;;; suderman-meow-test.el --- Focused Meow checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-meow-test.el -f ert-run-tests-batch-and-exit

(require 'cl-lib)
(require 'ert)
(require 'suderman-meow)

(defvar dirvish-mode-map)

(ert-deftest suderman/meow-insert-dispatches-by-state ()
  (with-temp-buffer
    (let (calls)
      (cl-letf (((symbol-function 'meow-beacon-insert)
                 (lambda () (setq calls (append calls '(beacon)))))
                ((symbol-function 'meow-insert)
                 (lambda () (setq calls (append calls '(insert)))))
                ((symbol-function 'suderman/meow--cancel-active-selection)
                 (lambda () (setq calls (append calls '(cancel))))))
        (setq-local meow-beacon-mode t)
        (suderman/meow-insert)
        (should (equal calls '(beacon)))

        (setq calls nil)
        (setq-local meow-beacon-mode nil)
        (suderman/meow-insert)
        (should (equal calls '(cancel insert)))))))

(ert-deftest suderman/meow-line-bound-overloads-insert-without-selection ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "  alpha  ; comment")
    (let (insert-points)
      (cl-letf (((symbol-function 'suderman/meow-insert)
                 (lambda () (push (point) insert-points))))
        (goto-char 5)
        (suderman/meow-insert-at-indentation)
        (suderman/meow-insert-at-indentation)
        (goto-char 5)
        (suderman/meow-insert-at-end-of-line)
        (suderman/meow-insert-at-end-of-line))
      (should (equal (nreverse insert-points) '(3 1 8 19))))))

(ert-deftest suderman/meow-keypad-runs-without-beacon-fanout ()
  (with-temp-buffer
    (let* ((overlay (make-overlay (point-min) (point-min)))
           (meow--beacon-overlays (list overlay))
           seen)
      (unwind-protect
          (cl-letf (((symbol-function 'meow-keypad)
                     (lambda () (setq seen meow--beacon-overlays))))
            (suderman/meow-keypad-once)
            (should-not seen)
            (should (equal meow--beacon-overlays (list overlay))))
        (delete-overlay overlay)))))

(ert-deftest suderman/meow-beacon-space-uses-one-shot-keypad ()
  (should (eq (lookup-key meow-beacon-state-keymap (kbd "SPC"))
              #'suderman/meow-keypad-once)))

(ert-deftest suderman/meow-save-copies-selection-or-buffer-path ()
  (let ((transient-mark-mode t)
        selection-saved)
    (with-temp-buffer
      (insert "selected")
      (set-mark (point-min))
      (activate-mark)
      (cl-letf (((symbol-function 'meow-save)
                 (lambda () (setq selection-saved t))))
        (suderman/meow-save))
      (should selection-saved)))
  (let ((kill-ring nil)
        (kill-ring-yank-pointer nil)
        (interprogram-cut-function nil))
    (with-temp-buffer
      (setq-local buffer-file-name "/tmp/example.txt")
      (suderman/meow-save)
      (should (equal (current-kill 0) buffer-file-name))))
  (with-temp-buffer
    (should-error (suderman/meow-save) :type 'user-error)))

(ert-deftest suderman/meow-shift-m-selects-line-rectangle-buffer ()
  (let ((transient-mark-mode t)
        (command (symbol-function 'suderman/meow-line-or-rectangle))
        states)
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (insert "alpha\nbeta\n")
        (setq-local meow-normal-mode t)
        (meow--cancel-selection)
        (goto-char 3)
        (setq last-command nil)
        (cl-letf (((symbol-function 'suderman/meow-line-or-rectangle)
                   (lambda (n)
                     (interactive "p")
                     (funcall command n)
                     (push (list (meow--selection-type)
                                 suderman/meow-line-position
                                 (point)
                                 (bound-and-true-p rectangle-mark-mode)
                                 (when (region-active-p)
                                   (cons (region-beginning) (region-end))))
                           states))))
          (execute-kbd-macro (kbd "M M M")))
        (setq states (nreverse states))
        (should (equal (nth 0 states)
                       '((expand . line) 3 6 nil (1 . 6))))
        (should (equal (nth 1 states)
                       '((expand . char) 3 3 t (3 . 3))))
        (should (equal (nth 2 states)
                       `((expand . char) 3 ,(point-max) nil
                         (,(point-min) . ,(point-max)))))))))

(ert-deftest suderman/meow-navigation-and-append-bindings ()
  (should meow-use-cursor-position-hack)
  (dolist (binding '(("$" . suderman/meow-smart-end-of-line)
                     ("^" . suderman/meow-smart-beginning-of-line)
                     ("a" . meow-append)
                     ("A" . suderman/meow-insert-at-end-of-line)
                     ("I" . suderman/meow-insert-at-indentation)
                     ("e" . suderman/meow-next-word)
                     ("E" . suderman/meow-next-symbol)
                     ("f" . suderman/meow-find)
                     ("F" . suderman/meow-find-backward)
                     ("N" . suderman/meow-buffer-end)
                     ("P" . suderman/meow-buffer-beginning)))
    (should (eq (lookup-key meow-normal-state-keymap (kbd (car binding)))
                (cdr binding)))))

(ert-deftest suderman/meow-line-bound-overloads-extend-word-selections ()
  (let ((transient-mark-mode t))
    (with-temp-buffer
      (emacs-lisp-mode)
      (insert "  alpha beta")
      (goto-char 5)
      (let ((last-command nil))
        (suderman/meow-visual))
      (suderman/meow-insert-at-end-of-line)
      (should (equal (cons (region-beginning) (region-end)) '(3 . 13)))

      (meow--cancel-selection)
      (goto-char 10)
      (let ((last-command nil))
        (suderman/meow-visual))
      (suderman/meow-insert-at-indentation)
      (should (equal (cons (region-beginning) (region-end)) '(3 . 13)))
      (suderman/meow-insert-at-indentation)
      (should (equal (cons (region-beginning) (region-end)) '(1 . 13))))))

(ert-deftest suderman/meow-find-motions-extend-word-selections ()
  (let ((transient-mark-mode t))
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (emacs-lisp-mode)
        (insert "alpha beta theta")
        (setq-local meow-normal-mode t)
        (goto-char 3)
        (execute-kbd-macro (kbd "m f t '"))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 13)))

        (meow--cancel-selection)
        (erase-buffer)
        (insert "token beta gamma")
        (goto-char 14)
        (execute-kbd-macro (kbd "m F t '"))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 17)))))))

(ert-deftest suderman/meow-thing-selections-stay-adjustable ()
  (let ((transient-mark-mode t))
    (dolist (case '((meow-beginning-of-thing . meow-right)
                    (meow-end-of-thing . meow-left)
                    (meow-inner-of-thing . meow-left)
                    (meow-bounds-of-thing . meow-right)))
      (with-temp-buffer
        (emacs-lisp-mode)
        (insert "alpha beta")
        (goto-char 3)
        (setq-local meow-normal-mode t)
        (funcall (car case) ?e)
        (should (equal (meow--selection-type) '(expand . char)))
        (let ((before (point)))
          (funcall (cdr case))
          (should (region-active-p))
          (should (equal (meow--selection-type) '(expand . char)))
          (should-not (= (point) before)))))))

(ert-deftest suderman/meow-parentheses-extend-selection ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "("))
              #'meow-left-expand))
  (should (eq (lookup-key meow-normal-state-keymap (kbd ")"))
              #'meow-right-expand))
  (should-not (lookup-key meow-normal-state-keymap (kbd "<")))
  (should-not (lookup-key meow-normal-state-keymap (kbd ">"))))

(ert-deftest suderman/meow-cheatsheet-labels-surround-prefix ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "s"))
              surround-keymap))
  (dolist (binding '(("s s" . surround-insert)
                     ("s k" . surround-kill)
                     ("s K" . surround-kill-outer)
                     ("s i" . surround-mark)
                     ("s o" . surround-mark-outer)
                     ("s d" . surround-delete)
                     ("s c" . surround-change)))
    (should (eq (lookup-key meow-normal-state-keymap (kbd (car binding)))
                (cdr binding))))
  (should (equal (string-trim
                  (meow--short-command-name
                   (lookup-key meow-normal-state-keymap (kbd "s"))))
                 "surround"))
  (dolist (command '(nil ignore))
    (should (equal (string-trim (meow--short-command-name command)) "")))
  (unwind-protect
      (save-window-excursion
        (meow-cheatsheet)
        (with-current-buffer "*Meow Cheatsheet*"
          (should (string-match-p "surround" (buffer-string)))
          (should-not (string-match-p "\\_<\\(nil\\|ignore\\)\\_>"
                                      (buffer-string)))))
    (when-let* ((buffer (get-buffer "*Meow Cheatsheet*")))
      (kill-buffer buffer))))

(ert-deftest suderman/backtick-opens-dashboard-from-editor-and-explorer-maps ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key ibuffer-mode-map (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key dired-mode-map (kbd "`"))
              #'suderman/dashboard))
  (require 'dirvish)
  (should (eq (lookup-key dirvish-mode-map (kbd "`"))
              #'suderman/dashboard)))

(ert-deftest suderman/dirvish-sidebar-entrypoints-use-s-and-leader-t-d ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "S"))
              #'suderman/dirvish-side-toggle))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "S"))
              #'suderman/dirvish-side-toggle))
  (should (eq (lookup-key suderman/leader-toggle-map (kbd "d"))
              #'suderman/dirvish-side-toggle))
  (should-not (lookup-key suderman/leader-toggle-map (kbd "t")))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "h"))
              #'meow-left))
  (should (eq (lookup-key ibuffer-mode-map (kbd "S"))
              #'suderman/ibuffer-dirvish-side))
  (should (eq (lookup-key ibuffer-mode-map (kbd "h"))
              #'suderman/ibuffer-toggle))
  (should (eq (lookup-key ibuffer-mode-map (kbd "l"))
              #'suderman/ibuffer-open))
  (dolist (key '("i" "H" "SPC"))
    (should-not (lookup-key ibuffer-mode-map (kbd key)))))

(ert-deftest suderman/leader-files-and-toggles-use-focused-commands ()
  (dolist (key '("/" ":" "\\" "d" "e" "p"))
    (should-not (lookup-key suderman/meow-leader-map (kbd key))))
  (should (eq (lookup-key suderman/leader-file-map (kbd "."))
              #'suderman/dirvish))
  (should (eq (lookup-key suderman/leader-file-map (kbd "f"))
              #'consult-fd))
  (should (eq (lookup-key suderman/leader-file-map (kbd "g"))
              #'consult-ripgrep))
  (should-not (lookup-key suderman/leader-search-map (kbd "g")))
  (dolist (binding '(("c" . display-fill-column-indicator-mode)
                     ("d" . suderman/dirvish-side-toggle)
                     ("h" . hl-line-mode)
                     ("l" . suderman/toggle-line-numbers)
                     ("r" . read-only-mode)
                     ("s" . jinx-mode)
                     ("v" . visual-line-mode)
                     ("w" . whitespace-mode)))
    (should (eq (lookup-key suderman/leader-toggle-map (kbd (car binding)))
                (cdr binding)))))

(provide 'suderman-meow-test)
;;; suderman-meow-test.el ends here
