;;; suderman-org-test.el --- Focused Org workflow checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-org-test.el -f ert-run-tests-batch-and-exit

(require 'ert)
(require 'org-agenda)
(require 'org-archive)
(require 'suderman-keys)
(require 'suderman-org)

(ert-deftest suderman/org-uses-phone-friendly-workflow-files ()
  (should auto-save-visited-mode)
  (should (= auto-save-visited-interval 3))
  (should (eq auto-save-visited-predicate
              #'suderman/org-auto-save-visited-p))
  (should (equal org-M-RET-may-split-line '((default . nil))))
  (should org-insert-heading-respect-content)
  (should (eq org-log-done 'time))
  (should org-log-into-drawer)
  (should org-startup-indented)
  (should org-startup-with-link-previews)
  (let ((directory (expand-file-name "~/org")))
    (should (equal org-directory directory))
    (should (equal org-attach-id-dir
                   (expand-file-name ".attach/" directory)))
    (should org-attach-use-inheritance)
    (should (equal org-id-locations-file
                   (expand-file-name "org-id-locations" suderman/state-dir)))
    (should (eq org-id-link-to-org-use-id
                'create-if-interactive-and-no-custom-id))
    (should
     (equal org-agenda-files
            (append
             (mapcar (lambda (file) (expand-file-name file directory))
                     '("inbox.org" "todo.org" "routines.org"))
             (suderman/org--direct-org-files
              (expand-file-name "calendar" directory))
             (suderman/org-context-files))))
    (should-not (member (expand-file-name "projects" directory)
                        org-agenda-files))
    (should (equal org-todo-keywords
                   '((sequence "TODO" "PROG" "EVAL" "HOLD" "|" "DONE"))))
    (should (equal org-default-notes-file
                   (expand-file-name "inbox.org" directory)))
    (should (equal org-capture-templates
                    `(("t" "Task" entry (file ,org-default-notes-file)
                       "* TODO %?\n  %U\n  %a")
                      ("n" "Note" entry (file ,org-default-notes-file)
                       "* %?\n  %U\n  %a")
                      ("i" "Idea" entry (file ,org-default-notes-file)
                       "* %?\n  %U\n  %a"))))
    (should (equal org-refile-targets
                   '((suderman/org-refile-files :maxlevel . 3))))
    (should (eq org-refile-use-outline-path 'file))
    (should-not org-outline-path-complete-in-steps)
    (should (eq org-refile-allow-creating-parent-nodes 'confirm))
    (should (equal org-archive-location "archive.org::"))
    (should-not org-archive-file-header-format)
    (should org-agenda-skip-scheduled-if-done)
    (should org-agenda-skip-deadline-if-done)
    (should
     (equal (assoc "d" org-agenda-custom-commands)
            '("d" "Dashboard"
              ((agenda "" ((org-agenda-span 7)))
               (todo "PROG" ((org-agenda-overriding-header "In progress")))
               (todo "EVAL" ((org-agenda-overriding-header "In review")))
               (todo "HOLD" ((org-agenda-overriding-header "On hold")))
               (todo "TODO" ((org-agenda-overriding-header "Todo")))))))))

(ert-deftest suderman/org-discovers-work-agenda-files-by-convention ()
  (let* ((work (make-temp-file "suderman-org-work-" t))
         (nonfiction (expand-file-name "nonfiction" work))
         (project (expand-file-name "beefresearch" nonfiction))
         (task (expand-file-name "2026-09-14-economic-value-of-feeds" project))
         (archive (expand-file-name "archive" nonfiction))
         (suderman (expand-file-name "suderman" work)))
    (unwind-protect
        (progn
          (dolist (directory (list task
                                   (expand-file-name "gta" archive)
                                   (expand-file-name "upick" nonfiction)
                                   (expand-file-name "not-a-file.org" nonfiction)
                                   (expand-file-name ".secret" nonfiction)
                                   (expand-file-name ".hidden" work)
                                   (expand-file-name "emacs" suderman)))
            (make-directory directory t))
          (dolist (file (list (expand-file-name "bcrc.org" nonfiction)
                              (expand-file-name "archive.org" nonfiction)
                              (expand-file-name "gta/gta.org" archive)
                              (expand-file-name ".private.org" nonfiction)
                              (expand-file-name "beefresearch.org" project)
                              (expand-file-name "quote-review.org" task)
                              (expand-file-name "notes.org"
                                                (expand-file-name "upick" nonfiction))
                              (expand-file-name ".secret.org"
                                                (expand-file-name ".secret" nonfiction))
                              (expand-file-name "client.org"
                                                (expand-file-name ".hidden" work))
                              (expand-file-name "davy.org" suderman)
                              (expand-file-name "emacs.org"
                                                (expand-file-name "emacs" suderman))))
            (with-temp-file file))
          (should
           (equal (suderman/org-work-agenda-files work)
                  (list (expand-file-name "bcrc.org" nonfiction)
                        (expand-file-name "beefresearch.org" project)
                        (expand-file-name "davy.org" suderman)
                        (expand-file-name "emacs/emacs.org" suderman))))
          (should-not
           (suderman/org-work-agenda-files
            (expand-file-name "missing" work))))
      (delete-directory work t))))

(ert-deftest suderman/org-builds-context-and-refile-file-lists ()
  (let* ((org-directory (make-temp-file "suderman-org-contexts-" t))
         (life (expand-file-name "life/kids.org" org-directory))
         (notes (expand-file-name "notes/reference.org" org-directory))
         (calendar (expand-file-name "calendar/import.org" org-directory))
         (client (expand-file-name "work/acme/acme.org" org-directory))
         (project (expand-file-name "work/acme/widget/widget.org" org-directory))
         (inbox (expand-file-name "inbox.org" org-directory))
         (todo (expand-file-name "todo.org" org-directory))
         (routines (expand-file-name "routines.org" org-directory))
         (draft (expand-file-name "draft.org" org-directory))
         (archive (expand-file-name "notes/archive.org" org-directory))
         (contexts (list life notes client project))
         (destinations (append (list todo routines) contexts)))
    (unwind-protect
        (progn
          (dolist (directory (list (file-name-directory life)
                                   (file-name-directory notes)
                                   (file-name-directory calendar)
                                   (file-name-directory project)))
            (make-directory directory t))
          (dolist (file (append (list inbox todo routines draft calendar archive)
                                contexts))
            (with-temp-file file))
          (should (equal (suderman/org-context-files) contexts))
          (with-temp-buffer
            (setq buffer-file-name inbox)
            (should (equal (suderman/org-refile-files) destinations)))
          (with-temp-buffer
            (setq buffer-file-name draft)
            (should (equal (suderman/org-refile-files)
                           (cons draft destinations))))
          (dolist (excluded (list inbox calendar archive))
            (with-temp-buffer
              (setq buffer-file-name excluded)
              (should-not (member excluded (suderman/org-refile-files)))))
          (should (cl-every #'file-regular-p destinations)))
      (delete-directory org-directory t))))

(ert-deftest suderman/org-excludes-archive-files-and-directories ()
  (let* ((directory (make-temp-file "suderman-org-files-" t))
         (active (expand-file-name "active.org" directory))
         (archive-file (expand-file-name "archive.org" directory))
         (archive-directory (expand-file-name "archive" directory))
         (archived (expand-file-name "client.org" archive-directory)))
    (unwind-protect
        (progn
          (make-directory archive-directory)
          (dolist (file (list active archive-file archived))
            (with-temp-file file))
          (should (equal (suderman/org--direct-org-files directory)
                         (list active)))
          (should-not (suderman/org--direct-org-files archive-directory)))
      (delete-directory directory t))))

(ert-deftest suderman/org-archives-into-a-sibling-file-with-context ()
  (let* ((directory (make-temp-file "suderman-org-archive-" t))
         (source (expand-file-name "cnrl.org" directory))
         (archive (expand-file-name "archive.org" directory))
         source-buffer archive-buffer)
    (unwind-protect
        (progn
          (with-temp-file source
            (insert "#+CATEGORY: cnrl\n"
                    "* Client work\n"
                    "** Analytics\n"
                    "*** DONE Fix GA4 cross-domain tracking\n"))
          (setq source-buffer (find-file-noselect source))
          (with-current-buffer source-buffer
            (goto-char (point-min))
            (search-forward "Fix GA4")
            (org-back-to-heading)
            (org-archive-subtree))
          (should (file-exists-p archive))
          (setq archive-buffer (find-file-noselect archive))
          (with-current-buffer archive-buffer
            (goto-char (point-min))
            (should (search-forward "Fix GA4 cross-domain tracking" nil t))
            (org-back-to-heading)
            (should (= (org-outline-level) 1))
            (should (org-entry-get nil "ARCHIVE_TIME"))
            (should (equal (org-entry-get nil "ARCHIVE_FILE") source))
            (should (equal (org-entry-get nil "ARCHIVE_OLPATH")
                           "Client work/Analytics"))
            (should (equal (org-entry-get nil "ARCHIVE_CATEGORY") "cnrl"))
            (should (equal (org-entry-get nil "ARCHIVE_TODO") "DONE"))))
      (when (buffer-live-p source-buffer)
        (kill-buffer source-buffer))
      (when (buffer-live-p archive-buffer)
        (kill-buffer archive-buffer))
      (delete-directory directory t))))

(ert-deftest suderman/org-archives-agenda-items-into-the-source-sibling ()
  (let* ((directory (make-temp-file "suderman-org-agenda-archive-" t))
         (source (expand-file-name "client.org" directory))
         (archive (expand-file-name "archive.org" directory))
         (agenda-buffer (generate-new-buffer " *suderman-archive-agenda*"))
         source-buffer archive-buffer marker)
    (unwind-protect
        (progn
          (with-temp-file source
            (insert "#+CATEGORY: client\n* DONE Archive from Agenda\n"))
          (setq source-buffer (find-file-noselect source))
          (with-current-buffer source-buffer
            (goto-char (point-min))
            (search-forward "Archive from Agenda")
            (org-back-to-heading)
            (setq marker (point-marker)))
          (with-current-buffer agenda-buffer
            (org-agenda-mode)
            (let ((inhibit-read-only t))
              (insert "Archive from Agenda\n")
              (add-text-properties (point-min) (point-max)
                                   `(org-marker ,marker)))
            (goto-char (point-min))
            (org-agenda-archive))
          (setq archive-buffer (find-file-noselect archive))
          (with-current-buffer archive-buffer
            (goto-char (point-min))
            (should (search-forward "Archive from Agenda" nil t))
            (org-back-to-heading)
            (should (= (org-outline-level) 1))))
      (when marker
        (set-marker marker nil))
      (dolist (buffer (list source-buffer archive-buffer agenda-buffer))
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest suderman/org-bulk-archive-saves-done-trees-in-their-own-archives ()
  (let* ((directory (make-temp-file "suderman-org-bulk-" t))
         (first (expand-file-name "first.org" directory))
         (second (expand-file-name "second.org" directory))
         (archive (expand-file-name "archive.org" directory))
         (override (expand-file-name "special.org" directory))
         (org-agenda-files (list first second))
         (org-archive-location "archive.org::")
         (org-archive-file-header-format nil)
         refreshed)
    (unwind-protect
        (progn
          (with-temp-file first
            (insert "* DONE Finished parent\n** DONE Finished child\n"
                    "* DONE Mixed parent\n** TODO Still open\n"
                    "** DONE Finished under mixed parent\n"
                    "* TODO Keep working\n"))
          (with-temp-file second
            (insert "* DONE Special\n:PROPERTIES:\n"
                    ":ARCHIVE: special.org::\n:END:\n"))
          (cl-letf (((symbol-function 'yes-or-no-p)
                     (lambda (&rest _) (error "Batch archiving prompted")))
                    ((symbol-function 'org-agenda-maybe-redo)
                     (lambda () (setq refreshed t))))
            (should (= (suderman/org-archive-done) 3)))
          (should refreshed)
          (should (string-match-p "Still open"
                                  (with-temp-buffer
                                    (insert-file-contents first)
                                    (buffer-string))))
          (should-not (string-match-p "Finished parent"
                                      (with-temp-buffer
                                        (insert-file-contents first)
                                        (buffer-string))))
          (with-temp-buffer
            (insert-file-contents archive)
            (should (search-forward "Finished parent" nil t))
            (should (search-forward "Finished child" nil t))
            (should (search-forward "Finished under mixed parent" nil t)))
          (with-temp-buffer
            (insert-file-contents override)
            (should (search-forward "Special" nil t))
            (should (search-forward "ARCHIVE_FILE" nil t)))
          (should (= (suderman/org-archive-done) 0)))
      (dolist (file (list first second archive override))
        (when-let* ((buffer (find-buffer-visiting file)))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest suderman/org-bulk-archive-confirms-or-accepts-prefix ()
  (let* ((directory (make-temp-file "suderman-org-confirm-" t))
         (source (expand-file-name "tasks.org" directory))
         (org-agenda-files (list source))
         (org-archive-location "archive.org::")
         (org-archive-file-header-format nil)
         (noninteractive nil)
         asked)
    (unwind-protect
        (progn
          (with-temp-file source (insert "* DONE Finished\n"))
          (cl-letf (((symbol-function 'yes-or-no-p)
                     (lambda (_prompt) (setq asked t) nil)))
            (should (= (call-interactively #'suderman/org-archive-done) 0))
            (should asked)
            (should (= (let ((current-prefix-arg '(4)))
                         (call-interactively #'suderman/org-archive-done))
                       1)))
          (should (file-exists-p (expand-file-name "archive.org" directory))))
      (dolist (file (list source (expand-file-name "archive.org" directory)))
        (when-let* ((buffer (find-buffer-visiting file)))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest suderman/org-auto-saves-only-safe-files-under-org-directory ()
  (let* ((org-directory (make-temp-file "suderman-org-" t))
         (inside (expand-file-name "todo.org" org-directory))
         (outside (make-temp-file "suderman-org-outside-" nil ".org"))
         (current t))
    (unwind-protect
        (cl-letf (((symbol-function 'verify-visited-file-modtime)
                   (lambda (&optional _buffer) current)))
          (with-temp-buffer
            (setq buffer-file-name inside)
            (org-mode)
            (should (suderman/org-auto-save-visited-p))
            (setq current nil)
            (should-not (suderman/org-auto-save-visited-p))
            (setq current t)
            (text-mode)
            (should-not (suderman/org-auto-save-visited-p)))
          (with-temp-buffer
            (setq buffer-file-name outside)
            (org-mode)
            (should-not (suderman/org-auto-save-visited-p))))
      (delete-directory org-directory t)
      (delete-file outside))))

(ert-deftest suderman/org-revert-refreshes-visible-agenda-only-for-synced-files ()
  (let* ((org-directory (make-temp-file "suderman-org-" t))
         (inside (expand-file-name "todo.org" org-directory))
         (outside (make-temp-file "suderman-org-outside-" nil ".org"))
         (agenda-buffer (generate-new-buffer " *suderman-org-agenda*"))
         refreshed)
    (unwind-protect
        (cl-letf (((symbol-function 'org-agenda-maybe-redo)
                   (lambda ()
                     (setq refreshed t)
                     (set-buffer agenda-buffer))))
          (with-temp-buffer
            (setq buffer-file-name inside)
            (org-mode)
            (should (local-variable-p 'after-revert-hook))
            (should (memq #'suderman/org-refresh-agenda-after-revert
                          after-revert-hook))
            (run-hooks 'after-revert-hook)
            (should refreshed)
            (should-not (eq (current-buffer) agenda-buffer)))
          (setq refreshed nil)
          (with-temp-buffer
            (setq buffer-file-name outside)
            (org-mode)
            (should-not
             (memq #'suderman/org-refresh-agenda-after-revert
                   after-revert-hook)))
          (should-not refreshed))
      (delete-directory org-directory t)
      (delete-file outside)
      (kill-buffer agenda-buffer))))

(ert-deftest suderman/org-prefix-enters-through-meow-keypad ()
  (should (eq (lookup-key suderman/meow-leader-map (kbd "o"))
              suderman/leader-org-map))
  (should (eq (lookup-key suderman/leader-org-map (kbd "g"))
              #'suderman/org-heading))
  (should (eq (lookup-key suderman/leader-org-map (kbd "n"))
              #'org-toggle-narrow-to-subtree))
  (should (eq (lookup-key suderman/leader-org-map (kbd "o"))
              #'suderman/org-dashboard))
  (should (eq (lookup-key suderman/leader-org-map (kbd "B"))
              #'suderman/org-archive-done))
  (let (called)
    (cl-letf (((symbol-function 'org-agenda)
               (lambda ()
                 (interactive)
                 (setq called t))))
      (with-temp-buffer
        (text-mode)
        (meow-normal-mode 1)
        (execute-kbd-macro (kbd "SPC o a"))
        (should called)))))

(ert-deftest suderman/org-agenda-keeps-buffer-and-file-shortcuts ()
  (should (eq (lookup-key org-agenda-mode-map (kbd ","))
              #'suderman/ibuffer-toggle))
  (should (eq (lookup-key org-agenda-mode-map (kbd "."))
              #'suderman/org-agenda-dirvish))
  (should (eq (lookup-key org-agenda-mode-map (kbd "C-c ,"))
              #'org-agenda-priority))
  (should (eq (lookup-key org-agenda-mode-map (kbd "C-c ."))
              #'org-agenda-goto-today))
  (let (called)
    (cl-letf (((symbol-function 'org-agenda-goto-today)
               (lambda () (interactive) (setq called 'today)))
              ((symbol-function 'org-agenda-priority)
               (lambda () (interactive) (setq called 'priority))))
      (with-temp-buffer
        (org-agenda-mode)
        (let ((window (selected-window))
              (previous (window-buffer)))
          (unwind-protect
              (progn
                (set-window-buffer window (current-buffer))
                (execute-kbd-macro (kbd "SPC c ."))
                (should (eq called 'today))
                (execute-kbd-macro (kbd "SPC c ,"))
                (should (eq called 'priority)))
            (set-window-buffer window previous)))))))

(ert-deftest suderman/org-agenda-dirvish-uses-selected-entry-file ()
  (let* ((source (generate-new-buffer " *agenda-source*"))
         (agenda (generate-new-buffer " *agenda-files*"))
         (file "/tmp/suderman-agenda-entry.org")
         (marker (with-current-buffer source
                   (setq buffer-file-name file)
                   (point-marker)))
         opened)
    (unwind-protect
        (cl-letf (((symbol-function 'suderman/dirvish)
                   (lambda (path) (setq opened path))))
          (with-current-buffer agenda
            (org-agenda-mode)
            (let ((inhibit-read-only t))
              (insert "Entry\n")
              (put-text-property (point-min) (point-max)
                                 'org-marker marker))
            (goto-char (point-min))
            (suderman/org-agenda-dirvish)
            (should (equal opened file))
            (remove-text-properties (point-min) (point-max)
                                    '(org-marker nil))
            (suderman/org-agenda-dirvish)
            (should (equal opened org-directory))))
      (set-marker marker nil)
      (kill-buffer source)
      (kill-buffer agenda))))

(ert-deftest suderman/org-dashboard-opens-the-direct-custom-view ()
  (let (received)
    (cl-letf (((symbol-function 'org-agenda)
               (lambda (arg keys &optional _restriction)
                 (setq received (list arg keys)))))
      (call-interactively #'suderman/org-dashboard))
    (should (equal received '(nil "d")))))

(ert-deftest suderman/org-item-commands-follow-buffer-context ()
  (dolist (binding '(("A" . suderman/org-archive)
                     ("d" . suderman/org-deadline)
                     ("e" . suderman/org-export)
                     ("g" . suderman/org-heading)
                     ("i" . suderman/org-insert-link)
                     ("r" . suderman/org-refile)
                     ("s" . suderman/org-schedule)
                     ("t" . suderman/org-todo)
                     ("x" . suderman/org-toggle-checkbox)))
    (should (eq (lookup-key suderman/leader-org-map (kbd (car binding)))
                (cdr binding))))
  (let (called)
    (cl-letf (((symbol-function 'consult-org-agenda)
               (lambda () (interactive) (setq called 'consult-org-agenda)))
              ((symbol-function 'org-agenda-archive)
               (lambda () (interactive) (setq called 'org-agenda-archive)))
              ((symbol-function 'consult-org-heading)
               (lambda () (interactive) (setq called 'consult-org-heading)))
              ((symbol-function 'org-agenda-deadline)
               (lambda () (interactive) (setq called 'org-agenda-deadline)))
              ((symbol-function 'org-agenda-refile)
               (lambda () (interactive) (setq called 'org-agenda-refile)))
              ((symbol-function 'org-agenda-schedule)
               (lambda () (interactive) (setq called 'org-agenda-schedule)))
              ((symbol-function 'org-agenda-todo)
               (lambda () (interactive) (setq called 'org-agenda-todo)))
              ((symbol-function 'org-agenda-write)
               (lambda () (interactive) (setq called 'org-agenda-write)))
              ((symbol-function 'org-deadline)
               (lambda () (interactive) (setq called 'org-deadline)))
              ((symbol-function 'org-export-dispatch)
               (lambda () (interactive) (setq called 'org-export-dispatch)))
              ((symbol-function 'org-archive-subtree)
               (lambda () (interactive) (setq called 'org-archive-subtree)))
              ((symbol-function 'org-insert-link)
               (lambda () (interactive) (setq called 'org-insert-link)))
              ((symbol-function 'org-refile)
               (lambda () (interactive) (setq called 'org-refile)))
              ((symbol-function 'org-schedule)
               (lambda () (interactive) (setq called 'org-schedule)))
              ((symbol-function 'org-todo)
               (lambda () (interactive) (setq called 'org-todo)))
              ((symbol-function 'org-todo-list)
               (lambda () (interactive) (setq called 'org-todo-list)))
              ((symbol-function 'org-toggle-checkbox)
               (lambda () (interactive) (setq called 'org-toggle-checkbox))))
      (dolist (case '((org-mode suderman/org-archive org-archive-subtree)
                      (org-mode suderman/org-deadline org-deadline)
                      (org-mode suderman/org-export org-export-dispatch)
                      (org-mode suderman/org-heading consult-org-heading)
                      (org-mode suderman/org-insert-link org-insert-link)
                      (org-mode suderman/org-refile org-refile)
                      (org-mode suderman/org-schedule org-schedule)
                      (org-mode suderman/org-todo org-todo)
                      (org-mode suderman/org-toggle-checkbox org-toggle-checkbox)
                      (org-agenda-mode suderman/org-archive org-agenda-archive)
                      (org-agenda-mode suderman/org-deadline org-agenda-deadline)
                      (org-agenda-mode suderman/org-export org-agenda-write)
                      (org-agenda-mode suderman/org-heading consult-org-agenda)
                      (org-agenda-mode suderman/org-refile org-agenda-refile)
                      (org-agenda-mode suderman/org-schedule org-agenda-schedule)
                      (org-agenda-mode suderman/org-todo org-agenda-todo)
                      (markdown-ts-mode suderman/org-deadline org-todo-list)
                      (markdown-ts-mode suderman/org-heading consult-org-agenda)
                      (markdown-ts-mode suderman/org-refile org-todo-list)
                      (markdown-ts-mode suderman/org-schedule org-todo-list)
                      (markdown-ts-mode suderman/org-todo org-todo-list)))
        (setq called nil)
        (with-temp-buffer
          (funcall (nth 0 case))
          (call-interactively (nth 1 case)))
        (should (eq called (nth 2 case))))
      (dolist (case '((org-agenda-mode suderman/org-insert-link)
                      (org-agenda-mode suderman/org-toggle-checkbox)
                      (markdown-ts-mode suderman/org-archive)
                      (markdown-ts-mode suderman/org-export)
                      (markdown-ts-mode suderman/org-insert-link)
                      (markdown-ts-mode suderman/org-toggle-checkbox)))
        (with-temp-buffer
          (funcall (nth 0 case))
          (should-error (call-interactively (nth 1 case))
                        :type 'user-error))))))

(ert-deftest suderman/org-item-commands-pass-prefix-arguments ()
  (let (received)
    (cl-letf (((symbol-function 'org-schedule)
               (lambda (arg)
                 (interactive "P")
                 (setq received arg))))
      (with-temp-buffer
        (org-mode)
        (let ((current-prefix-arg '(4)))
          (call-interactively #'suderman/org-schedule))))
    (should (equal received '(4)))))

(ert-deftest suderman/org-indent-toggle-is-under-toggles ()
  (should (eq (lookup-key suderman/leader-toggle-map (kbd "o"))
              #'org-indent-mode)))

(ert-deftest suderman/org-buffers-indent-and-scale-headings ()
  (require 'org)
  (with-temp-buffer
    (org-mode)
    (should (bound-and-true-p org-indent-mode))
    (should (= (face-attribute 'org-level-1 :height nil) 1.35))
    (should (= (face-attribute 'org-level-2 :height nil) 1.22))
    (org-indent-mode -1)
    (should-not (bound-and-true-p org-indent-mode))))

(ert-deftest suderman/org-superstar-prettifies-org-buffers ()
  (with-temp-buffer
    (insert "- item\n")
    (org-mode)
    (font-lock-ensure)
    (should (bound-and-true-p org-superstar-mode))
    (goto-char (point-min))
    (let ((bullet (get-text-property (point) 'display)))
      (should (stringp bullet))
      (should-not (equal bullet "-")))))

(ert-deftest suderman/org-mouse-cycles-todo-on-left-click ()
  (let ((org-todo-keywords '((sequence "TODO" "NEXT" "|" "DONE"))))
    (with-temp-buffer
      (insert "* TODO item\n")
      (org-mode)
      (font-lock-ensure)
      (goto-char (+ (point-min) 2))
      (let ((map (get-text-property (point) 'keymap)))
        (should (eq (lookup-key map [mouse-1])
                    #'suderman/org-mouse-cycle-todo)))
      (cl-letf (((symbol-function 'mouse-set-point)
                 (lambda (_event) (goto-char (+ (point-min) 2)))))
        (suderman/org-mouse-cycle-todo nil))
      (should (equal (org-get-todo-state) "NEXT"))
      (cl-letf (((symbol-function 'mouse-set-point)
                 (lambda (_event) (goto-char (+ (point-min) 2)))))
        (suderman/org-mouse-cycle-todo nil)
        (should (equal (org-get-todo-state) "DONE"))
        (suderman/org-mouse-cycle-todo nil)
        (should (equal (org-get-todo-state) "TODO"))))))

(ert-deftest suderman/org-mouse-todo-menu-clears-state ()
  (let ((org-todo-keywords '((sequence "TODO" "NEXT" "|" "DONE"))))
    (with-temp-buffer
      (insert "* DONE item\n")
      (org-mode)
      (goto-char (+ (point-min) 2))
      (let ((clear
             (cl-find-if
              (lambda (item)
                (and (vectorp item)
                     (equal (aref item 0) "Clear")))
              (org-mouse-todo-menu "DONE"))))
        (should clear)
        (should (equal (aref clear 1) '(org-todo "")))
        (should (aref clear 2))
        (eval (aref clear 1))
        (should-not (org-get-todo-state))))))

(provide 'suderman-org-test)
;;; suderman-org-test.el ends here
