;;; suderman-windows-test.el --- Focused window resize checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-windows-test.el -f ert-run-tests-batch-and-exit

(require 'ert)
(require 'suderman-windows)

(ert-deftest suderman/resize-window-moves-trailing-edge ()
  (save-window-excursion
    (delete-other-windows)
    (let ((left (selected-window))
          (right (split-window-right)))
      (select-window left)
      (let ((width (window-total-width left)))
        (suderman/resize-window-right)
        (should (> (window-total-width left) width)))
      (balance-windows)
      (select-window right)
      (let ((width (window-total-width right)))
        (suderman/resize-window-left)
        (should (> (window-total-width right) width))))
    (delete-other-windows)
    (let ((top (selected-window))
          (bottom (split-window-below)))
      (select-window top)
      (let ((height (window-total-height top)))
        (suderman/resize-window-down)
        (should (> (window-total-height top) height)))
      (balance-windows)
      (select-window bottom)
      (let ((height (window-total-height bottom)))
        (suderman/resize-window-up)
        (should (> (window-total-height bottom) height))))))

(ert-deftest suderman/resize-window-moves-trailing-edge-in-nested-layout ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((left (selected-window))
           (middle (split-window-right))
           (right (with-selected-window middle (split-window-right)))
           (left-width (window-total-width left))
           (middle-width (window-total-width middle))
           (right-width (window-total-width right)))
      (select-window left)
      (suderman/resize-window-left)
      (should (= (window-total-width left) (- left-width 5)))
      (should (= (window-total-width middle) (+ middle-width 5)))
      (should (= (window-total-width right) right-width))
      (balance-windows)
      (select-window middle)
      (setq left-width (window-total-width left)
            middle-width (window-total-width middle)
            right-width (window-total-width right))
      (suderman/resize-window-left)
      (should (= (window-total-width left) left-width))
      (should (= (window-total-width middle) (- middle-width 5)))
      (should (= (window-total-width right) (+ right-width 5)))
      (balance-windows)
      (select-window right)
      (setq left-width (window-total-width left)
            middle-width (window-total-width middle)
            right-width (window-total-width right))
      (suderman/resize-window-left)
      (should (= (window-total-width left) left-width))
      (should (= (window-total-width middle) (- middle-width 5)))
      (should (= (window-total-width right) (+ right-width 5))))
    (delete-other-windows)
    (let* ((top (selected-window))
           (middle (split-window-below))
           (bottom (with-selected-window middle (split-window-below)))
           (top-height (window-total-height top))
           (middle-height (window-total-height middle))
           (bottom-height (window-total-height bottom)))
      (select-window top)
      (suderman/resize-window-up)
      (should (= (window-total-height top) (- top-height 3)))
      (should (= (window-total-height middle) (+ middle-height 3)))
      (should (= (window-total-height bottom) bottom-height))
      (balance-windows)
      (select-window middle)
      (setq top-height (window-total-height top)
            middle-height (window-total-height middle)
            bottom-height (window-total-height bottom))
      (suderman/resize-window-up)
      (should (= (window-total-height top) top-height))
      (should (= (window-total-height middle) (- middle-height 3)))
      (should (= (window-total-height bottom) (+ bottom-height 3)))
      (balance-windows)
      (select-window bottom)
      (setq top-height (window-total-height top)
            middle-height (window-total-height middle)
            bottom-height (window-total-height bottom))
      (suderman/resize-window-up)
      (should (= (window-total-height top) top-height))
      (should (= (window-total-height middle) (- middle-height 3)))
      (should (= (window-total-height bottom) (+ bottom-height 3))))))

(provide 'suderman-windows-test)
;;; suderman-windows-test.el ends here
