;;; suderman-org-test.el --- Focused Org workflow checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-org-test.el -f ert-run-tests-batch-and-exit

(require 'ert)
(require 'org-agenda)
(require 'suderman-keys)
(require 'suderman-org)

(ert-deftest suderman/org-uses-phone-friendly-workflow-files ()
  (should (equal org-M-RET-may-split-line '((default . nil))))
  (should org-insert-heading-respect-content)
  (should (eq org-log-done 'time))
  (should org-log-into-drawer)
  (should org-startup-indented)
  (let ((directory (expand-file-name "~/org")))
    (should (equal org-directory directory))
    (should (equal org-agenda-files
                   (mapcar (lambda (file) (expand-file-name file directory))
                            '("inbox.org" "todo.org" "routines.org" "fresha.org"))))
    (should (equal org-todo-keywords
                   '((sequence "TODO" "PROG" "EVAL" "HOLD" "|" "DONE"))))
    (should (equal org-default-notes-file
                   (expand-file-name "inbox.org" directory)))
    (should (equal org-capture-templates
                    `(("t" "Task" entry (file ,org-default-notes-file)
                       "* TODO %?\n  %U\n  %a")
                      ("n" "Note" entry (file ,org-default-notes-file)
                       "* %?\n  %U\n  %a")
                      ("i" "Idea" entry
                       (file ,(expand-file-name "ideas.org" directory))
                       "* %?\n  %U\n  %a"))))
    (should (equal org-refile-targets
                    (mapcar
                     (lambda (file)
                       (cons (expand-file-name file directory) '(:maxlevel . 3)))
                     '("todo.org" "routines.org" "ideas.org" "archive.org"))))
    (should (equal org-archive-location
                   (concat (expand-file-name "archive.org" directory)
                           "::* From %s")))
    (should org-agenda-skip-scheduled-if-done)
    (should org-agenda-skip-deadline-if-done)
    (should (assoc "d" org-agenda-custom-commands))))

(ert-deftest suderman/org-prefix-enters-through-meow-keypad ()
  (should (eq (lookup-key suderman/meow-leader-map (kbd "o"))
              suderman/leader-org-map))
  (should (eq (lookup-key suderman/leader-org-map (kbd "g"))
              #'suderman/org-heading))
  (let (called)
    (cl-letf (((symbol-function 'org-agenda)
               (lambda ()
                 (interactive)
                 (setq called t))))
      (with-temp-buffer
        (text-mode)
        (meow-normal-mode 1)
        (execute-kbd-macro (kbd "SPC o a"))
        (should called)))))

(ert-deftest suderman/org-item-commands-follow-buffer-context ()
  (dolist (binding '(("d" . suderman/org-deadline)
                     ("e" . suderman/org-export)
                     ("g" . suderman/org-heading)
                     ("i" . suderman/org-insert-link)
                     ("r" . suderman/org-refile)
                     ("s" . suderman/org-schedule)
                     ("t" . suderman/org-todo)
                     ("x" . suderman/org-toggle-checkbox)))
    (should (eq (lookup-key suderman/leader-org-map (kbd (car binding)))
                (cdr binding))))
  (let (called)
    (cl-letf (((symbol-function 'consult-org-agenda)
               (lambda () (interactive) (setq called 'consult-org-agenda)))
              ((symbol-function 'consult-org-heading)
               (lambda () (interactive) (setq called 'consult-org-heading)))
              ((symbol-function 'org-agenda-deadline)
               (lambda () (interactive) (setq called 'org-agenda-deadline)))
              ((symbol-function 'org-agenda-refile)
               (lambda () (interactive) (setq called 'org-agenda-refile)))
              ((symbol-function 'org-agenda-schedule)
               (lambda () (interactive) (setq called 'org-agenda-schedule)))
              ((symbol-function 'org-agenda-todo)
               (lambda () (interactive) (setq called 'org-agenda-todo)))
              ((symbol-function 'org-agenda-write)
               (lambda () (interactive) (setq called 'org-agenda-write)))
              ((symbol-function 'org-deadline)
               (lambda () (interactive) (setq called 'org-deadline)))
              ((symbol-function 'org-export-dispatch)
               (lambda () (interactive) (setq called 'org-export-dispatch)))
              ((symbol-function 'org-insert-link)
               (lambda () (interactive) (setq called 'org-insert-link)))
              ((symbol-function 'org-refile)
               (lambda () (interactive) (setq called 'org-refile)))
              ((symbol-function 'org-schedule)
               (lambda () (interactive) (setq called 'org-schedule)))
              ((symbol-function 'org-todo)
               (lambda () (interactive) (setq called 'org-todo)))
              ((symbol-function 'org-todo-list)
               (lambda () (interactive) (setq called 'org-todo-list)))
              ((symbol-function 'org-toggle-checkbox)
               (lambda () (interactive) (setq called 'org-toggle-checkbox))))
      (dolist (case '((org-mode suderman/org-deadline org-deadline)
                      (org-mode suderman/org-export org-export-dispatch)
                      (org-mode suderman/org-heading consult-org-heading)
                      (org-mode suderman/org-insert-link org-insert-link)
                      (org-mode suderman/org-refile org-refile)
                      (org-mode suderman/org-schedule org-schedule)
                      (org-mode suderman/org-todo org-todo)
                      (org-mode suderman/org-toggle-checkbox org-toggle-checkbox)
                      (org-agenda-mode suderman/org-deadline org-agenda-deadline)
                      (org-agenda-mode suderman/org-export org-agenda-write)
                      (org-agenda-mode suderman/org-heading consult-org-agenda)
                      (org-agenda-mode suderman/org-refile org-agenda-refile)
                      (org-agenda-mode suderman/org-schedule org-agenda-schedule)
                      (org-agenda-mode suderman/org-todo org-agenda-todo)
                      (markdown-ts-mode suderman/org-deadline org-todo-list)
                      (markdown-ts-mode suderman/org-heading consult-org-agenda)
                      (markdown-ts-mode suderman/org-refile org-todo-list)
                      (markdown-ts-mode suderman/org-schedule org-todo-list)
                      (markdown-ts-mode suderman/org-todo org-todo-list)))
        (setq called nil)
        (with-temp-buffer
          (funcall (nth 0 case))
          (call-interactively (nth 1 case)))
        (should (eq called (nth 2 case))))
      (dolist (case '((org-agenda-mode suderman/org-insert-link)
                      (org-agenda-mode suderman/org-toggle-checkbox)
                      (markdown-ts-mode suderman/org-export)
                      (markdown-ts-mode suderman/org-insert-link)
                      (markdown-ts-mode suderman/org-toggle-checkbox)))
        (with-temp-buffer
          (funcall (nth 0 case))
          (should-error (call-interactively (nth 1 case))
                        :type 'user-error))))))

(ert-deftest suderman/org-item-commands-pass-prefix-arguments ()
  (let (received)
    (cl-letf (((symbol-function 'org-schedule)
               (lambda (arg)
                 (interactive "P")
                 (setq received arg))))
      (with-temp-buffer
        (org-mode)
        (let ((current-prefix-arg '(4)))
          (call-interactively #'suderman/org-schedule))))
    (should (equal received '(4)))))

(ert-deftest suderman/org-indent-toggle-is-under-toggles ()
  (should (eq (lookup-key suderman/leader-toggle-map (kbd "o"))
              #'org-indent-mode)))

(ert-deftest suderman/org-buffers-indent-and-scale-headings ()
  (require 'org)
  (with-temp-buffer
    (org-mode)
    (should (bound-and-true-p org-indent-mode))
    (should (= (face-attribute 'org-level-1 :height nil) 1.35))
    (should (= (face-attribute 'org-level-2 :height nil) 1.22))
    (org-indent-mode -1)
    (should-not (bound-and-true-p org-indent-mode))))

(ert-deftest suderman/org-superstar-prettifies-org-buffers ()
  (with-temp-buffer
    (insert "- item\n")
    (org-mode)
    (font-lock-ensure)
    (should (bound-and-true-p org-superstar-mode))
    (goto-char (point-min))
    (let ((bullet (get-text-property (point) 'display)))
      (should (stringp bullet))
      (should-not (equal bullet "-")))))

(ert-deftest suderman/org-mouse-cycles-todo-on-left-click ()
  (let ((org-todo-keywords '((sequence "TODO" "NEXT" "|" "DONE"))))
    (with-temp-buffer
      (insert "* TODO item\n")
      (org-mode)
      (font-lock-ensure)
      (goto-char (+ (point-min) 2))
      (let ((map (get-text-property (point) 'keymap)))
        (should (eq (lookup-key map [mouse-1])
                    #'suderman/org-mouse-cycle-todo)))
      (cl-letf (((symbol-function 'mouse-set-point)
                 (lambda (_event) (goto-char (+ (point-min) 2)))))
        (suderman/org-mouse-cycle-todo nil))
      (should (equal (org-get-todo-state) "NEXT"))
      (cl-letf (((symbol-function 'mouse-set-point)
                 (lambda (_event) (goto-char (+ (point-min) 2)))))
        (suderman/org-mouse-cycle-todo nil)
        (should (equal (org-get-todo-state) "DONE"))
        (suderman/org-mouse-cycle-todo nil)
        (should (equal (org-get-todo-state) "TODO"))))))

(ert-deftest suderman/org-mouse-todo-menu-clears-state ()
  (let ((org-todo-keywords '((sequence "TODO" "NEXT" "|" "DONE"))))
    (with-temp-buffer
      (insert "* DONE item\n")
      (org-mode)
      (goto-char (+ (point-min) 2))
      (let ((clear
             (cl-find-if
              (lambda (item)
                (and (vectorp item)
                     (equal (aref item 0) "Clear")))
              (org-mouse-todo-menu "DONE"))))
        (should clear)
        (should (equal (aref clear 1) '(org-todo "")))
        (should (aref clear 2))
        (eval (aref clear 1))
        (should-not (org-get-todo-state))))))

(provide 'suderman-org-test)
;;; suderman-org-test.el ends here
