;;; suderman-input-test.el --- Input and editing behavior checks -*- lexical-binding: t; -*-

;;; Commentary:
;; Tests for custom behavior with enough moving parts to merit a safety net.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'pixel-scroll)
(require 'suderman-android)
(require 'suderman-completion)
(require 'suderman-meow)
(require 'touch-screen)
(require 'vertico-mouse)

(defvar global-text-scale-adjust-limits)
(defvar vertico--scroll)
(defvar vertico-count)
(defvar vertico-scroll-margin)

;; Vertico touch input

(ert-deftest suderman/android-vertico-touch-drag-scrolls-candidates ()
  (let ((events '((touchscreen-update ((1 . update-position)))
                  (touchscreen-end (1 . end-position) nil)))
        (vertico--scroll 5)
        (vertico-count 10)
        (vertico-scroll-margin 2)
        gotos
        exhibits
        exited)
    (cl-letf (((symbol-function 'posn-window)
               (lambda (_posn) (selected-window)))
              ((symbol-function 'posn-x-y)
               (lambda (_posn) '(0 . 0)))
              ((symbol-function 'touch-screen-relative-xy)
               (lambda (_posn _window) '(0 . 30)))
              ((symbol-function 'default-line-height) (lambda () 10))
              ((symbol-function 'read-event) (lambda () (pop events)))
              ((symbol-function 'vertico--goto)
               (lambda (index) (push index gotos)))
              ((symbol-function 'vertico--exhibit)
               (lambda () (setq exhibits (1+ (or exhibits 0)))))
              ((symbol-function 'vertico-exit) (lambda () (setq exited t))))
      (suderman/vertico-touchscreen-begin
       '(touchscreen-begin (1 . begin-position)))
      (should (equal gotos '(4)))
      (should (= exhibits 1))
      (should-not exited))))

(ert-deftest suderman/android-vertico-touch-tap-selects-and-exits ()
  (let ((events '((touchscreen-end (1 . end-position) nil)))
        gotos
        exited)
    (cl-letf (((symbol-function 'posn-window)
               (lambda (_posn) (selected-window)))
              ((symbol-function 'posn-x-y)
               (lambda (_posn) '(0 . 0)))
              ((symbol-function 'read-event) (lambda () (pop events)))
              ((symbol-function 'vertico-mouse--index) (lambda (_event) 7))
              ((symbol-function 'vertico--goto)
               (lambda (index) (push index gotos)))
              ((symbol-function 'vertico-exit) (lambda () (setq exited t))))
      (suderman/vertico-touchscreen-begin
       '(touchscreen-begin (1 . begin-position)))
      (should (equal gotos '(7)))
      (should exited))))

(ert-deftest suderman/android-vertico-touch-allows-tap-jitter ()
  (let ((events '((touchscreen-update ((1 . update-position)))
                  (touchscreen-end (1 . end-position) nil)))
        (vertico--scroll 5)
        (vertico-count 10)
        (vertico-scroll-margin 2)
        gotos
        exited)
    (cl-letf (((symbol-function 'posn-window)
               (lambda (_posn) (selected-window)))
              ((symbol-function 'posn-x-y)
               (lambda (_posn) '(0 . 0)))
              ((symbol-function 'touch-screen-relative-xy)
               (lambda (_posn _window) '(3 . 3)))
              ((symbol-function 'default-line-height) (lambda () 20))
              ((symbol-function 'read-event) (lambda () (pop events)))
              ((symbol-function 'vertico-mouse--index) (lambda (_event) 7))
              ((symbol-function 'vertico--goto)
               (lambda (index) (push index gotos)))
              ((symbol-function 'vertico--exhibit) #'ignore)
              ((symbol-function 'vertico-exit) (lambda () (setq exited t))))
      (suderman/vertico-touchscreen-begin
       '(touchscreen-begin (1 . begin-position)))
      (should (equal gotos '(7)))
      (should exited))))

(ert-deftest suderman/android-vertico-touch-redraws-only-between-rows ()
  (let ((events '((touchscreen-update ((1 . update-1)))
                  (touchscreen-update ((1 . update-2)))
                  (touchscreen-end (1 . end-position) nil)))
        (vertico--scroll 5)
        (vertico-count 10)
        (vertico-scroll-margin 2)
        gotos
        exhibits)
    (cl-letf (((symbol-function 'posn-window)
               (lambda (_posn) (selected-window)))
              ((symbol-function 'posn-x-y)
               (lambda (_posn) '(0 . 0)))
              ((symbol-function 'touch-screen-relative-xy)
               (lambda (posn _window)
                 (if (eq posn 'update-1) '(0 . 25) '(0 . 29))))
              ((symbol-function 'default-line-height) (lambda () 40))
              ((symbol-function 'read-event) (lambda () (pop events)))
              ((symbol-function 'vertico--goto)
               (lambda (index) (push index gotos)))
              ((symbol-function 'vertico--exhibit)
               (lambda () (setq exhibits (1+ (or exhibits 0))))))
      (suderman/vertico-touchscreen-begin
       '(touchscreen-begin (1 . begin-position)))
      (should (equal gotos '(6)))
      (should (= exhibits 1)))))


;; Android gestures and modifiers

(ert-deftest suderman/android-modifier-buttons-toggle-off ()
  (dolist (case '((suderman/android-toggle-control-modifier control)
                  (suderman/android-toggle-meta-modifier meta)))
    (let* ((function (car case))
           (modifier (cadr case))
           (events (list 'tool-bar modifier))
           redraw-states)
      (cl-letf (((symbol-function 'read-event)
                 (lambda (&rest _) (pop events)))
                ((symbol-function 'event-basic-type) #'identity)
                ((symbol-function 'frame-toggle-on-screen-keyboard) #'ignore)
                ((symbol-function 'suderman/tool-bar-refresh)
                 (lambda (&rest _)
                   (push (copy-sequence modifier-bar-modifier-list)
                         redraw-states)))
                ((symbol-function 'redisplay) #'ignore)
                ((symbol-function 'set-text-conversion-style) #'ignore))
        (should (equal (funcall function nil) []))
        (should-not events)
        (should (equal (nreverse redraw-states)
                       (list (list modifier) nil nil)))))))

(ert-deftest suderman/android-modifier-buttons-toggle-independently ()
  (dolist (case '((suderman/android-toggle-control-modifier
                   control meta)
                  (suderman/android-toggle-meta-modifier
                   meta control)))
    (let* ((function (car case))
           (initial (cadr case))
           (remaining (caddr case))
           (events (list 'tool-bar remaining 'tool-bar initial ?x))
           applied)
      (cl-letf (((symbol-function 'read-event)
                 (lambda (&rest _) (pop events)))
                ((symbol-function 'event-basic-type) #'identity)
                ((symbol-function 'frame-toggle-on-screen-keyboard) #'ignore)
                ((symbol-function 'suderman/tool-bar-refresh) #'ignore)
                ((symbol-function 'redisplay) #'ignore)
                ((symbol-function 'set-text-conversion-style) #'ignore)
                ((symbol-function 'tool-bar-apply-modifiers)
                 (lambda (event modifiers)
                   (setq applied (list event modifiers))
                   'translated)))
        (should (equal (funcall function nil) [translated]))
        (should-not events)
        (should (equal applied (list ?x (list remaining))))))))

(ert-deftest suderman/android-toolbar-toggles-the-software-keyboard ()
  (let ((frame 'phone-frame)
        (width 600)
        (height 1000)
        full-size
        calls)
    (cl-letf (((symbol-function 'selected-frame) (lambda () frame))
              ((symbol-function 'frame-pixel-width) (lambda (_) width))
              ((symbol-function 'frame-pixel-height) (lambda (_) height))
              ((symbol-function 'frame-parameter)
               (lambda (_ parameter)
                 (should (eq parameter
                             'suderman/android-keyboard-full-size))
                 full-size))
              ((symbol-function 'set-frame-parameter)
               (lambda (_ parameter value)
                 (should (eq parameter
                             'suderman/android-keyboard-full-size))
                 (setq full-size value)))
              ((symbol-function 'frame-toggle-on-screen-keyboard)
               (lambda (&rest arguments) (push arguments calls))))
      (suderman/android-toggle-keyboard)
      (setq height 600)
      (suderman/android-toggle-keyboard)
      (setq height 1000)
      (suderman/android-toggle-keyboard)
      ;; An external dismissal also restores the full frame height.
      (setq height 600)
      (setq height 1000)
      (suderman/android-toggle-keyboard)
      (should (equal (nreverse calls)
                     '((phone-frame nil) (phone-frame t)
                       (phone-frame nil) (phone-frame nil))))
      (should (equal full-size '(600 . 1000))))))

(ert-deftest suderman/android-touch-scroll-flings-only-after-scrolling ()
  (let ((touch-screen-current-tool '(1 nil nil scroll))
        events)
    (cl-letf (((symbol-function 'pixel-scroll-start-momentum)
               (lambda (event) (push event events))))
      (suderman/android-start-touch-momentum
       '(touchscreen-update ((1 . position))))
      (let ((touch-screen-current-tool '(1 nil nil held)))
        (suderman/android-start-touch-momentum
         '(touchscreen-end (1 . position) nil)))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (2 . position) nil))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (1 . position) t))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (1 . position) nil))
      (should (equal events
                     '((touchscreen-end (1 . position) nil)))))))

(ert-deftest suderman/android-touch-word-selection-extends-with-meow-motion ()
  (let ((system-type 'android)
        (touch-screen-word-select t)
        (transient-mark-mode t))
    (save-window-excursion
      (dolist (reverse '(nil t))
        (dolist (key '("h" "j" "k" "l"))
          (with-temp-buffer
            (set-window-buffer (selected-window) (current-buffer))
            (insert "alpha beta\ngamma delta\nomega zeta\n")
            (setq-local meow-normal-mode t)
            (cl-letf (((symbol-function 'beep) #'ignore))
              (touch-screen-hold
               (list 'touchscreen-hold
                     (list (selected-window) 15 '(0 . 0)))))
            (should (equal (cons (region-beginning) (region-end))
                           '(12 . 17)))
            (should (equal (meow--selection-type) '(expand . char)))
            (when reverse
              (exchange-point-and-mark))
            (let ((anchor (mark))
                  (start (point)))
              (execute-kbd-macro (kbd key))
              (should (region-active-p))
              (should (= (mark) anchor))
              (should-not (= (point) start)))))))))

(ert-deftest suderman/android-pinch-scales-the-default-face-continuously ()
  (let ((global-text-scale-adjust-limits '(100 . 300))
        heights)
    (cl-letf (((symbol-function 'face-attribute)
               (lambda (&rest _) 200))
              ((symbol-function 'set-face-attribute)
               (lambda (_face _frame &rest attributes)
                 (push (plist-get attributes :height) heights))))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 0.1 0 0 0.1))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 1.1 0 0 0.1))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 2.0 0 0 1.0))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 0.4 0 0 -0.6))
      (should (equal (nreverse heights) '(220 300 100))))))

(ert-deftest suderman/android-volume-buttons-support-modifiers-and-chords ()
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-up)))
    (should (equal (suderman/android-volume-control nil) [escape])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-down)))
    (should (equal (suderman/android-volume-meta nil) [tab])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) ?x))
            ((symbol-function 'event-apply-modifier)
             (lambda (event modifier bit prefix)
               (list event modifier bit prefix))))
    (should (equal (suderman/android-volume-control nil)
                   [(120 control 26 "C-")]))
    (should (equal (suderman/android-volume-meta nil)
                   [(120 meta 27 "M-")]))))


;; Meow editing behavior

(ert-deftest suderman/android-meow-text-conversion-follows-state ()
  (with-temp-buffer
    (let ((system-type 'android)
          (text-conversion-style t)
          calls)
      (cl-letf (((symbol-function 'set-text-conversion-style)
                 (lambda (style &optional _after-key-sequence)
                   (setq text-conversion-style style)
                   (push style calls))))
        (suderman/android-meow-text-conversion 'normal)
        (suderman/android-meow-text-conversion 'motion)
        (suderman/android-meow-text-conversion 'insert)
        (suderman/android-meow-text-conversion 'keypad)
        (should-not text-conversion-style)
        (should (equal (nreverse calls) '(nil t nil)))))))

(ert-deftest suderman/android-meow-text-conversion-leaves-desktop-alone ()
  (let ((system-type 'gnu/linux)
        (text-conversion-style 'unchanged)
        calls)
    (cl-letf (((symbol-function 'set-text-conversion-style)
               (lambda (&rest arguments) (push arguments calls))))
      (suderman/android-meow-text-conversion 'insert)
      (should (eq text-conversion-style 'unchanged))
      (should-not calls))))

(ert-deftest suderman/meow-insert-dispatches-by-state ()
  (with-temp-buffer
    (let (calls)
      (cl-letf (((symbol-function 'meow-beacon-insert)
                 (lambda () (setq calls (append calls '(beacon)))))
                ((symbol-function 'meow-insert)
                 (lambda () (setq calls (append calls '(insert)))))
                ((symbol-function 'suderman/meow--cancel-active-selection)
                 (lambda () (setq calls (append calls '(cancel))))))
        (setq-local meow-beacon-mode t)
        (suderman/meow-insert)
        (should (equal calls '(beacon)))

        (setq calls nil)
        (setq-local meow-beacon-mode nil)
        (suderman/meow-insert)
        (should (equal calls '(cancel insert)))))))

(ert-deftest suderman/escape-dispatches-by-meow-state ()
  (let (calls resolved-keys)
    (cl-letf (((symbol-function 'meow-insert-exit)
               (lambda () (push 'insert-exit calls)))
              ((symbol-function 'key-binding)
               (lambda (key)
                 (push key resolved-keys)
                 'contextual-cancel))
              ((symbol-function 'call-interactively)
               (lambda (command) (push command calls))))
      (let ((meow-insert-mode t))
        (suderman/meow-escape))
      (let ((meow-insert-mode nil))
        (suderman/meow-escape))
      (should (equal (nreverse calls)
                     '(insert-exit contextual-cancel)))
      (should (equal resolved-keys (list (kbd "C-g")))))))

(ert-deftest suderman/meow-line-bound-overloads-insert-without-selection ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "  alpha  ; comment")
    (let (insert-points)
      (cl-letf (((symbol-function 'suderman/meow-insert)
                 (lambda () (push (point) insert-points))))
        (goto-char 5)
        (suderman/meow-insert-at-indentation)
        (suderman/meow-insert-at-indentation)
        (goto-char 5)
        (suderman/meow-insert-at-end-of-line)
        (suderman/meow-insert-at-end-of-line))
      (should (equal (nreverse insert-points) '(3 1 8 19))))))

(ert-deftest suderman/meow-keypad-runs-without-beacon-fanout ()
  (with-temp-buffer
    (let* ((overlay (make-overlay (point-min) (point-min)))
           (meow--beacon-overlays (list overlay))
           seen)
      (unwind-protect
          (cl-letf (((symbol-function 'meow-keypad)
                     (lambda () (setq seen meow--beacon-overlays))))
            (suderman/meow-keypad-once)
            (should-not seen)
            (should (equal meow--beacon-overlays (list overlay))))
        (delete-overlay overlay)))))

(ert-deftest suderman/meow-save-copies-selection-or-buffer-path ()
  (let ((transient-mark-mode t)
        selection-saved)
    (with-temp-buffer
      (insert "selected")
      (set-mark (point-min))
      (activate-mark)
      (cl-letf (((symbol-function 'meow-save)
                 (lambda () (setq selection-saved t))))
        (suderman/meow-save))
      (should selection-saved)))
  (let ((kill-ring nil)
        (kill-ring-yank-pointer nil)
        (interprogram-cut-function nil))
    (with-temp-buffer
      (setq-local buffer-file-name "/tmp/example.txt")
      (suderman/meow-save)
      (should (equal (current-kill 0) buffer-file-name))))
  (with-temp-buffer
    (should-error (suderman/meow-save) :type 'user-error)))

(ert-deftest suderman/meow-uppercase-delete-and-cut-use-active-selection ()
  (let ((transient-mark-mode t)
        (meow-use-clipboard nil)
        (interprogram-cut-function nil))
    (save-window-excursion
      (dolist (case '(("d" "D" nil) ("x" "X" "alpha")))
        (dolist (key (list (car case) (cadr case)))
          (let ((kill-ring nil)
                (kill-ring-yank-pointer nil))
            (with-temp-buffer
              (set-window-buffer (selected-window) (current-buffer))
              (insert "alpha beta\nnext\n")
              (goto-char 3)
              (setq-local meow-normal-mode t)
              (execute-kbd-macro (kbd (concat "m " key)))
              (should (equal (buffer-string) " beta\nnext\n"))
              (should (equal (car kill-ring) (caddr case))))))
        (let ((kill-ring nil)
              (kill-ring-yank-pointer nil))
          (with-temp-buffer
            (set-window-buffer (selected-window) (current-buffer))
            (insert "alpha beta\nnext\n")
            (goto-char 3)
            (setq-local meow-normal-mode t)
            (execute-kbd-macro (kbd (cadr case)))
            (should (equal (buffer-string) "next\n"))
            (should (equal (car kill-ring)
                           (and (caddr case) "alpha beta\n")))))))))

(ert-deftest suderman/meow-copy-line-keeps-point-on-selected-line ()
  (let ((transient-mark-mode t)
        (meow-use-clipboard nil)
        (interprogram-cut-function nil)
        (kill-ring nil))
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (insert "alpha\nbeta\n")
        (goto-char 3)
        (setq-local meow-normal-mode t)
        (execute-kbd-macro (kbd "M c"))
        (should (= (point) 6))
        (should (equal (current-kill 0) "alpha\n"))
        (should-not (region-active-p))
        (goto-char 8)
        (execute-kbd-macro (kbd "m c"))
        (should (= (point) 11))
        (should (equal (current-kill 0) "beta"))
        (should-not (region-active-p))))))

(ert-deftest suderman/meow-shift-m-selects-line-rectangle-buffer ()
  (let ((transient-mark-mode t)
        (command (symbol-function 'suderman/meow-line-or-rectangle))
        states)
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (insert "alpha\nbeta\n")
        (setq-local meow-normal-mode t)
        (meow--cancel-selection)
        (goto-char 3)
        (setq last-command nil)
        (cl-letf (((symbol-function 'suderman/meow-line-or-rectangle)
                   (lambda (n)
                     (interactive "p")
                     (funcall command n)
                     (push (list (meow--selection-type)
                                 suderman/meow-line-position
                                 (point)
                                 (bound-and-true-p rectangle-mark-mode)
                                 (when (region-active-p)
                                   (cons (region-beginning) (region-end))))
                           states))))
          (execute-kbd-macro (kbd "M M M")))
        (setq states (nreverse states))
        (should (equal (nth 0 states)
                       '((expand . line) 3 6 nil (1 . 6))))
        (should (equal (nth 1 states)
                       '((expand . char) 3 3 t (3 . 3))))
        (should (equal (nth 2 states)
                       `((expand . char) 3 ,(point-max) nil
                         (,(point-min) . ,(point-max)))))))))

(ert-deftest suderman/meow-line-bound-overloads-extend-word-selections ()
  (let ((transient-mark-mode t))
    (with-temp-buffer
      (emacs-lisp-mode)
      (insert "  alpha beta")
      (goto-char 5)
      (let ((last-command nil))
        (suderman/meow-visual))
      (suderman/meow-insert-at-end-of-line)
      (should (equal (cons (region-beginning) (region-end)) '(3 . 13)))

      (meow--cancel-selection)
      (goto-char 10)
      (let ((last-command nil))
        (suderman/meow-visual))
      (suderman/meow-insert-at-indentation)
      (should (equal (cons (region-beginning) (region-end)) '(3 . 13)))
      (suderman/meow-insert-at-indentation)
      (should (equal (cons (region-beginning) (region-end)) '(1 . 13))))))

(ert-deftest suderman/meow-find-motions-extend-word-selections ()
  (let ((transient-mark-mode t))
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (emacs-lisp-mode)
        (insert "alpha beta theta")
        (setq-local meow-normal-mode t)
        (goto-char 3)
        (execute-kbd-macro (kbd "m f t ;"))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 13)))

        (meow--cancel-selection)
        (erase-buffer)
        (insert "token beta gamma")
        (goto-char 14)
        (execute-kbd-macro (kbd "m F t ;"))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 17)))))))

(ert-deftest suderman/meow-word-start-skips-current-word-and-extends-selection ()
  (let ((transient-mark-mode t)
        (current-prefix-arg nil))
    (save-window-excursion
      (with-temp-buffer
        (set-window-buffer (selected-window) (current-buffer))
        (insert "alpha, beta gamma")
        (setq-local meow-normal-mode t)
        (goto-char 3)
        (execute-kbd-macro (kbd "w"))
        (should (= (point) 8))
        (should-not (region-active-p))
        (goto-char 3)
        (execute-kbd-macro (kbd "m w"))
        (should (= (point) 8))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 8)))
        (should (equal (meow--selection-type) '(expand . char)))
        (execute-kbd-macro (kbd "w"))
        (should (= (point) 13))
        (should (equal (cons (region-beginning) (region-end)) '(1 . 13)))
        (meow--cancel-selection)
        (goto-char 7)
        (execute-kbd-macro (kbd "C-u 2 w"))
        (should (= (point) 13))
        (suderman/meow-next-word-start -1)
        (should (= (point) 8))))))

(ert-deftest suderman/meow-thing-selections-stay-adjustable ()
  (let ((transient-mark-mode t))
    (dolist (case '((meow-beginning-of-thing . meow-right)
                    (meow-end-of-thing . meow-left)
                    (meow-inner-of-thing . meow-left)
                    (meow-bounds-of-thing . meow-right)))
      (with-temp-buffer
        (emacs-lisp-mode)
        (insert "alpha beta")
        (goto-char 3)
        (setq-local meow-normal-mode t)
        (funcall (car case) ?e)
        (should (equal (meow--selection-type) '(expand . char)))
        (let ((before (point)))
          (funcall (cdr case))
          (should (region-active-p))
          (should (equal (meow--selection-type) '(expand . char)))
          (should-not (= (point) before)))))))

(provide 'suderman-input-test)
;;; suderman-input-test.el ends here
