;;; suderman-android-test.el --- Focused Android checks -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'pixel-scroll)
(require 'suderman-android)
(require 'touch-screen)

(defvar global-text-scale-adjust-limits)

(ert-deftest suderman/custom-toolbar-has-the-requested-actions-and-order ()
  (let ((original-tool-bar-map (default-value 'tool-bar-map))
        (tool-bar-map (make-sparse-keymap))
        (input-decode-map (make-sparse-keymap))
        (tool-bar-button-margin 4)
        (tool-bar-style nil)
        (tool-bar-always-show-default nil)
        images
        face-changes
        customizations
        tool-bar-calls)
    (define-key tool-bar-map [stock-save]
      '(menu-item "Save" save-buffer))
    (cl-letf (((symbol-function 'modifier-bar-mode) #'ignore)
              ((symbol-function 'customize-set-variable)
               (lambda (symbol value)
                 (push (list symbol value) customizations)))
              ((symbol-function 'suderman/android-tool-bar-image)
               (lambda (name)
                  (let ((image `(test-image ,name)))
                    (push image images)
                    image)))
              ((symbol-function 'suderman/android-tool-bar-state-images)
               (lambda (name)
                 `(test-image ,name)))
              ((symbol-function 'face-foreground)
               (lambda (&rest _) "ink"))
              ((symbol-function 'face-background)
               (lambda (&rest _) "paper"))
              ((symbol-function 'set-face-attribute)
               (lambda (&rest arguments)
                 (push arguments face-changes)))
              ((symbol-function 'tool-bar--flush-cache) #'ignore)
              ((symbol-function 'tool-bar-mode)
               (lambda (&optional argument)
                 (push argument tool-bar-calls)))
              ((symbol-function 'force-mode-line-update) #'ignore))
      (unwind-protect
          (progn
            (suderman/android-setup-tool-bar)
            (suderman/android-setup-tool-bar 'test-theme)
            (setq tool-bar-map (default-value 'tool-bar-map))
            (should (equal tool-bar-calls '(1)))
            (should (member '(tool-bar-position bottom) customizations))
            (should (member '(tool-bar nil :foreground "ink"
                                       :background "paper")
                            face-changes))
            (should (= tool-bar-button-margin 4))
            (should (eq tool-bar-style 'image))
            (should tool-bar-always-show-default)
            (should (equal (mapcar #'car (cdr tool-bar-map))
                           '(control meta suderman-buffers suderman-keyboard
                             suderman-files suderman-tab suderman-escape)))
            (should (equal (mapcar (lambda (binding) (nth 2 binding))
                                   (cdr tool-bar-map))
                           '("CTRL" "META" "BUFFERS" "KEYBOARD" "FILES"
                             "TAB" "ESC")))
            (let* ((bindings (cdr tool-bar-map))
                   (control (assq 'control bindings))
                   (meta (assq 'meta bindings)))
              (should
               (equal
                 (mapcar (lambda (binding)
                           (plist-get (nthcdr 4 binding) :image))
                         bindings)
                (list '(test-image "control") '(test-image "meta")
                      '(test-image "buffers") '(test-image "keyboard")
                      '(test-image "files") '(test-image "tab")
                      '(test-image "escape"))))
              (should
               (equal (cdr (plist-get (nthcdr 4 control) :button))
                      '(memq 'control modifier-bar-modifier-list)))
              (should
               (equal (cdr (plist-get (nthcdr 4 meta) :button))
                      '(memq 'meta modifier-bar-modifier-list)))
              (let ((modifier-bar-modifier-list '(control meta)))
                (should (eval (cdr (plist-get (nthcdr 4 control) :button))))
                (should (eval (cdr (plist-get (nthcdr 4 meta) :button))))))
            (should (eq (lookup-key tool-bar-map [suderman-escape])
                        'suderman/meow-escape))
            (should (eq (lookup-key tool-bar-map [suderman-files])
                        'suderman/dirvish))
            (should (eq (lookup-key tool-bar-map [suderman-buffers])
                        'suderman/ibuffer-toggle))
            (should (eq (lookup-key tool-bar-map [suderman-keyboard])
                        'suderman/android-toggle-keyboard))
            (should-not
             (lookup-key input-decode-map [tool-bar suderman-escape]))
            (should (equal
                     (lookup-key input-decode-map [tool-bar suderman-tab])
                     [tab]))
            (should (eq
                     (lookup-key input-decode-map [tool-bar control])
                     'suderman/android-toggle-control-modifier))
            (should (eq
                     (lookup-key input-decode-map [tool-bar meta])
                     'suderman/android-toggle-meta-modifier))
            (let ((system-type 'android))
              (suderman/android-setup-tool-bar 'test-theme)
              (should (equal tool-bar-button-margin '(48 . 20)))))
        (set-default 'tool-bar-map original-tool-bar-map)))))

(ert-deftest suderman/custom-toolbar-is-enabled-and-theme-aware ()
  (should tool-bar-mode)
  (should (memq #'suderman/android-setup-tool-bar enable-theme-functions)))

(ert-deftest suderman/android-toolbar-images-are-native-sized ()
  (dolist (name '("escape" "tab" "files" "buffers" "keyboard"
                  "control" "control-active" "meta" "meta-active"))
    (let ((file (expand-file-name
                 (format "assets/android-toolbar/%s.pbm" name)
                 user-emacs-directory)))
      (should (file-readable-p file))
      (with-temp-buffer
        (insert-file-contents-literally file)
        (should (looking-at-p
                 "P1[[:space:]]+56[[:space:]]+56[[:space:]]"))))))

(ert-deftest suderman/custom-toolbar-desktop-images-are-final-size-vectors ()
  (let ((foreground "#abcdef")
        (background "#123456"))
    (dolist (name '("escape" "tab" "files" "buffers" "keyboard"
                    "control" "meta"))
      (let ((svg (suderman/tool-bar-desktop-svg-data
                  name foreground background)))
        (should (string-prefix-p "<svg " svg))
        (should (string-match-p "height=\"22\"" svg))
        (should (string-match-p "fill=\"#abcdef\"" svg))
        (should-not (string-match-p "<rect " svg))))
    (dolist (name '("control-active" "meta-active"))
      (let ((svg (suderman/tool-bar-desktop-svg-data
                  name foreground background)))
        (should (string-match-p "<rect .*fill=\"#abcdef\"" svg))
        (should (string-match-p "<text .*fill=\"#123456\"" svg))))
    (let ((control (suderman/tool-bar-desktop-svg-data
                    "control" foreground background))
          (meta (suderman/tool-bar-desktop-svg-data
                 "meta" foreground background)))
      (should (string-match-p ">Ctrl</text>" control))
      (should (string-match-p ">Meta</text>" meta))
      (should (string-match-p "width=\"28\"" control))
      (should (string-match-p "width=\"28\"" meta))
      (should (string-match-p "font-size=\"11\"" control))
      (should (string-match-p "font-size=\"11\"" meta)))))

(ert-deftest suderman/custom-toolbar-images-use-platform-source ()
  (let ((user-emacs-directory "/tmp/emacs-config/"))
    (cl-letf (((symbol-function 'suderman/tool-bar-desktop-svg-data)
               (lambda (&rest _) "<svg/>"))
              ((symbol-function 'face-foreground) (lambda (&rest _) "black"))
              ((symbol-function 'face-background) (lambda (&rest _) "white")))
      (let* ((system-type 'gnu/linux)
             (image (suderman/android-tool-bar-image "escape")))
        (should (equal (nth 1 image) "<svg/>"))
        (should (equal (nth 2 image) ''svg))
        (should (nth 3 image))
        (should (= (plist-get (nthcdr 4 image) :scale) 1)))
      (let* ((system-type 'android)
             (image (suderman/android-tool-bar-image "escape")))
        (should (equal (nth 1 image)
                       "/tmp/emacs-config/assets/android-toolbar/escape.pbm"))
        (should (equal (nth 2 image) ''pbm))
        (should-not (nth 3 image)))
      (let ((system-type 'android))
        (should (equal
                 (plist-get
                  (nthcdr 4
                          (suderman/android-tool-bar-image "control-active"))
                  :mask)
                 ''nil))))))

(ert-deftest suderman/custom-toolbar-state-images-match-platform-support ()
  (cl-letf (((symbol-function 'suderman/android-tool-bar-image)
              (lambda (name) `(test-create-image ,name)))
             ((symbol-function 'test-create-image)
              (lambda (name) `(image :type pbm :file ,name))))
    (let ((system-type 'gnu/linux))
      (let ((image (suderman/android-tool-bar-state-images "control")))
        (let ((modifier-bar-modifier-list nil))
          (should (equal (eval image)
                         '(image :type pbm :file "control"))))
        (let ((modifier-bar-modifier-list '(control)))
          (should (equal (eval image)
                         '(image :type pbm :file "control-active"))))))
    (let ((system-type 'android))
      (should
       (equal (suderman/android-tool-bar-state-images "control")
              [(image :type pbm :file "control-active")
               (image :type pbm :file "control")
               (image :type pbm :file "control-active")
               (image :type pbm :file "control")])))))

(ert-deftest suderman/android-modifier-buttons-toggle-off ()
  (dolist (case '((suderman/android-toggle-control-modifier control)
                  (suderman/android-toggle-meta-modifier meta)))
    (let* ((function (car case))
           (modifier (cadr case))
           (events (list 'tool-bar modifier))
           redraw-states)
      (cl-letf (((symbol-function 'read-event)
                 (lambda (&rest _) (pop events)))
                ((symbol-function 'event-basic-type) #'identity)
                ((symbol-function 'frame-toggle-on-screen-keyboard) #'ignore)
                ((symbol-function 'suderman/tool-bar-refresh)
                 (lambda (&rest _)
                   (push (copy-sequence modifier-bar-modifier-list)
                         redraw-states)))
                ((symbol-function 'redisplay) #'ignore)
                ((symbol-function 'set-text-conversion-style) #'ignore))
        (should (equal (funcall function nil) []))
        (should-not events)
        (should (equal (nreverse redraw-states)
                       (list (list modifier) nil nil)))))))

(ert-deftest suderman/android-modifier-buttons-toggle-independently ()
  (dolist (case '((suderman/android-toggle-control-modifier
                   control meta)
                  (suderman/android-toggle-meta-modifier
                   meta control)))
    (let* ((function (car case))
           (initial (cadr case))
           (remaining (caddr case))
           (events (list 'tool-bar remaining 'tool-bar initial ?x))
           applied)
      (cl-letf (((symbol-function 'read-event)
                 (lambda (&rest _) (pop events)))
                ((symbol-function 'event-basic-type) #'identity)
                ((symbol-function 'frame-toggle-on-screen-keyboard) #'ignore)
                ((symbol-function 'suderman/tool-bar-refresh) #'ignore)
                ((symbol-function 'redisplay) #'ignore)
                ((symbol-function 'set-text-conversion-style) #'ignore)
                ((symbol-function 'tool-bar-apply-modifiers)
                 (lambda (event modifiers)
                   (setq applied (list event modifiers))
                   'translated)))
        (should (equal (funcall function nil) [translated]))
        (should-not events)
        (should (equal applied (list ?x (list remaining))))))))

(ert-deftest suderman/android-toolbar-toggles-the-software-keyboard ()
  (let ((frame 'phone-frame)
        (width 600)
        (height 1000)
        full-size
        calls)
    (cl-letf (((symbol-function 'selected-frame) (lambda () frame))
              ((symbol-function 'frame-pixel-width) (lambda (_) width))
              ((symbol-function 'frame-pixel-height) (lambda (_) height))
              ((symbol-function 'frame-parameter)
               (lambda (_ parameter)
                 (should (eq parameter
                             'suderman/android-keyboard-full-size))
                 full-size))
              ((symbol-function 'set-frame-parameter)
               (lambda (_ parameter value)
                 (should (eq parameter
                             'suderman/android-keyboard-full-size))
                 (setq full-size value)))
              ((symbol-function 'frame-toggle-on-screen-keyboard)
               (lambda (&rest arguments) (push arguments calls))))
      (suderman/android-toggle-keyboard)
      (setq height 600)
      (suderman/android-toggle-keyboard)
      (setq height 1000)
      (suderman/android-toggle-keyboard)
      ;; An external dismissal also restores the full frame height.
      (setq height 600)
      (setq height 1000)
      (suderman/android-toggle-keyboard)
      (should (equal (nreverse calls)
                     '((phone-frame nil) (phone-frame t)
                       (phone-frame nil) (phone-frame nil))))
      (should (equal full-size '(600 . 1000))))))

(ert-deftest suderman/android-touch-scroll-enables-momentum-idempotently ()
  (let ((touch-screen-precision-scroll nil)
        (pixel-scroll-precision-use-momentum nil)
        calls
        defaults)
    (cl-letf (((symbol-function 'advice-remove)
               (lambda (symbol function)
                 (push (list 'remove symbol function) calls)))
              ((symbol-function 'advice-add)
               (lambda (symbol where function &rest _)
                 (push (list 'add symbol where function) calls)))
              ((symbol-function 'set-default)
               (lambda (symbol value)
                 (push (list symbol value) defaults))))
      (suderman/android-setup-touch-scrolling)
      (should touch-screen-precision-scroll)
      (should pixel-scroll-precision-use-momentum)
      (should (equal defaults
                     '((make-cursor-line-fully-visible nil))))
      (should
       (equal
        (nreverse calls)
        '((remove touch-screen-handle-scroll
                  suderman/android-record-touch-scroll)
          (add touch-screen-handle-scroll :before
               suderman/android-record-touch-scroll)
          (remove touch-screen-handle-touch
                  suderman/android-start-touch-momentum)
          (add touch-screen-handle-touch :before
               suderman/android-start-touch-momentum)))))))

(ert-deftest suderman/android-touch-scroll-records-finger-velocity ()
  (let (velocity)
    (cl-letf (((symbol-function 'pixel-scroll-accumulate-velocity)
               (lambda (delta) (setq velocity delta))))
      (suderman/android-record-touch-scroll 4 17)
      (should (= velocity -17)))))

(ert-deftest suderman/android-touch-scroll-flings-only-after-scrolling ()
  (let ((touch-screen-current-tool '(1 nil nil scroll))
        events)
    (cl-letf (((symbol-function 'pixel-scroll-start-momentum)
               (lambda (event) (push event events))))
      (suderman/android-start-touch-momentum
       '(touchscreen-update ((1 . position))))
      (let ((touch-screen-current-tool '(1 nil nil held)))
        (suderman/android-start-touch-momentum
         '(touchscreen-end (1 . position) nil)))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (2 . position) nil))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (1 . position) t))
      (suderman/android-start-touch-momentum
       '(touchscreen-end (1 . position) nil))
      (should (equal events
                     '((touchscreen-end (1 . position) nil)))))))

(ert-deftest suderman/android-pinch-scales-the-default-face-continuously ()
  (let ((global-text-scale-adjust-limits '(100 . 300))
        heights)
    (cl-letf (((symbol-function 'face-attribute)
               (lambda (&rest _) 200))
              ((symbol-function 'set-face-attribute)
               (lambda (_face _frame &rest attributes)
                 (push (plist-get attributes :height) heights))))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 0.1 0 0 0.1))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 1.1 0 0 0.1))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 2.0 0 0 1.0))
      (suderman/android-global-pinch
       '(touchscreen-pinch position 0.4 0 0 -0.6))
      (should (equal (nreverse heights) '(220 300 100))))))

(ert-deftest suderman/android-volume-buttons-support-modifiers-and-chords ()
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-up)))
    (should (equal (suderman/android-volume-control nil) [escape])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-down)))
    (should (equal (suderman/android-volume-meta nil) [tab])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) ?x))
            ((symbol-function 'event-apply-modifier)
             (lambda (event modifier bit prefix)
               (list event modifier bit prefix))))
    (should (equal (suderman/android-volume-control nil)
                   [(120 control 26 "C-")]))
    (should (equal (suderman/android-volume-meta nil)
                   [(120 meta 27 "M-")]))))

(provide 'suderman-android-test)
;;; suderman-android-test.el ends here
