;;; suderman-appearance-test.el --- Focused appearance checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-appearance-test.el -f ert-run-tests-batch-and-exit

(require 'cl-lib)
(require 'ert)
(require 'suderman-appearance)

(ert-deftest suderman/android-uses-a-larger-default-font ()
  (let ((system-type 'android)
        (custom-enabled-themes nil)
        attributes)
    (should (equal (suderman/default-font-size) 17.0))
    (cl-letf (((symbol-function 'suderman/nerd-fonts-available-p)
               (lambda (&optional _) nil))
              ((symbol-function 'set-face-attribute)
               (lambda (face frame &rest values)
                 (setq attributes (append (list face frame) values)))))
      (suderman/apply-default-font)
      (should (equal attributes '(default nil :height 170)))))
  (let ((system-type 'gnu/linux))
    (should (equal (suderman/default-font-size) 11))))

(ert-deftest suderman/android-nerd-font-size-is-in-points ()
  (let ((system-type 'android)
        (custom-enabled-themes nil)
        font-size)
    (cl-letf (((symbol-function 'suderman/nerd-fonts-available-p)
               (lambda (&optional _) t))
              ((symbol-function 'font-spec)
               (lambda (&rest properties)
                 (setq font-size (plist-get properties :size))
                 'font))
                ((symbol-function 'find-font) (lambda (&rest _) t))
                ((symbol-function 'set-face-attribute) #'ignore))
      (suderman/apply-default-font)
      ;; `font-spec' treats integers as pixels and floats as points.
      (should (equal font-size 17.0)))))

(ert-deftest suderman/android-icons-need-symbols-not-a-patched-text-font ()
  (let ((system-type 'android))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t))
              ((symbol-function 'find-font)
               (lambda (spec &optional _frame)
                 (equal (format "%s" (font-get spec :family)) suderman/font-family))))
      (should-not (suderman/nerd-fonts-available-p)))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t))
              ((symbol-function 'find-font)
               (lambda (spec &optional _frame)
                 (equal (format "%s" (font-get spec :family)) suderman/nerd-symbol-font))))
      (should (suderman/nerd-fonts-available-p)))))

(ert-deftest suderman/mode-line-navigation-segments-follow-platform ()
  (let ((system-type 'android))
    (should (equal (suderman/mode-line-navigation-segments)
                   '(suderman-dashboard))))
  (let ((system-type 'gnu/linux))
    (should (equal (suderman/mode-line-navigation-segments)
                   '(suderman-dashboard suderman-dirvish suderman-ibuffer)))))

(ert-deftest suderman/base16-gnus-faces-avoid-emacs-31-inheritance-cycles ()
  (let (faces transformed)
    (dolist (group '(mail news))
      (dotimes (index 6)
        (let* ((level (1+ index))
               (face (intern (format "gnus-group-%s-%d" group level)))
               (empty-face (intern (format "%s-empty" face)))
               (outline (intern (format "outline-%d" level))))
          (push `(,face :inherit ,outline) faces)
          (push `(,empty-face :foreground base04 :inherit ,face) faces))))
    (push '(default :foreground base05) faces)
    (let ((original (copy-tree faces)))
      (suderman/base16-theme-set-faces-without-gnus-cycles
       (lambda (_theme _colors fixed-faces)
         (setq transformed fixed-faces))
       'base16-test nil faces)
      (should (equal faces original)))
    (dolist (face transformed)
      (when (string-match
             "\\`\\(gnus-group-\\(?:mail\\|news\\)-[1-6]\\)-empty\\'"
             (symbol-name (car face)))
        (let* ((base-face (intern (match-string 1 (symbol-name (car face)))))
               (base-inherit (plist-get (cdr (assq base-face transformed)) :inherit)))
          (should (eq (plist-get (cdr face) :inherit) base-inherit)))))
    (should (equal (assq 'default transformed)
                   '(default :foreground base05)))))

(ert-deftest suderman/selection-faces-wait-for-a-graphical-frame ()
  (let ((frames nil)
        (original-region (face-background 'region nil t)))
    (cl-letf (((symbol-function 'filtered-frame-list)
               (lambda (_predicate) frames))
              ((symbol-function 'suderman/theme-blend)
               (lambda (face _alpha)
                 (if (eq face 'font-lock-function-name-face)
                     "#112233"
                   "#445566"))))
      (suderman/apply-selection-faces)
      (should (equal (face-background 'region nil t) original-region))

      (setq frames (list (selected-frame)))
      (suderman/apply-selection-faces)
      (should (equal (face-background 'region nil t) "#112233"))
      (should (equal (face-background 'secondary-selection nil t) "#445566")))))

(ert-deftest suderman/tty-menu-faces-follow-semantic-theme-faces ()
  (let ((frame (selected-frame))
        calls)
    (cl-letf (((symbol-function 'frame-list) (lambda () (list frame)))
              ((symbol-function 'display-graphic-p) (lambda (_) nil))
              ((symbol-function 'face-foreground)
               (lambda (face &rest _)
                 (pcase face
                   ('default "foreground")
                   ('shadow "disabled"))))
              ((symbol-function 'face-background)
               (lambda (face &rest _)
                 (pcase face
                   ('highlight "background")
                   ('region "selected"))))
              ((symbol-function 'set-face-attribute)
               (lambda (face target &rest attributes)
                 (push (append (list face target) attributes) calls))))
      (suderman/apply-tty-menu-faces)
      (should (member `(menu ,frame
                            :foreground "foreground"
                            :background "background"
                            :inverse-video nil)
                      calls))
      (should (member `(tty-menu-enabled-face ,frame
                                             :foreground "foreground"
                                             :background "background")
                      calls))
      (should (member `(tty-menu-disabled-face ,frame
                                              :foreground "disabled"
                                              :background "background")
                      calls))
      (should (member `(tty-menu-selected-face ,frame
                                              :foreground "foreground"
                                              :background "selected"
                                              :inverse-video nil)
                      calls)))))

(ert-deftest suderman/line-number-toggle-preserves-special-buffer-exclusions ()
  (let ((original-state global-display-line-numbers-mode)
        (text-buffer (generate-new-buffer " *suderman-line-numbers-text*"))
        (special-buffer (generate-new-buffer " *suderman-line-numbers-special*"))
        (image-buffer (generate-new-buffer " *suderman-line-numbers-image*")))
    (unwind-protect
        (progn
          (with-current-buffer text-buffer
            (text-mode))
          (with-current-buffer special-buffer
            (special-mode))
          (with-current-buffer image-buffer
            (setq major-mode 'image-mode))
          (unless global-display-line-numbers-mode
            (global-display-line-numbers-mode 1)
            (suderman/disable-line-numbers-in-special-buffers))

          (suderman/toggle-line-numbers)
          (should-not global-display-line-numbers-mode)
          (should-not (buffer-local-value 'display-line-numbers-mode text-buffer))
          (should-not (buffer-local-value 'display-line-numbers-mode special-buffer))
          (should-not (buffer-local-value 'display-line-numbers-mode image-buffer))

          (suderman/toggle-line-numbers)
          (should global-display-line-numbers-mode)
          (should (buffer-local-value 'display-line-numbers-mode text-buffer))
          (should-not (buffer-local-value 'display-line-numbers-mode special-buffer))
          (should-not (buffer-local-value 'display-line-numbers-mode image-buffer)))
      (global-display-line-numbers-mode (if original-state 1 -1))
      (when original-state
        (suderman/disable-line-numbers-in-special-buffers))
      (kill-buffer text-buffer)
      (kill-buffer special-buffer)
      (kill-buffer image-buffer))))

(ert-deftest suderman/android-column-guide-defaults-off ()
  (dolist (case '((gnu/linux 1) (android -1)))
    (let ((system-type (car case))
          received)
      (cl-letf (((symbol-function 'global-display-fill-column-indicator-mode)
                 (lambda (argument) (setq received argument))))
        (suderman/initialize-fill-column-indicator)
        (should (= received (cadr case)))))))

(ert-deftest suderman/android-line-modes-default-off ()
  (dolist (case '((gnu/linux 1) (android -1)))
    (let ((system-type (car case))
          calls)
      (cl-letf (((symbol-function 'global-hl-line-mode)
                 (lambda (argument) (push (list 'hl-line argument) calls)))
                ((symbol-function 'global-display-line-numbers-mode)
                 (lambda (argument)
                   (push (list 'line-numbers argument) calls))))
        (suderman/initialize-line-modes)
        (should (equal (nreverse calls)
                       `((hl-line ,(cadr case))
                         (line-numbers ,(cadr case)))))))))

(ert-deftest suderman/dirvish-preview-keeps-line-numbers-disabled ()
  (with-temp-buffer
    (display-line-numbers-mode 1)
    (suderman/dirvish-preview-disable-line-numbers)
    (should-not display-line-numbers-mode)
    (display-line-numbers-mode 1)
    (should-not display-line-numbers-mode)))

(ert-deftest suderman/shared-style-is-optional-and-reloadable ()
  (let ((directory (make-temp-file "emacs-style-" t))
        (suderman/system-style '(:mono-font "old")))
    (unwind-protect
        (let ((file (expand-file-name "style.el" directory)))
          (suderman/load-system-style file)
          (should-not suderman/system-style)
          (with-temp-file file
            (insert ";;; -*- lexical-binding: t; -*-\n"
                    "(setq suderman/system-style '(:mono-font \"Example\" :font-size 12.0))"))
          (suderman/load-system-style file)
          (should (equal (plist-get suderman/system-style :mono-font) "Example")))
      (delete-directory directory t))))

(ert-deftest suderman/system-palettes-switch-without-stacking-themes ()
  (let* ((colors (cl-loop for index below 16
                          append (list (intern (format ":base%02X" index))
                                       "#777777")))
         (light (plist-put (copy-sequence colors) :base00 "#ffffff"))
         (dark (plist-put (copy-sequence colors) :base00 "#111111"))
         (suderman/system-style (list :palettes (list :light light :dark dark)))
         (original-themes custom-enabled-themes)
         (toolkit-theme 'light)
         setting-count)
    (unwind-protect
        (cl-letf (((symbol-function 'suderman/load-system-style) #'ignore))
          ;; Startup reads the current toolkit value, not a separate preference.
          (suderman/apply-system-palette)
          (should (equal custom-enabled-themes '(suderman-light)))
          (setq setting-count (length (get 'suderman-light 'theme-settings)))
          ;; Face corrections must replace Base16 entries, not create duplicates.
          (should (= setting-count
                     (length (delete-dups
                              (mapcar #'cadr (get 'suderman-light 'theme-settings))))))
          (dolist (appearance '(dark light light dark light))
            (run-hook-with-args 'toolkit-theme-set-functions appearance)
            (let* ((theme (if (eq appearance 'light) 'suderman-light 'suderman-dark))
                   (setting (cl-find 'default (get theme 'theme-settings) :key #'cadr)))
              (should (equal custom-enabled-themes (list theme)))
              (should (= setting-count (length (get theme 'theme-settings))))
              ;; Inspect the graphic spec even when this test runs in batch.
              (should (equal (plist-get (cadar (nth 3 setting)) :background)
                             (if (eq appearance 'light) "#ffffff" "#111111")))))
          ;; Re-read palette data even when the appearance has not changed.
          (setf (plist-get light :base00) "#eeeeee")
          (suderman/apply-system-palette 'light)
          (let ((setting (cl-find 'default (get 'suderman-light 'theme-settings)
                                  :key #'cadr)))
            (should (equal (plist-get (cadar (nth 3 setting)) :background)
                           "#eeeeee"))))
      (mapc #'disable-theme custom-enabled-themes)
      (mapc #'enable-theme (reverse original-themes)))))

(ert-deftest suderman/missing-system-palettes-preserve-current-theme ()
  (let ((suderman/system-style nil)
        (original-themes custom-enabled-themes))
    (cl-letf (((symbol-function 'suderman/load-system-style) #'ignore))
      (dolist (appearance '(light dark nil))
        (suderman/apply-system-palette appearance)
        (should (equal custom-enabled-themes original-themes))))))

(ert-deftest suderman/shared-fonts-are-gui-only-and-keep-point-sizes ()
  (let ((suderman/system-style '(:mono-font "Mono" :fallback-font "Fallback"
                                :variable-font "Prose" :font-size 12.0))
        (system-type 'gnu/linux)
        calls fontsets)
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t))
              ((symbol-function 'find-font) (lambda (&rest _) t))
              ((symbol-function 'set-face-attribute)
               (lambda (face frame &rest attributes)
                 (push (list face frame attributes) calls)))
              ((symbol-function 'suderman/set-nerd-font-fallbacks) #'ignore)
              ((symbol-function 'set-fontset-font)
               (lambda (&rest args) (push args fontsets))))
      (suderman/apply-system-fonts)
      (should-not fontsets)
      (should (equal (font-get (plist-get (caddr (assq 'default calls)) :font) :size)
                     12.0))
      (should (equal (plist-get (caddr (assq 'fixed-pitch calls)) :family) "Mono"))
      (should (equal (plist-get (caddr (assq 'variable-pitch calls)) :family) "Prose"))
      (setq calls nil)
      (let ((system-type 'android))
        (suderman/apply-system-fonts)
        (should (= (font-get (plist-get (caddr (assq 'default calls)) :font) :size)
                   17.0))
        (should (equal (nreverse fontsets)
                       (list (list t nil (font-spec :family "Mono") nil 'append)
                             (list t nil (font-spec :family "Fallback") nil 'append)))))
      (setq calls nil fontsets nil)
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) nil)))
        (suderman/apply-system-fonts)
        (should-not calls)
        (should-not fontsets))
      (let ((system-type 'android))
        (cl-letf (((symbol-function 'find-font) (lambda (&rest _) nil)))
          (suderman/apply-system-fonts)
          (should-not calls)
          (should-not fontsets))))))

(ert-deftest suderman/nerd-fontsets-touch-only-supported-pua ()
  (let (ranges)
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t))
              ((symbol-function 'find-font) (lambda (&rest _) t))
              ((symbol-function 'set-fontset-font)
               (lambda (_fontset range &rest _) (push range ranges))))
      (suderman/set-nerd-font-fallbacks)
      (should (equal (nreverse ranges) '((#xe000 . #xf8ff) (#xf0001 . #xf1af0)))))))

(provide 'suderman-appearance-test)
;;; suderman-appearance-test.el ends here
