;;; suderman-files-test.el --- Focused Dirvish checks -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'suderman-files)

(ert-deftest suderman/dirvish-extensions-and-mouse-bindings-are-available ()
  (should dirvish-side-follow-mode)
  (should dirvish-peek-mode)
  (dolist (attribute '(vc-state subtree-state nerd-icons collapse file-modes))
    (should (memq attribute dirvish-attributes)))
  (dolist (binding '(("TAB" . dirvish-subtree-toggle)
                     (";" . dirvish-dispatch)
                     ("E" . dirvish-emerge-menu)
                     ("N" . dirvish-narrow)
                     ("R" . dirvish-rsync)
                     ("S" . suderman/dirvish-side-toggle)
                     ("<mouse-1>" . mouse-set-point)
                     ("<double-mouse-1>" . dired-mouse-find-file)
                     ("<mouse-3>" . context-menu-open)))
    (should (eq (lookup-key dirvish-mode-map (kbd (car binding)))
                (cdr binding))))
  (should (eq (lookup-key dirvish-directory-view-mode-map
                          (kbd "<mouse-1>"))
              #'suderman/dirvish-parent-mouse-select))
  (dolist (map (list dirvish-directory-view-mode-map dirvish-misc-mode-map))
    (dolist (key '("M-h" "M-j" "M-k" "M-l"))
      (should (eq (lookup-key map (kbd key))
                  #'suderman/dirvish-focus-root)))))

(ert-deftest suderman/dirvish-sidebar-open-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           opened)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p) #'ignore)
                ((symbol-function 'dirvish-side)
                 (lambda (path)
                   (setq opened path)
                   (select-window sidebar))))
        (suderman/dirvish-side-toggle "/tmp/")
        (should (equal opened "/tmp/"))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-sidebar-hide-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           quit-window)
      (select-window editor)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p)
                 (lambda () sidebar))
                ((symbol-function 'dirvish-quit)
                 (lambda () (setq quit-window (selected-window)))))
        (suderman/dirvish-side-toggle)
        (should (eq quit-window sidebar))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-breadcrumb-navigation-uses-root-window ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (misc (split-window-right))
           (misc-buffer (generate-new-buffer " *dirvish-misc-test*"))
           called-window)
      (unwind-protect
          (progn
            (set-window-buffer misc misc-buffer)
            (select-window misc)
            (with-current-buffer misc-buffer
              (dirvish-misc-mode)
              (cl-letf (((symbol-function 'dirvish-curr) (lambda () 'session))
                        ((symbol-function 'dv-root-window) (lambda (_) root)))
                (suderman/dirvish-find-entry-at-root
                 (lambda (_find _entry)
                   (setq called-window (selected-window)))
                 #'find-file "/tmp/")))
            (should (eq called-window root))
            (should (eq (selected-window) root)))
        (kill-buffer misc-buffer)))))

(ert-deftest suderman/dirvish-parent-file-click-centers-and-selects-file ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (parent (split-window-right))
           (file "/tmp/example.txt")
           navigation selected)
      (select-window parent)
      (cl-letf (((symbol-function 'event-start) (lambda (_) 'position))
                ((symbol-function 'posn-window) (lambda (_) parent))
                ((symbol-function 'posn-point) (lambda (_) 1))
                ((symbol-function 'dired-get-filename) (lambda (&rest _) file))
                ((symbol-function 'dirvish-curr) (lambda () 'session))
                ((symbol-function 'dv-root-window) (lambda (_) root))
                ((symbol-function 'file-directory-p) #'ignore)
                ((symbol-function 'dirvish--find-entry)
                 (lambda (find entry) (setq navigation (list find entry))))
                ((symbol-function 'dired-goto-file)
                 (lambda (entry) (setq selected entry))))
        (suderman/dirvish-parent-mouse-select 'event))
      (should (equal navigation '(find-alternate-file "/tmp/")))
      (should (equal selected file))
      (should (eq (selected-window) root)))))

(ert-deftest suderman/dirvish-gif-preview-loops-only-while-displayed ()
  (with-temp-buffer
    (insert (propertize " " 'display 'image-spec))
    (let ((recipe (cons 'buffer (current-buffer)))
          callback callback-arg animate-args)
      (cl-letf (((symbol-function 'dirvish--find-file-temporarily)
                 (lambda (_) recipe))
                ((symbol-function 'run-with-idle-timer)
                 (lambda (_seconds _repeat function argument)
                   (setq callback function callback-arg argument)))
                ((symbol-function 'image-animate)
                 (lambda (&rest args) (setq animate-args args))))
        (should (eq (dirvish-gif-dp "example.gif" "gif" nil nil) recipe))
        (funcall callback callback-arg)
        (should (equal animate-args '(image-spec nil t 1)))))))

(provide 'suderman-files-test)
;;; suderman-files-test.el ends here
