;;; suderman-meow-test.el --- Focused Meow checks -*- lexical-binding: t; -*-

;; Run with:
;; emacs --batch -l init.el -l test/suderman-meow-test.el -f ert-run-tests-batch-and-exit

(require 'cl-lib)
(require 'ert)
(require 'suderman-meow)

(defvar dirvish-mode-map)

(ert-deftest suderman/meow-insert-dispatches-by-state ()
  (with-temp-buffer
    (let (calls)
      (cl-letf (((symbol-function 'meow-beacon-insert)
                 (lambda () (setq calls (append calls '(beacon)))))
                ((symbol-function 'meow-insert)
                 (lambda () (setq calls (append calls '(insert)))))
                ((symbol-function 'suderman/meow--cancel-active-selection)
                 (lambda () (setq calls (append calls '(cancel))))))
        (setq-local meow-beacon-mode t)
        (suderman/meow-insert)
        (should (equal calls '(beacon)))

        (setq calls nil)
        (setq-local meow-beacon-mode nil)
        (suderman/meow-insert)
        (should (equal calls '(cancel insert)))))))

(ert-deftest suderman/meow-keypad-runs-without-beacon-fanout ()
  (with-temp-buffer
    (let* ((overlay (make-overlay (point-min) (point-min)))
           (meow--beacon-overlays (list overlay))
           seen)
      (unwind-protect
          (cl-letf (((symbol-function 'meow-keypad)
                     (lambda () (setq seen meow--beacon-overlays))))
            (suderman/meow-keypad-once)
            (should-not seen)
            (should (equal meow--beacon-overlays (list overlay))))
        (delete-overlay overlay)))))

(ert-deftest suderman/meow-beacon-space-uses-one-shot-keypad ()
  (should (eq (lookup-key meow-beacon-state-keymap (kbd "SPC"))
              #'suderman/meow-keypad-once)))

(ert-deftest suderman/meow-save-copies-selection-or-buffer-path ()
  (let ((transient-mark-mode t)
        selection-saved)
    (with-temp-buffer
      (insert "selected")
      (set-mark (point-min))
      (activate-mark)
      (cl-letf (((symbol-function 'meow-save)
                 (lambda () (setq selection-saved t))))
        (suderman/meow-save))
      (should selection-saved)))
  (let ((kill-ring nil)
        (kill-ring-yank-pointer nil)
        (interprogram-cut-function nil))
    (with-temp-buffer
      (setq-local buffer-file-name "/tmp/example.txt")
      (suderman/meow-save)
      (should (equal (current-kill 0) buffer-file-name))))
  (with-temp-buffer
    (should-error (suderman/meow-save) :type 'user-error)))

(ert-deftest suderman/meow-parentheses-extend-selection ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "("))
              #'meow-left-expand))
  (should (eq (lookup-key meow-normal-state-keymap (kbd ")"))
              #'meow-right-expand))
  (should-not (lookup-key meow-normal-state-keymap (kbd "<")))
  (should-not (lookup-key meow-normal-state-keymap (kbd ">"))))

(ert-deftest suderman/meow-cheatsheet-labels-surround-prefix ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "s"))
              surround-keymap))
  (dolist (binding '(("s s" . surround-insert)
                     ("s k" . surround-kill)
                     ("s K" . surround-kill-outer)
                     ("s i" . surround-mark)
                     ("s o" . surround-mark-outer)
                     ("s d" . surround-delete)
                     ("s c" . surround-change)))
    (should (eq (lookup-key meow-normal-state-keymap (kbd (car binding)))
                (cdr binding))))
  (should (equal (string-trim
                  (meow--short-command-name
                   (lookup-key meow-normal-state-keymap (kbd "s"))))
                 "surround"))
  (dolist (command '(nil ignore))
    (should (equal (string-trim (meow--short-command-name command)) "")))
  (unwind-protect
      (save-window-excursion
        (meow-cheatsheet)
        (with-current-buffer "*Meow Cheatsheet*"
          (should (string-match-p "surround" (buffer-string)))
          (should-not (string-match-p "\\_<\\(nil\\|ignore\\)\\_>"
                                      (buffer-string)))))
    (when-let* ((buffer (get-buffer "*Meow Cheatsheet*")))
      (kill-buffer buffer))))

(ert-deftest suderman/backtick-opens-dashboard-from-editor-and-explorer-maps ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key ibuffer-mode-map (kbd "`"))
              #'suderman/dashboard))
  (should (eq (lookup-key dired-mode-map (kbd "`"))
              #'suderman/dashboard))
  (require 'dirvish)
  (should (eq (lookup-key dirvish-mode-map (kbd "`"))
              #'suderman/dashboard)))

(ert-deftest suderman/dirvish-sidebar-entrypoints-use-s-and-leader-t-d ()
  (should (eq (lookup-key meow-normal-state-keymap (kbd "S"))
              #'suderman/dirvish-side-toggle))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "S"))
              #'suderman/dirvish-side-toggle))
  (should (eq (lookup-key suderman/leader-toggle-map (kbd "d"))
              #'suderman/dirvish-side-toggle))
  (should-not (lookup-key suderman/leader-toggle-map (kbd "t")))
  (should (eq (lookup-key meow-motion-state-keymap (kbd "h"))
              #'meow-left))
  (should (eq (lookup-key ibuffer-mode-map (kbd "S"))
              #'suderman/ibuffer-dirvish-side))
  (should (eq (lookup-key ibuffer-mode-map (kbd "h"))
              #'suderman/ibuffer-toggle))
  (should (eq (lookup-key ibuffer-mode-map (kbd "l"))
              #'suderman/ibuffer-open))
  (dolist (key '("i" "H" "SPC"))
    (should-not (lookup-key ibuffer-mode-map (kbd key)))))

(ert-deftest suderman/leader-files-and-toggles-use-focused-commands ()
  (dolist (key '("/" ":" "\\" "d" "e" "p"))
    (should-not (lookup-key suderman/meow-leader-map (kbd key))))
  (should (eq (lookup-key suderman/leader-file-map (kbd "."))
              #'suderman/dirvish))
  (should (eq (lookup-key suderman/leader-file-map (kbd "f"))
              #'consult-fd))
  (should (eq (lookup-key suderman/leader-file-map (kbd "g"))
              #'consult-ripgrep))
  (should-not (lookup-key suderman/leader-search-map (kbd "g")))
  (dolist (binding '(("c" . display-fill-column-indicator-mode)
                     ("d" . suderman/dirvish-side-toggle)
                     ("h" . hl-line-mode)
                     ("l" . suderman/toggle-line-numbers)
                     ("r" . read-only-mode)
                     ("s" . jinx-mode)
                     ("v" . visual-line-mode)
                     ("w" . whitespace-mode)))
    (should (eq (lookup-key suderman/leader-toggle-map (kbd (car binding)))
                (cdr binding)))))

(provide 'suderman-meow-test)
;;; suderman-meow-test.el ends here
