;;; suderman-android-test.el --- Focused Android checks -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'suderman-android)

(ert-deftest suderman/android-toolbar-is-bottom-and-escape-exits-insert ()
  (let ((tool-bar-map (make-sparse-keymap))
        (input-decode-map (make-sparse-keymap))
        customizations)
    (cl-letf (((symbol-function 'modifier-bar-mode) #'ignore)
              ((symbol-function 'customize-set-variable)
               (lambda (symbol value)
                 (push (list symbol value) customizations)))
              ((symbol-function 'tool-bar--image-expression)
               (lambda (&rest _) 'image))
              ((symbol-function 'tool-bar--flush-cache) #'ignore)
              ((symbol-function 'tool-bar-mode) #'ignore)
              ((symbol-function 'force-mode-line-update) #'ignore))
      (suderman/android-setup-tool-bar)
      (should (member '(tool-bar-position bottom) customizations))
      (should (eq (lookup-key tool-bar-map [suderman-escape])
                  'meow-insert-exit))
      (should-not
       (lookup-key input-decode-map [tool-bar suderman-escape])))))

(ert-deftest suderman/android-volume-buttons-support-modifiers-and-chords ()
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-up)))
    (should (equal (suderman/android-volume-control nil) [escape])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) 'volume-down)))
    (should (equal (suderman/android-volume-meta nil) [tab])))
  (cl-letf (((symbol-function 'read-event) (lambda (&rest _) ?x))
            ((symbol-function 'event-apply-modifier)
             (lambda (event modifier bit prefix)
               (list event modifier bit prefix))))
    (should (equal (suderman/android-volume-control nil)
                   [(120 control 26 "C-")]))
    (should (equal (suderman/android-volume-meta nil)
                   [(120 meta 27 "M-")]))))

(provide 'suderman-android-test)
;;; suderman-android-test.el ends here
