;;; suderman-files-test.el --- File and view behavior checks -*- lexical-binding: t; -*-

;;; Commentary:
;; Tests for custom behavior with enough moving parts to merit a safety net.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'term/xterm)
(require 'url-util)
(require 'image-mode)
(require 'suderman-dashboard)
(require 'suderman-files)
(require 'suderman-images)
(require 'suderman-markdown)
(require 'suderman-org)

;; Dashboard behavior

(ert-deftest suderman/dashboard-closes-full-frame-dirvish-first ()
  (let ((session (make-dirvish :curr-layout t :root-window (selected-window)))
        calls)
    (cl-letf (((symbol-function 'dirvish-curr) (lambda () session))
              ((symbol-function 'dirvish-quit)
               (lambda () (push 'quit calls)))
              ((symbol-function 'dashboard-open)
               (lambda () (push 'open calls))))
      (suderman/dashboard))
    (should (equal (nreverse calls) '(quit open)))))

(ert-deftest suderman/dashboard-filters-and-renumbers-missing-destinations ()
  (let ((user-emacs-directory "/config/emacs/")
        (existing (list (expand-file-name "~/") "/config/emacs/")))
    (cl-letf (((symbol-function 'file-directory-p)
               (lambda (path) (member path existing)))
              ((symbol-function 'suderman/nerd-fonts-available-p) #'ignore))
      (let ((buttons (suderman/dashboard-destinations)))
        (should (equal (mapcar #'car buttons) '("Home" "Emacs" "Scratch")))
        (should (equal (mapcar #'cadr buttons) '("1" "2" "3")))))))

(ert-deftest suderman/dashboard-moves-between-buttons-spatially ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "  ")
      (widget-create 'push-button :tag "Work" :action #'ignore)
      (insert "        ")
      (widget-create 'push-button :tag "Personal" :action #'ignore)
      (insert "\n\nProjects:\n  ")
      (widget-create 'push-button :tag "Alpha" :action #'ignore)
      (insert "       ")
      (widget-create 'push-button :tag "Beta" :action #'ignore)
      (dashboard-mode)
      (cl-labels ((label ()
                    (substring-no-properties
                     (widget-get (get-char-property (point) 'button) :tag))))
        (should (equal (label) "Work"))
        (execute-kbd-macro (kbd "l"))
        (should (equal (label) "Personal"))
        (execute-kbd-macro (kbd "h"))
        (should (equal (label) "Work"))
        (execute-kbd-macro (kbd "j"))
        (should (equal (label) "Alpha"))
        (execute-kbd-macro (kbd "k"))
        (should (equal (label) "Work"))
        (execute-kbd-macro (kbd "h"))
        (should (equal (label) "Work"))
        (execute-kbd-macro (kbd "k"))
        (should (equal (label) "Work"))))))


;; Markdown preview

(ert-deftest suderman/markdown-preview-render-owns-its-target ()
  (let ((root (make-temp-file "markdown-preview-test-" t)))
    (unwind-protect
        (with-temp-buffer
          (insert "| A |\n|---|\n| B |\n")
          (let ((suderman/markdown-preview-server-root root)
                (suderman/markdown-preview-css "<style>table { width: 100%; }</style>"))
            (cl-letf (((symbol-function 'executable-find) (lambda (_) "/bin/pandoc"))
                      ((symbol-function 'suderman/markdown-preview-server-start)
                       (lambda ()
                         (setq suderman/markdown-preview-server-port 4321)))
                      ((symbol-function 'call-process-region)
                       (lambda (&rest arguments)
                         (with-temp-file (car (last arguments))
                           (insert "<colgroup><col></colgroup>\n<table><tr><td>A</td></tr></table>"))
                         0)))
              (should (equal (suderman/markdown-preview-render)
                             suderman/markdown-preview-file)))
            (should (file-exists-p suderman/markdown-preview-version-file))
            (should (string-prefix-p "http://127.0.0.1:4321/"
                                     suderman/markdown-preview-url))
            (let ((html-file suderman/markdown-preview-file))
              (with-temp-buffer
                (insert-file-contents html-file)
                (should-not (search-forward "<colgroup" nil t))
                (goto-char (point-min))
                (should (search-forward "<div class=\"table-wrapper\">" nil t))))))
      (delete-directory root t))))

(ert-deftest suderman/markdown-preview-cleanup-removes-buffer-files ()
  (with-temp-buffer
    (setq-local suderman/markdown-preview-file (make-temp-file "markdown-preview-"))
    (setq-local suderman/markdown-preview-version-file (make-temp-file "markdown-preview-version-"))
    (setq-local suderman/markdown-preview-url "http://127.0.0.1/preview.html")
    (let ((html-file suderman/markdown-preview-file)
          (version-file suderman/markdown-preview-version-file))
      (suderman/markdown-preview-cleanup)
      (should-not (file-exists-p html-file))
      (should-not (file-exists-p version-file))
      (should-not suderman/markdown-preview-file)
      (should-not suderman/markdown-preview-version-file)
      (should-not suderman/markdown-preview-url))))


;; Images and galleries

(ert-deftest suderman/image-copy-sends-static-image-data-with-its-mime-type ()
  (with-temp-buffer
    (setq-local buffer-file-name "/tmp/example.png")
    (let (call)
      (cl-letf (((symbol-function 'file-readable-p) (lambda (_) t))
                ((symbol-function 'file-remote-p) (lambda (_) nil))
                ((symbol-function 'mailcap-file-name-to-mime-type)
                 (lambda (_) "image/png"))
                ((symbol-function 'executable-find) (lambda (_) "/bin/wl-copy"))
                ((symbol-function 'call-process)
                 (lambda (&rest arguments)
                   (setq call arguments)
                   0)))
        (suderman/image-copy-to-clipboard))
      (should (equal call '("wl-copy" "/tmp/example.png" nil nil
                            "--type" "image/png"))))))

(ert-deftest suderman/image-copy-sends-gifs-as-local-files ()
  (with-temp-buffer
    (setq-local buffer-file-name "/tmp/example gif.gif")
    (let (call)
      (cl-letf (((symbol-function 'file-readable-p) (lambda (_) t))
                ((symbol-function 'file-remote-p) (lambda (_) nil))
                ((symbol-function 'mailcap-file-name-to-mime-type)
                 (lambda (_) "image/gif"))
                ((symbol-function 'executable-find) (lambda (_) "/bin/wl-copy"))
                ((symbol-function 'call-process)
                 (lambda (&rest arguments)
                   (setq call arguments)
                   0)))
        (suderman/image-copy-to-clipboard))
      (should (equal call '("wl-copy" nil nil nil
                            "--type" "text/uri-list"
                            "file:///tmp/example%20gif.gif"))))))

(ert-deftest suderman/image-copy-requires-a-local-image-file ()
  (with-temp-buffer
    (should-error (suderman/image-copy-to-clipboard) :type 'user-error))
  (with-temp-buffer
    (setq-local buffer-file-name "/tmp/example.txt")
    (cl-letf (((symbol-function 'file-readable-p) (lambda (_) t))
              ((symbol-function 'file-remote-p) (lambda (_) nil))
              ((symbol-function 'mailcap-file-name-to-mime-type)
               (lambda (_) "text/plain")))
      (should-error (suderman/image-copy-to-clipboard) :type 'user-error))))

(ert-deftest suderman/image-gallery-image-keeps-its-private-thumbnail-buffer ()
  (let ((gallery (generate-new-buffer " *image-gallery-test*"))
        (image (generate-new-buffer " *image-gallery-image-test*"))
        displayed)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer gallery
            (image-dired-thumbnail-mode)
            (setq-local image-dired-thumbnail-buffer (buffer-name gallery)
                        image-dired-display-image-buffer (buffer-name image)
                        image-dired-track-movement nil)
            (let ((inhibit-read-only t))
              (insert (propertize "a" 'image-dired-thumbnail t
                                  'original-file-name "/tmp/a.png")
                      " "
                      (propertize "b" 'image-dired-thumbnail t
                                  'original-file-name "/tmp/b.png")
                      " "
                      (propertize "c" 'image-dired-thumbnail t
                                  'original-file-name "/tmp/c.png")))
            (goto-char (point-min)))
          (switch-to-buffer gallery)
          (cl-letf (((symbol-function 'image-dired-display-this)
                     (lambda () (switch-to-buffer image))))
            (suderman/image-dired-display))
          (with-current-buffer image
            (should (eq suderman/image-dired-gallery-buffer gallery))
            (should (equal image-dired-thumbnail-buffer
                           (buffer-name gallery)))
            (should (equal image-dired-display-image-buffer
                           (buffer-name image))))
          (cl-letf (((symbol-function 'image-dired-display-image)
                     (lambda (file)
                       (setq displayed file)
                       (with-current-buffer image
                         (kill-all-local-variables)))))
            (with-current-buffer image
              (suderman/image-dired-display-next 1))
            (should (equal displayed "/tmp/b.png"))
            (with-current-buffer image
              (suderman/image-dired-display-next 1))
            (should (equal displayed "/tmp/c.png"))
            (with-current-buffer image
              (suderman/image-dired-display-previous 1))
            (should (equal displayed "/tmp/b.png"))))
      (kill-buffer gallery)
      (kill-buffer image))))

(ert-deftest suderman/image-gallery-lists-only-top-level-images ()
  (let* ((directory (make-temp-file "suderman-image-gallery-" t))
         (nested (expand-file-name "nested" directory))
         (image (expand-file-name "one.png" directory))
         (upper-image (expand-file-name "two.JPG" directory))
         (text (expand-file-name "notes.txt" directory))
         (nested-image (expand-file-name "three.webp" nested))
         buffer)
    (unwind-protect
        (progn
          (make-directory nested)
          (dolist (file (list image upper-image text nested-image))
            (write-region "" nil file))
          (let (dired-buffers)
            (setq buffer
                  (dired-internal-noselect
                   (file-name-as-directory directory)
                   dired-listing-switches)))
          (should (equal (suderman/image-dired--files buffer)
                         (list image upper-image))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/image-gallery-leaves-an-empty-directory-untouched ()
  (let* ((directory (make-temp-file "suderman-empty-gallery-" t))
         buffer)
    (unwind-protect
        (save-window-excursion
          (let (dired-buffers)
            (setq buffer
                  (dired-internal-noselect
                   (file-name-as-directory directory)
                   dired-listing-switches)))
          (set-window-buffer (selected-window) buffer)
          (let ((windows (window-list)))
            (should-error (suderman/image-dired-gallery) :type 'user-error)
            (should (equal (window-list) windows))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/image-gallery-restores-its-dirvish-window ()
  (let* ((directory (make-temp-file "suderman-gallery-window-" t))
         (image (expand-file-name "photo.png" directory))
         source gallery source-window windows)
    (unwind-protect
        (save-window-excursion
          (write-region "" nil image)
          (let (dired-buffers)
            (setq source
                  (dired-internal-noselect
                   (file-name-as-directory directory)
                   dired-listing-switches)))
          (delete-other-windows)
          (set-window-buffer (selected-window) source)
          (setq source-window (selected-window))
          (split-window-right)
          (select-window source-window)
          (setq windows (window-list))
          (cl-letf (((symbol-function 'suderman/image-dired--populate)
                     (lambda (buffer backing files _selected-file)
                       (should (equal files (list image)))
                       (with-current-buffer buffer
                         (let ((inhibit-read-only t))
                           (erase-buffer)
                           (insert (propertize "x"
                                               'image-dired-thumbnail t
                                               'original-file-name image
                                               'associated-dired-buffer
                                               backing))
                           (goto-char (point-min)))))))
            (suderman/image-dired-gallery))
          (setq gallery (current-buffer))
          (should (derived-mode-p 'image-dired-thumbnail-mode))
          (should (= (length (window-list)) 1))
          (should (eq (get-text-property
                       (point) 'associated-dired-buffer)
                      source))
          (suderman/image-dired-quit)
          (should (eq (selected-window) source-window))
          (should (equal (window-list) windows))
          (should (eq (window-buffer source-window) source))
          (should (equal (with-selected-window source-window
                           (dired-get-filename nil t))
                         image)))
      (when (buffer-live-p gallery)
        (with-current-buffer gallery
          (setq suderman/image-dired-window-configuration nil
                suderman/image-dired-source-buffer nil
                suderman/image-dired-source-window nil))
        (kill-buffer gallery))
      (when (buffer-live-p source)
        (kill-buffer source))
      (delete-directory directory t))))

(ert-deftest suderman/image-gallery-updates-count-after-deletion ()
  (with-temp-buffer
    (image-dired-thumbnail-mode)
    (let ((inhibit-read-only t))
      (insert (propertize "x" 'image-dired-thumbnail t) " "
              (propertize "x" 'image-dired-thumbnail t)))
    (setq image-dired--number-of-thumbnails 2)
    (cl-letf (((symbol-function 'image-dired-do-flagged-delete)
               (lambda ()
                 (let ((inhibit-read-only t))
                   (delete-region (point-min) (+ (point-min) 2)))))
              ((symbol-function 'image-dired--update-header-line) #'ignore))
      (suderman/image-dired-delete))
    (should (= image-dired--number-of-thumbnails 1))))


;; Dirvish and file operations

(ert-deftest suderman/dired-ripdrag-is-silent-when-missing ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'executable-find) (lambda (_) nil))
              ((symbol-function 'dired-get-marked-files)
               (lambda (&rest _) (ert-fail "Read selection without Ripdrag")))
              ((symbol-function 'make-process)
               (lambda (&rest _) (ert-fail "Started process without Ripdrag")))
              ((symbol-function 'message)
               (lambda (&rest _) (ert-fail "Reported missing Ripdrag"))))
      (should-not (call-interactively #'suderman/dired-ripdrag)))))

(ert-deftest suderman/dired-ripdrag-passes-current-or-marked-files-as-arguments ()
  (let* ((directory (make-temp-file "suderman-ripdrag-" t))
         (current (expand-file-name "current.txt" directory))
         (marked (expand-file-name "space ; quote ' λ.txt" directory))
         (nested (expand-file-name "nested" directory))
         (child (expand-file-name "-child.txt" nested))
         buffer launches)
    (unwind-protect
        (progn
          (make-directory nested)
          (dolist (file (list current marked child))
            (with-temp-file file (insert file)))
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (dired-insert-subdir nested)
            (should (dired-goto-file current))
            (cl-letf (((symbol-function 'executable-find)
                       (lambda (_) "/test/bin/ripdrag"))
                      ((symbol-function 'make-process)
                       (lambda (&rest args) (push args launches))))
              (call-interactively #'suderman/dired-ripdrag)
              (should (equal (last (plist-get (car launches) :command))
                             (list current)))
              (dolist (file (list marked child))
                (should (dired-goto-file file))
                (dired-mark 1))
              (should (dired-goto-file current))
              (call-interactively #'suderman/dired-ripdrag)
              (should (equal (last (plist-get (car launches) :command) 2)
                             (list marked child)))
              (should (equal (dired-get-marked-files) (list marked child)))
              (should (= (length launches) 2))
              (dolist (launch launches)
                (should (equal (car (plist-get launch :command))
                               "/test/bin/ripdrag"))
                (should (plist-get launch :noquery))))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/dired-delete-confirms-marked-files-or-current-entry ()
  (let* ((directory (make-temp-file "suderman-dired-delete-" t))
         (current (expand-file-name "current.txt" directory))
         (marked (expand-file-name "marked.txt" directory))
         (nested (expand-file-name "nested" directory))
         (child (expand-file-name "child.txt" nested))
         (delete-by-moving-to-trash nil)
         buffer prompts accept)
    (unwind-protect
        (progn
          (make-directory nested)
          (dolist (file (list current marked child))
            (with-temp-file file (insert file)))
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (dired-insert-subdir nested)
            (dolist (file (list marked child))
              (should (dired-goto-file file))
              (suderman/dired-toggle-mark))
            (should (dired-goto-file current))
            (let ((dired-deletion-confirmer
                   (lambda (prompt) (push prompt prompts) accept)))
              (call-interactively #'dired-do-delete)
              (should (= (length prompts) 1))
              (should (equal (dired-get-marked-files) (list marked child)))
              (dolist (file (list current marked child))
                (should (file-exists-p file)))
              (setq accept t)
              (call-interactively #'dired-do-delete)
              (should (= (length prompts) 2))
              (should (file-exists-p current))
              (dolist (file (list marked child))
                (should-not (file-exists-p file))
                (should-not (dired-goto-file file)))
              (should (dired-goto-file current))
              (call-interactively #'dired-do-delete)
              (should (= (length prompts) 3))
              (should-not (file-exists-p current))
              (should-not (dired-goto-file current)))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/dired-delete-without-confirmation-keeps-unsaved-buffers ()
  (let* ((directory (make-temp-file "suderman-dired-delete-direct-" t))
         (current (expand-file-name "current.txt" directory))
         (folder (expand-file-name "folder" directory))
         (child (expand-file-name "child.txt" folder))
         (link (expand-file-name "link" directory))
         (delete-by-moving-to-trash nil)
         buffer visiting)
    (unwind-protect
        (progn
          (make-directory folder)
          (dolist (file (list current child))
            (with-temp-file file (insert file)))
          (make-symbolic-link current link)
          (setq buffer (dired-noselect directory)
                visiting (find-file-noselect current))
          (with-current-buffer visiting (insert "unsaved edits"))
          (with-current-buffer buffer
            (dolist (file (list folder link))
              (should (dired-goto-file file))
              (suderman/dired-toggle-mark))
            (should (dired-goto-file current))
            (cl-letf (((symbol-function 'yes-or-no-p)
                       (lambda (&rest _) (ert-fail "Unexpected confirmation")))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _) (ert-fail "Unexpected confirmation")))
                      ((symbol-function 'read-answer)
                       (lambda (&rest _) (ert-fail "Unexpected recursive prompt"))))
              (let ((dired-recursive-deletes nil))
                (call-interactively #'suderman/dired-delete-without-confirmation)
                (should-not dired-recursive-deletes))
              (should (file-exists-p current))
              (should-not (file-exists-p folder))
              (should-not (file-symlink-p link))
              (should-not (dired-goto-file folder))
              (should-not (dired-goto-file link))
              (should (dired-goto-file current))
              (call-interactively #'suderman/dired-delete-without-confirmation)
              (should-not (file-exists-p current))
              (should-not (dired-goto-file current))
              (should (buffer-live-p visiting))
              (with-current-buffer visiting
                (should (buffer-modified-p))
                (should (string-prefix-p "unsaved edits" (buffer-string)))))))
      (when (buffer-live-p visiting)
        (with-current-buffer visiting (set-buffer-modified-p nil))
        (kill-buffer visiting))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/dired-archive-moves-selected-or-marked-items ()
  (let* ((directory (make-temp-file "suderman-dired-archive-" t))
         (file (expand-file-name "selected.txt" directory))
         (folder (expand-file-name "folder" directory))
         (keep (expand-file-name "keep.txt" directory))
         (archive (expand-file-name "archive" directory))
         (archive-org (expand-file-name "archive.org" directory))
         (nested (expand-file-name "nested" directory))
         (nested-file (expand-file-name "nested.txt" nested))
         buffer visiting)
    (unwind-protect
        (progn
          (make-directory folder)
          (make-directory nested)
          (dolist (path (list file keep archive-org nested-file
                             (expand-file-name "child.txt" folder)))
            (with-temp-file path (insert path)))
          (setq buffer (dired-noselect directory)
                visiting (find-file-noselect file))
          (with-current-buffer buffer
            (should (dired-goto-file file))
            (call-interactively #'suderman/org-archive)
            (should-not (file-exists-p file))
            (should (file-exists-p (expand-file-name "selected.txt" archive)))
            (should (equal (buffer-local-value 'buffer-file-name visiting)
                           (expand-file-name "selected.txt" archive)))
            (should-not (dired-goto-file file))
            (revert-buffer)
            (dired-insert-subdir nested)
            (dolist (path (list folder archive archive-org nested-file))
              (should (dired-goto-file path))
              (dired-mark 1))
            (should (dired-goto-file keep))
            (call-interactively #'suderman/org-archive)
            (should (file-exists-p keep))
            (should (file-exists-p archive-org))
            (should (file-directory-p archive))
            (should-not (file-exists-p folder))
            (should-not (file-exists-p nested-file))
            (should (file-exists-p (expand-file-name "folder/child.txt" archive)))
            (should (file-exists-p (expand-file-name "archive/nested.txt" nested)))
            (dired-unmark-all-marks)
            (dolist (path (list archive archive-org))
              (should (dired-goto-file path))
              (call-interactively #'suderman/org-archive)
              (should (file-exists-p path)))
            (should-not (file-exists-p (expand-file-name "archive" archive)))
            (should-not (file-exists-p (expand-file-name "archive.org" archive)))))
      (when (buffer-live-p visiting) (kill-buffer visiting))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/dired-archive-timestamps-collisions-without-overwriting ()
  (dolist (case '(("prompt.org" "prompt-20261006-120345.org" file)
                  ("notes" "notes-20261006-120345" file)
                  (".env" ".env-20261006-120345" file)
                  ("folder" "folder-20261006-120345" directory)
                  ("folder.v1" "folder.v1-20261006-120345" directory)
                  ("link.org" "link-20261006-120345.org" symlink)))
    (let* ((directory (make-temp-file "suderman-dired-archive-conflict-" t))
           (file (expand-file-name (car case) directory))
           (archive (expand-file-name "archive" directory))
           (destination (expand-file-name (car case) archive))
           (renamed (expand-file-name (cadr case) archive))
           (numbered (if (eq (nth 2 case) 'directory)
                         (concat renamed "-2")
                       (concat (file-name-sans-extension renamed) "-2"
                               (file-name-extension renamed t))))
           buffer visiting)
      (unwind-protect
          (progn
            (make-directory archive)
            (if (eq (nth 2 case) 'directory)
                (progn
                  (make-directory file)
                  (with-temp-file (expand-file-name "child.txt" file)
                    (insert "source")))
              (with-temp-file file (insert "source"))
              (setq visiting (find-file-noselect file)))
            (pcase (nth 2 case)
              ('symlink (make-symbolic-link "missing" destination))
              ('directory
               (make-directory destination)
               (with-temp-file (expand-file-name "keep.txt" destination)
                 (insert "existing archive")))
              (_ (with-temp-file destination (insert "existing archive"))))
            (setq buffer (dired-noselect directory))
            (with-current-buffer buffer
              (dired-omit-mode -1)
              (should (dired-goto-file file))
              (cl-letf (((symbol-function 'format-time-string)
                         (lambda (format &rest _)
                           (should (equal format "%Y%m%d-%H%M%S"))
                           "20261006-120345"))
                        ((symbol-function 'dired-query)
                         (lambda (&rest _) (error "Archive prompted to overwrite"))))
                (call-interactively #'suderman/org-archive)
                (should-not (file-exists-p file))
                (should (equal (with-temp-buffer
                                 (insert-file-contents
                                  (if (eq (nth 2 case) 'directory)
                                      (expand-file-name "child.txt" renamed)
                                    renamed))
                                 (buffer-string))
                               "source"))
                (when visiting
                  (should (equal (buffer-local-value 'buffer-file-name visiting)
                                 renamed)))
                (when (eq (nth 2 case) 'directory) (make-directory file))
                (with-temp-file (if (eq (nth 2 case) 'directory)
                                    (expand-file-name "child.txt" file)
                                  file)
                  (insert "second source"))
                (revert-buffer)
                (should (dired-goto-file file))
                (call-interactively #'suderman/org-archive)
                (dolist (entry (list (cons renamed "source")
                                    (cons numbered "second source")))
                  (should (equal (with-temp-buffer
                                   (insert-file-contents
                                    (if (eq (nth 2 case) 'directory)
                                        (expand-file-name "child.txt" (car entry))
                                      (car entry)))
                                   (buffer-string))
                                 (cdr entry))))))
            (if (eq (nth 2 case) 'symlink)
                (should (equal (file-symlink-p destination) "missing"))
              (should (equal (with-temp-buffer
                               (insert-file-contents
                                (if (eq (nth 2 case) 'directory)
                                    (expand-file-name "keep.txt" destination)
                                  destination))
                               (buffer-string))
                             "existing archive"))))
        (when (buffer-live-p visiting) (kill-buffer visiting))
        (when (buffer-live-p buffer) (kill-buffer buffer))
        (delete-directory directory t)))))

(ert-deftest suderman/dired-archive-keeps-files-if-destination-appears-during-move ()
  (let* ((directory (make-temp-file "suderman-dired-archive-race-" t))
         (file (expand-file-name "prompt.org" directory))
         (destination (expand-file-name "archive/prompt.org" directory))
         (rename (symbol-function 'dired-rename-file))
         (dired-backup-overwrite 'always)
         buffer)
    (unwind-protect
        (progn
          (with-temp-file file (insert "source"))
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (should (dired-goto-file file))
            (cl-letf (((symbol-function 'dired-rename-file)
                       (lambda (from to overwrite)
                         (should-not overwrite)
                         (should-not dired-backup-overwrite)
                         (with-temp-file to (insert "late arrival"))
                         (funcall rename from to overwrite))))
              (call-interactively #'suderman/org-archive)))
          (dolist (entry (list (cons file "source")
                              (cons destination "late arrival")))
            (should (equal (with-temp-buffer
                             (insert-file-contents (car entry)) (buffer-string))
                           (cdr entry)))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/dirvish-subtree-toggle-ignores-nondirectories ()
  (let* ((directory (make-temp-file "suderman-subtree-" t))
         (folder (expand-file-name "folder" directory))
         (file (expand-file-name "ordinary.txt" directory))
         (folder-link (expand-file-name "folder-link" directory))
         (file-link (expand-file-name "file-link" directory))
         (broken-link (expand-file-name "broken-link" directory))
         buffer calls)
    (unwind-protect
        (progn
          (make-directory folder)
          (with-temp-file file (insert "ordinary file\n"))
          (make-symbolic-link folder folder-link)
          (make-symbolic-link file file-link)
          (make-symbolic-link (expand-file-name "missing" directory) broken-link)
          (setq buffer (dired-noselect directory))
          (with-current-buffer buffer
            (cl-letf (((symbol-function 'dirvish-subtree-toggle)
                       (lambda () (push (dired-get-filename) calls))))
              (dolist (entry (list file file-link broken-link))
                (should (dired-goto-file entry))
                (let ((before (buffer-string))
                      (position (point)))
                  (call-interactively #'suderman/dirvish-toggle-subtree)
                  (should (equal before (buffer-string)))
                  (should (= position (point)))))
              (should-not calls)
              (goto-char (point-min))
              (should-not (dired-get-filename nil t))
              (call-interactively #'suderman/dirvish-toggle-subtree)
              (should-not calls)
              (dolist (entry (list folder folder-link))
                (should (dired-goto-file entry))
                (call-interactively #'suderman/dirvish-toggle-subtree))
              (should (equal (nreverse calls) (list folder folder-link))))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest suderman/android-dired-tap-opens-in-current-window ()
  (dolist (android '(nil t))
    (let ((system-type (if android 'android 'gnu/linux))
          same-window other-window)
      (cl-letf (((symbol-function 'suderman/dired-mouse-open)
                 (lambda (event) (setq same-window event)))
                ((symbol-function 'dired-mouse-find-file-other-window)
                 (lambda (event) (setq other-window event))))
        (suderman/dired-mouse-secondary-open 'tap)
        (if android
            (progn
              (should (eq same-window 'tap))
              (should-not other-window))
          (should-not same-window)
          (should (eq other-window 'tap)))))))

(ert-deftest suderman/dirvish-normalizes-layout-from-an-ambient-buffer ()
  (save-window-excursion
    (let* ((root-buffer (generate-new-buffer " *suderman-dirvish-root*"))
           (root-window (selected-window))
           (session (make-dirvish :curr-layout 'full-frame
                                  :root-window root-window))
           toggled)
      (unwind-protect
          (progn
            (set-window-buffer root-window root-buffer)
            (with-temp-buffer
              (cl-letf (((symbol-function 'dirvish-curr)
                         (lambda ()
                           (and (eq (current-buffer) root-buffer) session)))
                        ((symbol-function 'dirvish) #'ignore)
                        ((symbol-function 'dirvish-layout-toggle)
                         (lambda ()
                           (should (eq (selected-window) root-window))
                           (setq toggled t)
                           (setf (dv-curr-layout session) nil))))
                (suderman/dirvish "/tmp/")))
            (should toggled)
            (should-not (dv-curr-layout session)))
        (kill-buffer root-buffer)))))

(ert-deftest suderman/dired-terminal-import-and-fallback ()
  (let* ((root (make-temp-file "suderman-import-" t))
         (source (expand-file-name "source" root))
         (dest (expand-file-name "dest" root))
         (names '("space name.csv" "quotes'\";$.csv" "é百分%.csv" " trailing " "ssh:literal"))
         files buffer)
    (unwind-protect
        (progn
          (make-directory source)
          (make-directory dest)
          (dolist (name names)
            (let ((file (expand-file-name name source)))
              (write-region "source" nil file) (push file files)))
          (setq buffer (dired-noselect dest))
          (with-current-buffer buffer
            (should (eq (key-binding [xterm-paste]) #'suderman/dired-xterm-paste))
            (should (eq (key-binding "v") #'suderman/dired-paste))
            (should (eq (key-binding "b") #'suderman/dired-ripdrag))
            (suderman/dired-xterm-paste
             (list 'xterm-paste (concat (string-join files "\n") "\n")))
            (dolist (name names) (should (file-exists-p (expand-file-name name dest))))
            (should-error (suderman/dired-xterm-paste '(xterm-paste "ordinary\ntext"))
                          :type 'buffer-read-only)
            (cl-letf (((symbol-function 'xterm-paste)
                       (lambda (event) (should (equal event '(xterm-paste "ordinary\ntext"))))))
              (suderman/dired-xterm-paste '(xterm-paste "ordinary\ntext")))
            (dolist (text (list "" "relative" (concat (car files) "\nmissing\n")
                                (concat (car files) "\n\n")))
              (should-not (suderman/dired--paste-paths text))))
          (with-temp-buffer
            (require 'term/xterm)
            (should (eq (key-binding [xterm-paste]) #'xterm-paste))
            (suderman/dired-xterm-paste '(xterm-paste "ordinary\ntext"))
            (should (equal (buffer-string) "ordinary\ntext"))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest suderman/dired-import-directory-collisions-and-self-copy ()
  (let* ((root (make-temp-file "suderman-import-dir-" t))
         (source (expand-file-name "source/tree" root))
         (dest (expand-file-name "dest" root))
         (target (expand-file-name "tree" dest))
         (dired-recursive-copies 'always) buffer queries)
    (unwind-protect
        (progn
          (make-directory source t) (make-directory dest)
          (write-region "original" nil (expand-file-name "inside" source))
          (setq buffer (dired-noselect dest))
          (with-current-buffer buffer
            (suderman/dired-import-files (list (file-name-quote source)))
            (should (file-exists-p (expand-file-name "inside" target)))
            (write-region "changed" nil (expand-file-name "inside" source))
            (cl-letf (((symbol-function 'dired-query) (lambda (&rest _) (push t queries) nil))
                      ((symbol-function 'dired-log-summary) #'ignore))
              (suderman/dired-import-files (list (file-name-quote source))))
            (should queries)
            (with-temp-buffer
              (insert-file-contents (expand-file-name "inside" target))
              (should (equal (buffer-string) "original")))
            (cl-letf (((symbol-function 'dired-query) (lambda (&rest _) t)))
              (suderman/dired-import-files (list (file-name-quote source))))
            (should-not (file-exists-p (expand-file-name "tree" target)))
            (with-temp-buffer
              (insert-file-contents (expand-file-name "inside" target))
              (should (equal (buffer-string) "changed")))
            (should-error (suderman/dired--copy-file source source t) :type 'file-error)
            (should-error (suderman/dired--copy-file source (expand-file-name "nested/tree" source) t)
                          :type 'file-error)
            (let ((file (expand-file-name "inside" source)) (to (expand-file-name "existing" dest)))
              (write-region "occupied" nil to)
              (should-error (suderman/dired--copy-file file to nil) :type 'file-already-exists)
              (suderman/dired--copy-file file to t))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest suderman/dired-clipboard-files-decode-local-uris-only ()
  (let* ((root (make-temp-file "suderman-uris-" t))
         (file (expand-file-name "é space%#\nname" root))
         (uri (concat "file://" (url-hexify-string file (cons ?/ url-unreserved-chars)))))
    (unwind-protect
        (progn
          (write-region "file" nil file)
          (dolist (pair (list (cons 'text/uri-list (concat "# comment\r\n" uri "\r\n"))
                             (cons 'x-special/gnome-copied-files (concat "cut\n" uri))
                             (cons 'x-special/mate-copied-files (concat "copy\n" uri))))
            (should (equal (suderman/dired--clipboard-files (car pair) (cdr pair))
                           (list (file-name-quote file)))))
          (should (equal (suderman/dired--clipboard-files 'text/uri-list
                         (concat "file://localhost" (substring uri 7)))
                         (list (file-name-quote file))))
          (should-not (suderman/dired--clipboard-files 'text/uri-list
                       (concat uri "\nhttps://example.org/file")))
          (should-not (suderman/dired--clipboard-files 'text/uri-list "file://other-host/tmp/file")))
      (delete-directory root t))))

(ert-deftest suderman/dired-smart-paste-native-media-and-staged-fallback ()
  (let* ((root (make-temp-file "suderman-smart-paste-" t))
         (file (expand-file-name "clipboard source" root))
         (image (unibyte-string #xff #xd8 #x00 #xff #xd9))
         (timestamp "2026-10-06-211234")
         (existing (expand-file-name (concat "clipboard-" timestamp ".jpg") root))
         (expected (expand-file-name (concat "clipboard-" timestamp "-2.jpg") root))
         (types [text/uri-list image/jpeg]) (suderman/dired-transfer nil)
         buffer imported staged)
    (unwind-protect
        (progn
          (write-region "file" nil file) (write-region "occupied" nil existing)
          (setq buffer (dired-noselect root))
          (with-current-buffer buffer
            (cl-letf (((symbol-function 'gui-get-selection)
                       (lambda (_selection type)
                         (pcase type ('TARGETS types)
                           ('text/uri-list (concat "file://" (url-hexify-string file (cons ?/ url-unreserved-chars))))
                           ('image/jpeg image) (_ "plain text\nnot files"))))
                      ((symbol-function 'format-time-string) (lambda (&rest _) timestamp)))
              (cl-letf (((symbol-function 'suderman/dired-import-files)
                         (lambda (files) (setq imported files))))
                (suderman/dired-paste))
              (should (equal imported (list (file-name-quote file))))
              (setq types [UTF8_STRING])
              (cl-letf (((symbol-function 'executable-find) #'ignore)
                        ((symbol-function 'gui-get-selection)
                         (lambda (_selection type)
                           (if (eq type 'TARGETS) types
                             (concat "file://" (url-hexify-string file
                                                   (cons ?/ url-unreserved-chars))))))
                        ((symbol-function 'suderman/dired-import-files)
                         (lambda (files) (setq imported files))))
                (setq imported nil)
                (suderman/dired-paste)
                (should (equal imported (list (file-name-quote file)))))
              (setq types [image/jpeg]) (suderman/dired-paste)
              (should (equal (dired-get-filename nil t) expected))
              (with-temp-buffer
                (set-buffer-multibyte nil) (insert-file-contents-literally expected)
                (should (equal (buffer-string) image)))
              (setq types [text/plain])
              (let ((before (directory-files root)))
                (suderman/dired-paste) (should (equal before (directory-files root))))
              (let ((suderman/dired-transfer '(copy "file")))
                (cl-letf (((symbol-function 'suderman/dired-paste-files) (lambda () (setq staged t))))
                  (suderman/dired-paste)))
              (should staged)
              (should-error (suderman/dired--write-image 'image/png "") :type 'user-error))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest suderman/dired-clipboard-optional-wayland-reader ()
  (with-temp-buffer
    (let ((default-directory "/ssh:server:/directory/")
          (process-environment (copy-sequence process-environment)) calls)
      (setenv "WAYLAND_DISPLAY" "wayland-test")
      (setenv "SSH_CONNECTION" nil) (setenv "SSH_TTY" nil)
      (cl-letf (((symbol-function 'gui-get-selection) #'ignore)
                ((symbol-function 'getenv)
                 (lambda (name &optional _) (getenv-internal name)))
                ((symbol-function 'executable-find)
                 (lambda (_) (should (equal default-directory "/")) "/bin/wl-paste"))
                ((symbol-function 'call-process)
                 (lambda (_program _in _out _display &rest args)
                   (should (equal default-directory "/"))
                   (should (eq coding-system-for-read 'binary))
                   (should-not enable-multibyte-characters)
                   (push args calls)
                   (insert (if (equal args '("--list-types")) "image/png\n" "bytes")) 0)))
        (pcase-let ((`(,types . ,reader) (suderman/dired--clipboard-reader)))
          (should (equal types '(image/png)))
          (should (equal (funcall reader 'image/png) "bytes")))
        (should (= (length calls) 2))
        (setenv "SSH_CONNECTION" "remote") (should-not (suderman/dired--clipboard-reader))
        (setenv "SSH_CONNECTION" nil)
        (cl-letf (((symbol-function 'executable-find) #'ignore))
          (should-not (suderman/dired--clipboard-reader)))))))

(ert-deftest suderman/dirvish-windmove-rejects-breadcrumb-window ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((window (split-window-right))
           (buffer (generate-new-buffer " *dirvish-misc-test*")))
      (unwind-protect
          (progn
            (set-window-buffer window buffer)
            (with-current-buffer buffer (dirvish-misc-mode))
            (should-not
             (suderman/dirvish-ignore-misc-window
              (lambda (&rest _) window)))
            (with-current-buffer buffer (fundamental-mode))
            (should
             (eq (suderman/dirvish-ignore-misc-window
                  (lambda (&rest _) window))
                 window)))
        (kill-buffer buffer)))))

(ert-deftest suderman/dirvish-narrow-renders-after-live-update ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (session (make-dirvish :root-window root))
           events received)
      (cl-letf (((symbol-function 'dirvish-curr) (lambda () session))
                ((symbol-function 'dirvish--render-attrs)
                 (lambda (window selected)
                   (push (list 'render window selected) events))))
        (suderman/dirvish-render-after-narrow
         (lambda (action record callback debounce throttle)
           (setq received (list action record debounce throttle))
           (funcall callback 'input))
         "pdf" :narrow
         (lambda (input) (push (list 'update input) events))
         0.1 0.2)
        (should (equal received '("pdf" :narrow 0.1 0.2)))
        (should (equal (nreverse events)
                       `((update input) (render ,root ,root))))))))

(ert-deftest suderman/dirvish-parent-navigation-preserves-parent-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (parent (split-window root nil 'left))
           (session (make-dirvish :root-window root))
           navigation)
      (set-window-parameter parent 'no-other-window t)
      (select-window parent)
      (cl-letf (((symbol-function 'dirvish-curr) (lambda () session))
                ((symbol-function 'dirvish--find-entry)
                 (lambda (find entry) (setq navigation (list find entry)))))
        (suderman/dirvish-parent-navigate "/tmp/next/")
        (should (equal navigation '(find-alternate-file "/tmp/next/")))
        (should (eq (selected-window) parent))))))

(ert-deftest suderman/dirvish-preview-keeps-explorer-keys-buffer-local ()
  ;; Isolate shared maps so a failing test cannot poison later tests.
  (let ((emacs-lisp-mode-map (copy-keymap emacs-lisp-mode-map))
        (org-mode-map (copy-keymap org-mode-map))
        (text-mode-map (copy-keymap text-mode-map)))
    (dolist (mode '(emacs-lisp-mode org-mode text-mode fundamental-mode))
      (save-window-excursion
        (with-temp-buffer
          (funcall mode)
          (let* ((shared-map (current-local-map))
                 (original-map (and shared-map (copy-keymap shared-map))))
            (run-hooks 'dirvish-preview-setup-hook)
            (run-hooks 'dirvish-preview-setup-hook)
            (should (equal shared-map original-map))
            (should (eq (lookup-key (current-local-map) (kbd ","))
                        #'suderman/dirvish-ibuffer))
            (should (eq (lookup-key (current-local-map) (kbd "`"))
                        #'suderman/dashboard)))
          ;; A new editor in the same mode must retain its typing map.
          (with-temp-buffer
            (funcall mode)
            (set-window-buffer (selected-window) (current-buffer))
            (meow-mode 1)
            (should (eq (key-binding (kbd ",")) #'suderman/ibuffer-toggle))
            (should (eq (key-binding (kbd ".")) #'suderman/dirvish))
            (suderman/meow-insert)
            (execute-kbd-macro (kbd ", . `"))
            (should (equal (buffer-string) ",.`"))
            (should (meow-insert-mode-p))))))))

(ert-deftest suderman/dirvish-peek-follows-consult-async-results ()
  (let* ((file (make-temp-file "suderman-peek-"))
         (default-directory (file-name-directory file))
         (vertico--index -1)
         (dirvish--props (list (cons :peek-category 'file)
                               (cons :peek-fetcher
                                     #'suderman/dirvish-peek-candidate)))
         (session (make-dirvish :type 'peek))
         preview)
    (unwind-protect
        (cl-letf (((symbol-function 'vertico--candidate)
                   (lambda () (if (< vertico--index 0) "#suderman"
                                (file-name-nondirectory file))))
                  ((symbol-function 'dirvish-curr) (lambda () session))
                  ((symbol-function 'dirvish--preview-update)
                   (lambda (_session path) (setq preview path))))
          (should-not (suderman/dirvish-peek-candidate))
          (suderman/dirvish-peek-consult-refresh)
          (should-not preview)
          (setq vertico--index 0)
          (should (equal (suderman/dirvish-peek-candidate)
                         (file-name-nondirectory file)))
          (suderman/dirvish-peek-consult-refresh)
          (should (equal preview file)))
      (delete-file file))))

(ert-deftest suderman/dirvish-sidebar-open-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           opened)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p) #'ignore)
                ((symbol-function 'dirvish-side)
                 (lambda (path)
                   (setq opened path)
                   (select-window sidebar))))
        (suderman/dirvish-side-toggle "/tmp/")
        (should (equal opened "/tmp/"))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-colors-vc-filenames ()
  (with-temp-buffer
    (let ((dirvish--dir-data (make-hash-table :test #'equal)))
      (dolist (entry '(("lisp" dir edited warning)
                       ("suderman-meow.el" file edited warning)
                       ("added.el" file added success)
                       ("removed.el" file removed error)
                       ("new.el" file unregistered font-lock-constant-face)
                       ("clean.el" file up-to-date nil)))
        (let* ((name (nth 0 entry))
               (file (concat "/tmp/" name))
               (beg (point)))
          (insert name)
          (puthash (secure-hash 'md5 file)
                   (list :vc-state (nth 2 entry)) dirvish--dir-data)
          (let ((rendered (dirvish-attribute-suderman-vc-state-rd
                           beg (point) name file nil (cons (nth 1 entry) nil)
                           beg (point) nil 35)))
            (if (nth 3 entry)
                (let ((ov (cdr rendered)))
                  (should (eq (car rendered) 'ov))
                  (should (= (overlay-start ov) beg))
                  (should (= (overlay-end ov) (point)))
                  (should (eq (overlay-get ov 'face) (nth 3 entry)))
                  (should-not (overlay-get ov 'before-string)))
              (should-not rendered)))
          (insert "\n"))))))

(ert-deftest suderman/dirvish-period-focuses-resizable-sidebar ()
  (save-window-excursion
    (delete-other-windows)
    (let ((editor (selected-window))
          (directory (make-temp-file "suderman-sidebar-" t)))
      (unwind-protect
          (progn
            (suderman/dirvish-side-toggle directory)
            (let* ((sidebar (dirvish-side--session-visible-p))
                   (session (with-current-buffer (window-buffer sidebar)
                              (dirvish-curr))))
              (should (eq editor (selected-window)))
              (should (eq (dv-type session) 'side))
              (should-not (dv-size-fixed session))
              (with-selected-window sidebar
                (dirvish--build-layout session))
              (should-not (with-current-buffer (window-buffer sidebar)
                            window-size-fixed))
              (let ((width (window-width sidebar)))
                (with-selected-window sidebar (enlarge-window-horizontally 5))
                (should (> (window-width sidebar) width)))
              (suderman/dirvish)
              (should (eq (selected-window) sidebar))
              (should (eq (dirvish-side--session-visible-p) sidebar))
              (suderman/dirvish)
              (should-not (dirvish-side--session-visible-p))))
        (when-let* ((sidebar (dirvish-side--session-visible-p)))
          (with-selected-window sidebar (dirvish-quit)))
        (delete-directory directory t)))))

(ert-deftest suderman/dirvish-sidebar-resizes-from-editor ()
  (save-window-excursion
    (delete-other-windows)
    (let ((editor (selected-window))
          (directory (make-temp-file "suderman-sidebar-resize-" t)))
      (unwind-protect
          (progn
            (suderman/dirvish-side-toggle directory)
            (let* ((sidebar (dirvish-side--session-visible-p))
                   (width (window-width sidebar)))
              (should-not (window-in-direction 'left editor))
              (should (eq (window-in-direction 'left editor t) sidebar))
              (suderman/resize-window-right)
              (should (= (window-width sidebar) (+ width 5)))
              (suderman/resize-window-left)
              (should (= (window-width sidebar) width))
              (should (eq (selected-window) editor))))
        (when-let* ((sidebar (dirvish-side--session-visible-p)))
          (with-selected-window sidebar (dirvish-quit)))
        (delete-directory directory t)))))

(ert-deftest suderman/resize-window-excludes-non-side-special-windows ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((special (selected-window))
           (editor (split-window-right)))
      (set-window-parameter special 'no-other-window t)
      (select-window editor)
      (should-error (suderman/resize-window-right) :type 'user-error))))

(ert-deftest suderman/dirvish-explicit-path-ignores-visible-sidebar ()
  (save-window-excursion
    (delete-other-windows)
    (let ((editor (selected-window))
          (sidebar (split-window-right))
          opened)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p)
                 (lambda () sidebar))
                ((symbol-function 'dirvish)
                 (lambda (directory) (setq opened directory))))
        (suderman/dirvish "/tmp/")
        (should (equal opened "/tmp/"))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-sidebar-hide-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           quit-window)
      (select-window editor)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p)
                 (lambda () sidebar))
                ((symbol-function 'dirvish-quit)
                 (lambda () (setq quit-window (selected-window)))))
        (suderman/dirvish-side-toggle)
        (should (eq quit-window sidebar))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-breadcrumb-navigation-uses-root-window ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (misc (split-window-right))
           (misc-buffer (generate-new-buffer " *dirvish-misc-test*"))
           (session (make-dirvish :root-window root))
           called-window)
      (unwind-protect
          (progn
            (set-window-buffer misc misc-buffer)
            (select-window misc)
            (with-current-buffer misc-buffer
              (dirvish-misc-mode)
              (cl-letf (((symbol-function 'dirvish-curr) (lambda () session)))
                (suderman/dirvish-find-entry-at-root
                 (lambda (_find _entry)
                   (setq called-window (selected-window)))
                 #'find-file "/tmp/")))
            (should (eq called-window root))
            (should (eq (selected-window) root)))
        (kill-buffer misc-buffer)))))

(ert-deftest suderman/dirvish-parent-file-click-centers-and-selects-file ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (parent (split-window-right))
           (session (make-dirvish :root-window root))
           (file "/tmp/example.txt")
           navigation selected)
      (select-window parent)
      (cl-letf (((symbol-function 'event-start) (lambda (_) 'position))
                ((symbol-function 'posn-window) (lambda (_) parent))
                ((symbol-function 'posn-point) (lambda (_) 1))
                ((symbol-function 'dired-get-filename) (lambda (&rest _) file))
                ((symbol-function 'dirvish-curr) (lambda () session))
                ((symbol-function 'file-directory-p) #'ignore)
                ((symbol-function 'dirvish--find-entry)
                 (lambda (find entry) (setq navigation (list find entry))))
                ((symbol-function 'dired-goto-file)
                 (lambda (entry) (setq selected entry))))
        (suderman/dirvish-parent-mouse-select 'event))
      (should (equal navigation '(find-alternate-file "/tmp/")))
      (should (equal selected file))
      (should (eq (selected-window) root)))))

(ert-deftest suderman/dirvish-gif-preview-loops-only-while-displayed ()
  (with-temp-buffer
    (insert (propertize " " 'display 'image-spec))
    (let ((recipe (cons 'buffer (current-buffer)))
          callback callback-arg animate-args)
      (cl-letf (((symbol-function 'dirvish--find-file-temporarily)
                 (lambda (_) recipe))
                ((symbol-function 'run-with-idle-timer)
                 (lambda (_seconds _repeat function argument)
                   (setq callback function callback-arg argument)))
                ((symbol-function 'image-animate)
                 (lambda (&rest args) (setq animate-args args))))
        (should (eq (dirvish-gif-dp "example.gif" "gif" nil nil) recipe))
        (funcall callback callback-arg)
        (should (equal animate-args '(image-spec nil t 1)))))))

(ert-deftest suderman/kitty-graphics-probe-redraws-the-selected-frame ()
  (skip-unless (featurep 'kitty-graphics))
  (let ((replies (string-to-list "\e[1;1R\e[1;3R\e[1;5R\e[0n"))
        (kitty-graphics--text-sizing-support nil)
        (unread-command-events nil)
        events sizing)
    (cl-letf (((symbol-function 'terminal-parameter)
               (lambda (_terminal key)
                 (when (eq key 'kitty-graphics-text-sizing) sizing)))
              ((symbol-function 'set-terminal-parameter)
               (lambda (_terminal key value)
                 (when (eq key 'kitty-graphics-text-sizing)
                   (setq sizing value))))
              ((symbol-function 'send-string-to-terminal)
               (lambda (sequence &rest _)
                 (should (string-match-p "\e\\[2K" sequence))
                 (should (string-match-p "66;s=2" sequence))
                 (push 'probe events)))
              ((symbol-function 'read-event)
               (lambda (&rest _) (pop replies)))
              ((symbol-function 'redraw-frame)
               (lambda (frame) (push (list 'redraw frame) events))))
      (should (eq (kitty-graphics--query-text-sizing-support) 'scale))
      (should (eq sizing 'scale))
      (should (equal (reverse events)
                     (list 'probe (list 'redraw (selected-frame)))))
      (let ((previous-events (copy-sequence events)))
        (should (eq (kitty-graphics--query-text-sizing-support) 'scale))
        (should (equal events previous-events))))))

(provide 'suderman-files-test)
;;; suderman-files-test.el ends here
