;;; suderman-files-test.el --- Focused Dirvish checks -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'suderman-files)

(ert-deftest suderman/dirvish-extensions-and-mouse-bindings-are-available ()
  (should dirvish-side-follow-mode)
  (should dirvish-peek-mode)
  (should (equal dirvish-attributes
                 '(vc-state subtree-state nerd-icons collapse file-size)))
  (dolist (binding '(("TAB" . dirvish-subtree-toggle)
                     ("'" . dirvish-setup-menu)
                     (";" . dirvish-dispatch)
                     ("E" . dirvish-emerge-menu)
                     ("N" . dirvish-narrow)
                     ("R" . dirvish-rsync)
                     ("S" . suderman/dirvish-side-toggle)
                     ("<mouse-1>" . mouse-set-point)
                     ("<double-mouse-1>" . suderman/dired-mouse-open)
                     ("<mouse-3>" . context-menu-open)))
    (should (eq (lookup-key dirvish-mode-map (kbd (car binding)))
                (cdr binding))))
  (should (eq (lookup-key dirvish-directory-view-mode-map
                          (kbd "<mouse-1>"))
              #'suderman/dirvish-parent-mouse-select))
  (dolist (binding '(("h" . suderman/dirvish-parent-up-directory)
                     ("j" . suderman/dirvish-parent-next-directory)
                     ("k" . suderman/dirvish-parent-previous-directory)
                     ("l" . suderman/dirvish-focus-root)))
    (should (eq (lookup-key dirvish-directory-view-mode-map
                            (kbd (car binding)))
                (cdr binding))))
  (dolist (map (list dirvish-directory-view-mode-map dirvish-misc-mode-map))
    (dolist (key '("M-h" "M-j" "M-k" "M-l"))
      (should (eq (lookup-key map (kbd key))
                  #'suderman/dirvish-focus-root)))))

(ert-deftest suderman/dirvish-uses-frame-width-and-window-count-for-layout ()
  (dolist (case '((79 t t) (80 t nil) (80 nil t)))
    (let (opened toggled)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish) (lambda (_) (setq opened t)))
                ((symbol-function 'dirvish-layout-toggle)
                 (lambda () (setq toggled t)))
                ((symbol-function 'frame-width)
                 (lambda (&optional _) (nth 0 case)))
                ((symbol-function 'one-window-p)
                 (lambda (&rest _) (nth 1 case))))
        (suderman/dirvish "/tmp/")
        (should opened)
        (should (eq toggled (nth 2 case)))))))

(ert-deftest suderman/dirvish-single-click-does-not-follow-dired-links ()
  (with-temp-buffer
    (let ((mouse-1-click-follows-link 450))
      (suderman/dired-setup)
      (should (local-variable-p 'mouse-1-click-follows-link))
      (should-not mouse-1-click-follows-link))))

(ert-deftest suderman/pdf-tools-opens-pdf-files ()
  (should (featurep 'pdf-tools))
  (should (eq (assoc-default "example.pdf" auto-mode-alist #'string-match)
              'pdf-view-mode))
  (should (eq (assoc-default "%PDF-1.7" magic-mode-alist #'string-match)
              'pdf-view-mode)))

(ert-deftest suderman/dirvish-opens-media-with-desktop-player ()
  (let ((file "/tmp/example.mp3")
        (mime-type "audio/mpeg")
        processes file-opened)
    (cl-letf (((symbol-function 'dired-get-file-for-visit)
               (lambda () file))
              ((symbol-function 'file-directory-p) #'ignore)
              ((symbol-function 'mailcap-file-name-to-mime-type)
               (lambda (_) mime-type))
              ((symbol-function 'executable-find) (lambda (_) "/bin/xdg-open"))
              ((symbol-function 'start-process)
               (lambda (&rest arguments) (push arguments processes)))
              ((symbol-function 'dired-find-file)
               (lambda () (setq file-opened t))))
      (suderman/dired-open)
      (setq file "/tmp/example.epub"
            mime-type "application/epub+zip")
      (suderman/dired-open))
    (should (equal (nreverse processes)
                   '(("open-media" nil "xdg-open" "/tmp/example.mp3")
                     ("open-media" nil "xdg-open" "/tmp/example.epub"))))
    (should-not file-opened)))

(ert-deftest suderman/dirvish-opens-documents-inside-emacs ()
  (let (process file-opened)
    (cl-letf (((symbol-function 'dired-get-file-for-visit)
               (lambda () "/tmp/example.pdf"))
              ((symbol-function 'file-directory-p) #'ignore)
              ((symbol-function 'mailcap-file-name-to-mime-type)
               (lambda (_) "application/pdf"))
              ((symbol-function 'start-process)
               (lambda (&rest arguments) (setq process arguments)))
              ((symbol-function 'dired-find-file)
               (lambda () (setq file-opened t))))
      (suderman/dired-open))
    (should file-opened)
    (should-not process)))

(ert-deftest suderman/dirvish-subtree-arrows-toggle-on-click ()
  (dolist (icon (list (car dirvish-subtree--state-icons)
                      (cdr dirvish-subtree--state-icons)))
    (let ((map (get-text-property 0 'keymap icon)))
      (should map)
      (should (eq (lookup-key map [mouse-1])
                  #'dirvish-subtree-toggle-or-open)))))

(ert-deftest suderman/dirvish-windmove-rejects-breadcrumb-window ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((window (split-window-right))
           (buffer (generate-new-buffer " *dirvish-misc-test*")))
      (unwind-protect
          (progn
            (set-window-buffer window buffer)
            (with-current-buffer buffer (dirvish-misc-mode))
            (should-not
             (suderman/dirvish-ignore-misc-window
              (lambda (&rest _) window)))
            (with-current-buffer buffer (fundamental-mode))
            (should
             (eq (suderman/dirvish-ignore-misc-window
                  (lambda (&rest _) window))
                 window)))
        (kill-buffer buffer)))))

(ert-deftest suderman/dirvish-narrow-renders-after-live-update ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (session (make-dirvish :root-window root))
           events received)
      (cl-letf (((symbol-function 'dirvish-curr) (lambda () session))
                ((symbol-function 'dirvish--render-attrs)
                 (lambda (window selected)
                   (push (list 'render window selected) events))))
        (suderman/dirvish-render-after-narrow
         (lambda (action record callback debounce throttle)
           (setq received (list action record debounce throttle))
           (funcall callback 'input))
         "pdf" :narrow
         (lambda (input) (push (list 'update input) events))
         0.1 0.2)
        (should (equal received '("pdf" :narrow 0.1 0.2)))
        (should (equal (nreverse events)
                       `((update input) (render ,root ,root))))))))

(ert-deftest suderman/dirvish-parent-movement-navigates-to-directory ()
  (let (moved navigated)
    (cl-letf (((symbol-function 'dired-next-dirline)
               (lambda (arg) (setq moved arg)))
              ((symbol-function 'dired-get-filename)
               (lambda (&rest _) "/tmp/next/"))
              ((symbol-function 'file-directory-p) (lambda (_) t))
              ((symbol-function 'suderman/dirvish-parent-navigate)
               (lambda (directory) (setq navigated directory))))
      (suderman/dirvish-parent-next-directory)
      (should (= moved 1))
      (should (equal navigated "/tmp/next/")))))

(ert-deftest suderman/dirvish-parent-navigation-preserves-parent-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (parent (split-window root nil 'left))
           navigation)
      (set-window-parameter parent 'no-other-window t)
      (select-window parent)
      (cl-letf (((symbol-function 'dirvish-curr) (lambda () 'session))
                ((symbol-function 'dv-root-window) (lambda (_) root))
                ((symbol-function 'dirvish--find-entry)
                 (lambda (find entry) (setq navigation (list find entry)))))
        (suderman/dirvish-parent-navigate "/tmp/next/")
        (should (equal navigation '(find-alternate-file "/tmp/next/")))
        (should (eq (selected-window) parent))))))

(ert-deftest suderman/dirvish-sidebar-open-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           opened)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p) #'ignore)
                ((symbol-function 'dirvish-side)
                 (lambda (path)
                   (setq opened path)
                   (select-window sidebar))))
        (suderman/dirvish-side-toggle "/tmp/")
        (should (equal opened "/tmp/"))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-sidebar-hide-preserves-editor-focus ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor (selected-window))
           (sidebar (split-window-right))
           quit-window)
      (select-window editor)
      (cl-letf (((symbol-function 'dirvish-curr) #'ignore)
                ((symbol-function 'dirvish-side--session-visible-p)
                 (lambda () sidebar))
                ((symbol-function 'dirvish-quit)
                 (lambda () (setq quit-window (selected-window)))))
        (suderman/dirvish-side-toggle)
        (should (eq quit-window sidebar))
        (should (eq (selected-window) editor))))))

(ert-deftest suderman/dirvish-breadcrumb-navigation-uses-root-window ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (misc (split-window-right))
           (misc-buffer (generate-new-buffer " *dirvish-misc-test*"))
           called-window)
      (unwind-protect
          (progn
            (set-window-buffer misc misc-buffer)
            (select-window misc)
            (with-current-buffer misc-buffer
              (dirvish-misc-mode)
              (cl-letf (((symbol-function 'dirvish-curr) (lambda () 'session))
                        ((symbol-function 'dv-root-window) (lambda (_) root)))
                (suderman/dirvish-find-entry-at-root
                 (lambda (_find _entry)
                   (setq called-window (selected-window)))
                 #'find-file "/tmp/")))
            (should (eq called-window root))
            (should (eq (selected-window) root)))
        (kill-buffer misc-buffer)))))

(ert-deftest suderman/dirvish-parent-file-click-centers-and-selects-file ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((root (selected-window))
           (parent (split-window-right))
           (file "/tmp/example.txt")
           navigation selected)
      (select-window parent)
      (cl-letf (((symbol-function 'event-start) (lambda (_) 'position))
                ((symbol-function 'posn-window) (lambda (_) parent))
                ((symbol-function 'posn-point) (lambda (_) 1))
                ((symbol-function 'dired-get-filename) (lambda (&rest _) file))
                ((symbol-function 'dirvish-curr) (lambda () 'session))
                ((symbol-function 'dv-root-window) (lambda (_) root))
                ((symbol-function 'file-directory-p) #'ignore)
                ((symbol-function 'dirvish--find-entry)
                 (lambda (find entry) (setq navigation (list find entry))))
                ((symbol-function 'dired-goto-file)
                 (lambda (entry) (setq selected entry))))
        (suderman/dirvish-parent-mouse-select 'event))
      (should (equal navigation '(find-alternate-file "/tmp/")))
      (should (equal selected file))
      (should (eq (selected-window) root)))))

(ert-deftest suderman/kitty-graphics-enables-terminal-features ()
  (should (fboundp 'kitty-graphics-setup))
  (should kitty-graphics-enable-video)
  (should kitty-graphics-dirvish-video-inline-preview)
  (should-not kitty-graphics-heading-sizes-auto)
  (should (memq #'kitty-graphics--enable-on-tty-frame
                server-after-make-frame-hook)))

(ert-deftest suderman/dirvish-gif-preview-loops-only-while-displayed ()
  (with-temp-buffer
    (insert (propertize " " 'display 'image-spec))
    (let ((recipe (cons 'buffer (current-buffer)))
          callback callback-arg animate-args)
      (cl-letf (((symbol-function 'dirvish--find-file-temporarily)
                 (lambda (_) recipe))
                ((symbol-function 'run-with-idle-timer)
                 (lambda (_seconds _repeat function argument)
                   (setq callback function callback-arg argument)))
                ((symbol-function 'image-animate)
                 (lambda (&rest args) (setq animate-args args))))
        (should (eq (dirvish-gif-dp "example.gif" "gif" nil nil) recipe))
        (funcall callback callback-arg)
        (should (equal animate-args '(image-spec nil t 1)))))))

(ert-deftest suderman/dirvish-previews-gzip-files-as-archives ()
  (should (member "gz" dirvish-archive-exts))
  (should (member "gz" dirvish-binary-exts))
  (should (eq (car (dirvish-archive-dp
                    "/tmp/incomplete.gif.gz" "gz" nil nil))
              'shell)))

(provide 'suderman-files-test)
;;; suderman-files-test.el ends here
