;;; suderman-help.el --- Context-aware keyboard cheatsheets -*- lexical-binding: t; -*-

;;; Commentary:
;; Reuse Meow's keyboard drawing for views whose local maps own editing keys.
;; Labels describe commands; the invoking buffer remains the source of bindings.

;;; Code:

(require 'cl-lib)
(require 'seq)
(require 'subr-x)
(require 'meow-cheatsheet)

(defvar suderman/cheatsheet-command-labels
  '((undefined . "")
    (self-insert-command . "")
    (digit-argument . "argument")
    (negative-argument . "arg -")
    (beginning-of-buffer . "start")
    (describe-mode . "mode help")
    (set-mark-command . "region")
    (meow-keypad . "keypad")
    (delete-other-windows . "maximize")
    (quit-window . "quit")
    (next-buffer . "next buf")
    (previous-buffer . "prev buf")
    (revert-buffer . "refresh")
    (ibuffer-forward-line . "down")
    (ibuffer-backward-line . "up")
    (suderman/ibuffer-open . "visit")
    (suderman/ibuffer-toggle-mark . "mark")
    (suderman/ibuffer-mark-all . "mark all")
    (suderman/ibuffer-unmark . "unmark")
    (suderman/ibuffer-dirvish . "files")
    (suderman/ibuffer-dirvish-side . "sidebar")
    (ibuffer-do-toggle-modified . "modified?")
    (ibuffer-do-shell-command-file . "shell")
    (ibuffer-add-to-tmp-hide . "hide re")
    (ibuffer-add-to-tmp-show . "show re")
    (ibuffer-diff-with-file . "file diff")
    (ibuffer-do-query-replace . "replace?")
    (ibuffer-copy-filename-as-kill . "copy path")
    (ibuffer-copy-buffername-as-kill . "copy name")
    (ibuffer-do-view-and-eval . "view/eval")
    (ibuffer-do-eval . "eval")
    (ibuffer-visit-buffer . "visit")
    (ibuffer-visit-buffer-other-window . "visit win")
    (ibuffer-do-replace-regexp . "repl re")
    (ibuffer-do-query-replace-regexp . "repl re?")
    (ibuffer-do-rename-uniquely . "rename")
    (ibuffer-toggle-marks . "invert")
    (ibuffer-do-toggle-read-only . "readonly?")
    (ibuffer-do-occur . "occur")
    (ibuffer-do-print . "print")
    (ibuffer-do-view . "view")
    (ibuffer-do-delete . "kill")
    (ibuffer-update . "refresh")
    (ibuffer-do-toggle-lock . "lock?")
    (ibuffer-do-kill-on-deletion-marks . "kill flag")
    (ibuffer-do-shell-command-pipe . "pipe")
    (ibuffer-do-shell-command-pipe-replace . "pipe/repl")
    (ibuffer-do-revert . "revert")
    (ibuffer-bury-buffer . "bury")
    (ibuffer-unmark-all-marks . "clear mrk")
    (ibuffer-forward-filter-group . "next grp")
    (dired-next-line . "down")
    (dired-previous-line . "up")
    (dired-up-directory . "parent")
    (suderman/dired-open . "visit")
    (suderman/dired-ripdrag . "drag")
    (suderman/dired-toggle-mark . "mark")
    (suderman/dired-unmark . "unmark")
    (suderman/dired-delete-without-confirmation . "delete!")
    (suderman/dired-mark-all . "mark all")
    (suderman/dired-create-item . "new item")
    (suderman/dired-copy-files . "copy")
    (suderman/dired-cut-files . "cut")
    (suderman/dired-paste . "paste")
    (suderman/dired-kitty-receive . "receive")
    (suderman/dirvish . "files")
    (suderman/mail-open . "select")
    (suderman/dirvish-toggle-dotfiles . "dotfiles?")
    (suderman/dirvish-ibuffer . "buffers")
    (suderman/dirvish-search . "search")
    (suderman/dirvish-help . "key help")
    (suderman/image-dired-gallery . "gallery")
    (tramp-dired-find-file-with-sudo . "sudo open")
    (browse-url-of-dired-file . "browser")
    (dired-flag-backup-files . "flag bak")
    (dired-flag-auto-save-files . "flag auto")
    (dired-flag-file-deletion . "flag del")
    (dired-hide-subdir . "hide dir")
    (dired-hide-details-mode . "details?")
    (dired-do-shell-command . "shell")
    (dired-do-async-shell-command . "shell &")
    (dired-diff . "diff")
    (dired-create-directory . "mkdir")
    (dired-do-find-regexp . "find re")
    (dired-do-find-regexp-and-replace . "repl re?")
    (dired-copy-filename-as-kill . "copy path")
    (dired-find-file . "visit")
    (dired-do-rename . "rename")
    (dired-toggle-marks . "invert")
    (dired-do-touch . "touch")
    (dired-show-file-type . "file type")
    (dired-do-relsymlink . "rel link")
    (dired-unmark-all-marks . "clear mrk")
    (dired-do-chown . "owner")
    (dired-do-print . "print")
    (dired-do-delete . "delete")
    (dired-do-find-marked-files . "open mrks")
    (dired-do-compress . "compress")
    (dired-do-flagged-delete . "del flags")
    (dired-do-copy . "copy now")
    (dired-do-byte-compile . "compile")
    (dired-prev-dirline . "prev dir")
    (dirvish-quit . "quit")
    (dirvish-emerge-menu . "groups")
    (dirvish-rsync . "rsync")
    (dirvish-file-info-menu . "file info")
    (dirvish-subtree-toggle . "subtree")
    (dirvish-quicksort . "sort")
    (dirvish-layout-toggle . "layout")
    (dirvish-history-go-backward . "hist back")
    (dirvish-history-go-forward . "hist fwd")
    (dirvish-dispatch . "menu")
    (dirvish-setup-menu . "view opts")
    (dirvish-quick-access . "quick dir")
    (dirvish-narrow . "narrow")
    (magit-section-forward . "down")
    (magit-section-backward . "up")
    (magit-mode-bury-buffer . "quit")
    (magit-section-show-level-1 . "level 1")
    (magit-section-show-level-2 . "level 2")
    (magit-section-show-level-3 . "level 3")
    (magit-section-show-level-4 . "level 4")
    (magit-section-up . "parent")
    (magit-run . "run")
    (magit-process-buffer . "process")
    (magit-worktree . "worktree")
    (magit-diff-default-context . "ctx reset")
    (magit-diff-less-context . "context -")
    (magit-diff-more-context . "context +")
    (magit-git-command . "git cmd")
    (magit-am . "am mbox")
    (magit-patch . "patch")
    (magit-ediff-dwim . "ediff")
    (magit-ediff . "ediff opt")
    (magit-rebase . "rebase")
    (magit-file-rename . "rename")
    (magit-tag . "tag")
    (magit-notes . "notes")
    (magit-show-refs . "refs")
    (magit-cherry . "unmerged")
    (magit-unstage-files . "unstage")
    (magit-unstage-all . "unstage *")
    (magit-gitignore . "ignore")
    (magit-init . "git init")
    (magit-submodule . "submodule")
    (magit-subtree . "subtree")
    (magit-push . "push")
    (magit-cherry-apply . "apply")
    (magit-cherry-pick . "pick")
    (magit-stage-files . "stage")
    (magit-stage-modified . "stage mod")
    (magit-diff . "diff")
    (magit-diff-refresh . "diff opts")
    (magit-fetch . "fetch")
    (magit-pull . "pull")
    (magit-refresh . "refresh")
    (magit-refresh-all . "refresh *")
    (magit-dispatch . "menu")
    (magit-describe-section . "sect info")
    (magit-display-repository-buffer . "repo bufs")
    (magit-file-untrack . "untrack")
    (magit-log . "log")
    (magit-log-refresh . "log opts")
    (magit-stash . "stash")
    (magit-reset-quickly . "reset now")
    (magit-reset . "reset")
    (magit-commit . "commit")
    (magit-clone . "clone")
    (magit-revert-no-commit . "reverse")
    (magit-revert . "revert")
    (magit-branch . "branch")
    (magit-bisect . "bisect")
    (magit-merge . "merge")
    (magit-remote . "remote")
    (magit-sparse-checkout . "sparse")
    (magit-section-toggle . "fold")
    (magit-visit-thing . "visit")
    (magit-diff-dwim . "show diff")
    (magit-diff-show-or-scroll-up . "preview")
    (suderman/dashboard . "dashboard")
    (suderman/ibuffer-toggle . "buffers")
    (suderman/org-agenda-dirvish . "files")
    (suderman/dirvish-side-toggle . "sidebar")
    (suderman/org-agenda-refresh . "refresh")
    (suderman/org-agenda-refresh-all . "refresh *")
    (org-agenda-limit-interactively . "limit")
    (org-agenda-toggle-deadlines . "deadlines")
    (org-agenda-dim-blocked-tasks . "blocked?")
    (org-agenda-archive . "archive")
    (org-agenda-bulk-mark-regexp . "mark re")
    (org-agenda-filter-by-top-headline . "top?")
    (org-agenda-bulk-mark-all . "mark all")
    (org-agenda-priority-down . "priority-")
    (org-agenda-priority-up . "priority+")
    (org-agenda-filter-by-effort . "effort?")
    (org-agenda-filter-by-regexp . "regexp?")
    (org-agenda-quit . "quit")
    (org-agenda-Quit . "quit all")
    (org-agenda-week-view . "week")
    (org-agenda-set-effort . "effort")
    (org-agenda-entry-text-mode . "text")
    (org-agenda-clockreport-mode . "clock sum")
    (org-agenda-todo . "TODO")
    (org-agenda-show-tags . "show tags")
    (org-agenda-year-view . "year")
    (org-agenda-bulk-unmark . "unmark")
    (org-agenda-bulk-unmark-all . "clear mrk")
    (org-agenda-diary-entry . "add diary")
    (org-agenda-clock-in . "clock in")
    (org-agenda-clock-out . "clock out")
    (org-agenda-previous-line . "up")
    (org-agenda-next-line . "down")
    (org-agenda-previous-item . "prev item")
    (org-agenda-next-item . "next item")
    (org-agenda-manipulate-query-add . "query+")
    (org-agenda-manipulate-query-add-re . "regexp+")
    (org-agenda-manipulate-query-subtract . "query-")
    (org-agenda-manipulate-query-subtract-re . "regexp-")
    (org-agenda-archive-default-with-confirmation . "archive?")
    (org-agenda-append-agenda . "append")
    (org-save-all-org-buffers . "save Org")
    (org-agenda-sunrise-sunset . "sun times")
    (org-agenda-day-view . "day")
    (org-agenda-toggle-diary . "diary")
    (org-agenda-later . "later")
    (org-agenda-earlier . "earlier")
    (org-agenda-follow-mode . "follow")
    (org-agenda-toggle-time-grid . "time grid")
    (org-agenda-holidays . "holidays")
    (org-agenda-clock-goto . "clock src")
    (org-agenda-switch-to . "visit")
    (org-agenda-recenter . "recenter")
    (org-timer-set-timer . "timer")
    (org-agenda-set-tags . "tags")
    (org-agenda-add-note . "add note")
    (org-agenda-exit . "exit/save")
    (org-agenda-clock-cancel . "clock x")
    (org-agenda-goto-calendar . "calendar")
    (org-agenda-convert-date . "date fmt")
    (org-agenda-view-mode-dispatch . "view menu")
    (org-agenda-bulk-action . "bulk menu")
    (org-agenda-bulk-toggle . "mark")
    (org-agenda-filter-by-category . "category")
    (org-agenda-filter . "filter")
    (org-agenda-show-the-flagging-note . "flag note")
    (org-agenda-filter-by-tag . "tag?")
    (org-agenda-filter-remove-all . "clear flt")
    (org-agenda-goto . "visit other window")
    (org-agenda-show-and-scroll-up . "preview / scroll")
    (org-agenda-goto-today . "today")
    (org-agenda-goto-date . "go to date")
    (org-agenda-capture . "capture")
    (org-agenda-log-mode . "log mode")
    (org-agenda-priority . "set priority")
    (org-agenda-date-prompt . "change date")
    (org-agenda-phases-of-moon . "moon phases")
    (suderman/mail-sync . "sync IMAP")
    (suderman/mail-folder . "folder")
    (suderman/mail-overview-escape . "leave input")
    (suderman/mail-archive . "archive?")
    (suderman/mail-trash . "trash?")
    (suderman/mail-folder-action-pending . "disabled")
    (notmuch-refresh-this-buffer . "refresh")
    (notmuch-jump-search . "inboxes")
    (notmuch-tree-jump-search . "inboxes")
    (notmuch-search . "search")
    (notmuch-search-by-tag . "tag query")
    (notmuch-tag-jump . "flags")
    (notmuch-tag-undo . "undo tags")
    (notmuch-help . "mode help")
    (notmuch-tree-help . "mode help")
    (notmuch-bury-or-kill-this-buffer . "quit")
    (notmuch-tree-quit . "quit")
    (notmuch-show-quit . "quit")
    (notmuch-mua-new-mail . "compose")
    (notmuch-tree-new-mail . "compose")
    (notmuch-search-next-thread . "next")
    (notmuch-search-previous-thread . "previous")
    (notmuch-search-show-thread . "thread")
    (notmuch-search-reply-to-thread-sender . "reply")
    (notmuch-search-reply-to-thread . "reply all")
    (notmuch-search-filter . "filter")
    (notmuch-search-edit-search . "edit query")
    (notmuch-search-toggle-order . "order")
    (notmuch-search-toggle-hide-excluded . "excluded?")
    (notmuch-search-scroll-up . "page down")
    (notmuch-search-scroll-down . "page up")
    (notmuch-tree-next-matching-message . "next")
    (notmuch-tree-prev-matching-message . "previous")
    (notmuch-tree-next-message . "next any")
    (notmuch-tree-prev-message . "prev any")
    (notmuch-tree-show-message . "open")
    (notmuch-tree-reply-sender . "reply")
    (notmuch-tree-reply . "reply all")
    (notmuch-tree-forward-message . "forward")
    (notmuch-tree-resume-message . "edit draft")
    (notmuch-tree-scroll-or-next . "read next")
    (notmuch-tree-next-message-button . "next part")
    (notmuch-tree-filter . "filter")
    (notmuch-tree-edit-search . "edit query")
    (notmuch-tree-toggle-order . "order")
    (notmuch-tree-toggle-hide-excluded . "excluded?")
    (notmuch-tree-to-search . "threads")
    (notmuch-search-from-tree-current-query . "threads")
    (notmuch-unthreaded-from-tree-current-query . "messages")
    (notmuch-tree-from-unthreaded-current-query . "tree")
    (notmuch-tree-to-tree . "tree")
    (notmuch-show-reply-sender . "reply")
    (notmuch-show-reply . "reply all")
    (notmuch-show-forward-message . "forward")
    (notmuch-show-resume-message . "edit draft")
    (notmuch-show-advance . "read next")
    (notmuch-show-part-map . "part menu")
    (notmuch-show-next-button . "next part")
    (notmuch-show-toggle-message . "fold")
    (notmuch-show-save-attachments . "save files")
    (notmuch-show-view-all-mime-parts . "MIME parts")
    (notmuch-tree-view-raw-message . "raw mail")
    (notmuch-draft-save . "save draft")
    (notmuch-draft-postpone . "save/close")
    (notmuch-mua-send-and-exit . "send/close?")
    (notmuch-mua-send . "send?")
    (mml-attach-file . "attach file")
    (message-insert-to . "add To")
    (message-change-subject . "edit Subject")
    (message-goto-to . "To header")
    (message-goto-cc . "Cc header")
    (message-goto-bcc . "Bcc header")
    (message-goto-subject . "Subject header")
    (message-goto-body . "body")
    (widget-forward . "next item")
    (widget-backward . "prev item")
    (widget-button-press . "open")
    (next-line . "down")
    (previous-line . "up")
    (edger-left . "window left")
    (edger-down . "window down")
    (edger-up . "window up")
    (edger-right . "window right")
    (edger-close . "close window or tab"))
  "Readable command labels for local-map cheatsheets.
Keyboard cells have nine columns; longer labels get a numbered note.
Unknown commands use their names without the mode or personal prefix.")

(defvar suderman/cheatsheet-extra-keys
  '("TAB" "RET" "SPC" "C-SPC"
    "C-c ." "C-c j" "C-c k" "C-c l" "C-c ," "C-c <" "C-c >" "C-c M"
    "M-h" "M-j" "M-k" "M-l" "M-w")
  "Keys shown below the keyboard, resolved in the invoking buffer.")

(defvar suderman/cheatsheet-views
  (append '(meow org-agenda-mode ibuffer-mode dired-mode magit-status-mode)
          (when (executable-find "notmuch")
            '(notmuch-hello-mode notmuch-search-mode notmuch-tree-mode
              notmuch-show-mode notmuch-message-mode)))
  "Sheets available through next/previous cycling.
Dired and Dirvish share a map.  Other invoking modes join this list locally.")

(defvar-local suderman/cheatsheet-origin nil
  "Buffer from which keyboard help was opened.")

(defvar-local suderman/cheatsheet-view nil
  "View currently shown in keyboard help.")

(defun suderman/cheatsheet-disable-meow ()
  "Keep the cheatsheet's own navigation and quit bindings active."
  (if (bound-and-true-p meow-mode)
      (meow-mode -1)
    (meow--disable)))

(define-derived-mode suderman/cheatsheet-mode special-mode "Cheatsheet"
  "Read a keyboard cheatsheet; quit returns to the invoking view."
  (setq-local truncate-lines t)
  (add-hook 'meow-mode-hook #'suderman/cheatsheet-disable-meow nil t)
  (suderman/cheatsheet-disable-meow))

(keymap-set suderman/cheatsheet-mode-map "SPC" #'meow-keypad)
(keymap-set suderman/cheatsheet-mode-map "h" #'quit-window)
(keymap-set suderman/cheatsheet-mode-map "<escape>" #'quit-window)
(keymap-set suderman/cheatsheet-mode-map "n" #'suderman/cheatsheet-next)
(keymap-set suderman/cheatsheet-mode-map "p" #'suderman/cheatsheet-previous)

(defun suderman/cheatsheet-command-label (command mode)
  "Return a readable label for COMMAND in MODE."
  (or (alist-get command suderman/cheatsheet-command-labels)
      (alist-get command meow-command-to-short-name-list)
      (when (and command (symbolp command))
        (let ((name (string-remove-prefix "suderman/" (symbol-name command)))
              (prefix (string-remove-suffix "-mode" (symbol-name mode))))
          (string-remove-prefix (concat prefix "-") name)))
      ""))

(defun suderman/cheatsheet-local-content ()
  "Render the current buffer's effective bindings as a keyboard sheet."
  (let ((mode major-mode)
        (title (pcase major-mode
                 ('notmuch-hello-mode "Mail overview")
                 ('notmuch-search-mode "Mail threads")
                 ('notmuch-tree-mode "Mail messages")
                 ('notmuch-show-mode "Read mail")
                 ('notmuch-message-mode "Compose mail")
                 (_ (capitalize
                     (string-replace "-" " "
                                     (string-remove-suffix "-mode" (symbol-name major-mode)))))))
        ;; Overview's search widget treats letters as input.  Show command keys
        ;; rather than a blank typing map, without changing the live field.
        (overriding-local-map (if (eq major-mode 'notmuch-hello-mode)
                                 (current-local-map)
                               overriding-local-map))
        (bindings (make-sparse-keymap))
        (keyboard-keys (apply #'append (mapcar #'cdr meow-cheatsheet-layout)))
        (suderman/cheatsheet-extra-keys
         (append suderman/cheatsheet-extra-keys
                 (when (eq major-mode 'notmuch-hello-mode)
                   '("<escape>"))
                 (when (memq major-mode '(notmuch-search-mode notmuch-tree-mode notmuch-show-mode))
                   '("C-v"))
                 (when (eq major-mode 'notmuch-show-mode)
                   '("C-c ."))
                 (when (eq major-mode 'notmuch-message-mode)
                   '("C-x C-s" "C-c C-p" "C-c C-c" "C-c C-s" "C-c C-a"
                     "C-c C-t" "C-c C-f s" "C-c C-b"))))
        labels extras notes)
    ;; Snapshot before entering the help buffer, including command remaps.
    (dolist (key (append keyboard-keys suderman/cheatsheet-extra-keys))
      (let* ((command (or (key-binding (kbd key)) 'undefined))
             (label (suderman/cheatsheet-command-label command mode)))
        (keymap-set bindings key command)
        (when (and (member key keyboard-keys) (not (assq command labels)))
          (let ((cell label))
            (when (> (string-width label) 9)
              (setq cell (format "[%d]" (1+ (length notes))))
              (push (cons cell label) notes))
            (push (cons command cell) labels)))
        (when (and (member key suderman/cheatsheet-extra-keys)
                   (not (string-empty-p label)))
          (push (format "%7s  %s" key label) extras))))
    (with-temp-buffer
      (let (;; Key lookup in a new GUI frame can use another keyboard's
            ;; terminal map.  The nonterminal override follows this render.
            (overriding-terminal-local-map nil)
            (overriding-local-map bindings)
            (meow-command-to-short-name-list labels))
        (insert title " cheatsheet\n" meow-cheatsheet-physical-layout)
        (meow--cheatsheet-replace-keysyms)
        (add-face-text-property (point-min) (point-max) 'meow-cheatsheet-command)
        (goto-char (point-max))
        (insert "\nOther keys\n")
        (dolist (row (seq-partition (nreverse extras) 3))
          (insert (mapconcat (lambda (entry) (format "%-44s" entry)) row "  ") "\n"))
        (when notes
          (insert "\nLabel notes\n")
          (dolist (note (nreverse notes))
            (insert (format "  %s  %s\n" (car note) (cdr note)))))
        (cond
         ((eq mode 'notmuch-message-mode)
          (insert "\nCompose uses Meow and meow-purrsist. i enters Insert; Escape returns to Normal.\n"
                  "Save keeps a local draft, not phone Drafts. Sending asks for confirmation.\n"
                  "M-x suderman/mail-draft-from-org builds a rich draft without sending.\n"))
         ((memq mode '(notmuch-hello-mode notmuch-search-mode notmuch-tree-mode notmuch-show-mode))
          (insert "\nSPC: keypad. ,: buffers. .: files. h: back. l: Return action. /: search/filter.\n"
                  "J: saved searches. i personal, w work, u unread, f stars, d local drafts, s Sent.\n"
                  "G fetches/syncs IMAP; wait for completion, then g refreshes.\n")
          (when (eq mode 'notmuch-hello-mode)
            (insert "Overview lists saved searches and folders. In its search field, letters type a query.\n"
                    "Escape leaves input unchanged and restores command keys. TAB moves between widgets.\n"
                    "This diagram shows overview commands, not the field's typing keys.\n"))
          (unless (eq mode 'notmuch-hello-mode)
            (insert "t r/u: read/unread. t f/F: star/unstar. Flags sync; folders organize mail.\n"
                    "a/x confirm single Inbox-copy moves. A/X and thread-row moves are disabled.\n"
                    "Moves sync with G. Trash follows provider retention rules.\n"))))
        (buffer-string)))))

(defun suderman/cheatsheet-view-content (view origin)
  "Render VIEW using ORIGIN, an open view, or its configured mode map."
  (if (eq view 'meow)
      (let ((existing (get-buffer "*Meow Cheatsheet*")))
        (unwind-protect
            (save-window-excursion
              (with-current-buffer origin (meow-cheatsheet))
              (with-current-buffer (window-buffer)
                (string-trim-left (buffer-string))))
          (unless existing
            (when-let* ((buffer (get-buffer "*Meow Cheatsheet*")))
              (kill-buffer buffer)))))
    (let ((source
           (seq-find (lambda (buffer)
                       (with-current-buffer buffer
                         (and (derived-mode-p view)
                              (or (eq view 'notmuch-message-mode)
                                  (not (bound-and-true-p meow-mode))))))
                     (cons origin (delq origin (buffer-list))))))
      (if source
          (with-current-buffer source (suderman/cheatsheet-local-content))
        ;; Reference sheets need keymaps, not live Agenda, explorer, or Git sessions.
        (pcase view
          ('org-agenda-mode (require 'org-agenda))
          ('ibuffer-mode (require 'ibuffer))
          ('dired-mode (require 'dirvish))
          ('magit-status-mode (require 'magit))
          ((or 'notmuch-hello-mode 'notmuch-search-mode 'notmuch-tree-mode
               'notmuch-show-mode 'notmuch-message-mode)
           (require 'notmuch)))
        (with-temp-buffer
          (setq major-mode view)
          (use-local-map (copy-keymap (symbol-value (intern (format "%s-map" view)))))
          (if (eq view 'notmuch-message-mode)
              (progn
                ;; Derived-mode inheritance is installed lazily on first compose.
                (set-keymap-parent (current-local-map) message-mode-map)
                (meow-mode 1))
            (suderman/cheatsheet-disable-meow))
          (when (eq view 'magit-status-mode)
            (suderman/magit-setup))
          (suderman/cheatsheet-local-content))))))

(defun suderman/cheatsheet-update ()
  "Replace the displayed keyboard sheet without changing its quit target."
  (let ((content (suderman/cheatsheet-view-content
                  suderman/cheatsheet-view suderman/cheatsheet-origin))
        (inhibit-read-only t))
    (erase-buffer)
    (insert content
            "\nC-c h: context cheatsheet. In keypad views, SPC ? does the same.\n"
            "SPC o opens Org commands where SPC invokes the Meow keypad.\n"
            "Other sheets use an open view or its configured mode map.\n"
            "After closing, C-h k describes a key; C-h m opens native mode help.\n")
    (goto-char (point-min))
    (forward-line 1)
    (insert "n/p: next/previous sheet. q, h, or Escape closes help.\n")
    (goto-char (point-min))))

(defun suderman/cheatsheet-cycle (step)
  "Move STEP sheets, wrapping at either end."
  (setq suderman/cheatsheet-view
        (nth (mod (+ (cl-position suderman/cheatsheet-view suderman/cheatsheet-views) step)
                  (length suderman/cheatsheet-views))
             suderman/cheatsheet-views))
  (suderman/cheatsheet-update))

(defun suderman/cheatsheet-next ()
  "Show the next keyboard sheet."
  (interactive)
  (suderman/cheatsheet-cycle 1))

(defun suderman/cheatsheet-previous ()
  "Show the previous keyboard sheet."
  (interactive)
  (suderman/cheatsheet-cycle -1))

;;;###autoload
(defun suderman/cheatsheet ()
  "Show the invoking view's keyboard bindings, with n/p sheet cycling."
  (interactive)
  (with-current-buffer (window-buffer (selected-window))
    (if (derived-mode-p 'suderman/cheatsheet-mode)
        (suderman/cheatsheet-update)
      (let* ((origin (current-buffer))
             (view (cond
                    ((derived-mode-p 'notmuch-message-mode) 'notmuch-message-mode)
                    ((bound-and-true-p meow-mode) 'meow)
                    (t (or (seq-find #'derived-mode-p (remq 'meow suderman/cheatsheet-views))
                           major-mode))))
             (views (if (memq view suderman/cheatsheet-views)
                        suderman/cheatsheet-views
                      (append suderman/cheatsheet-views (list view))))
             (buffer (get-buffer-create "*Keyboard Cheatsheet*")))
        (with-current-buffer buffer
          (suderman/cheatsheet-mode)
          (setq-local suderman/cheatsheet-origin origin
                      suderman/cheatsheet-view view
                      suderman/cheatsheet-views views)
          (suderman/cheatsheet-update))
        (pop-to-buffer buffer '(display-buffer-same-window))))))

(provide 'suderman-help)
;;; suderman-help.el ends here
