;;; suderman-meow.el --- Meow modal editing setup -*- lexical-binding: t; -*-

;;; Commentary:
;; Meow gives modal editing while leaving vanilla Emacs keymaps available through
;; its keypad.  Keep the upstream QWERTY layout recognizable, then layer only the
;; personal behavior that belongs to the modal core.

;;; Code:

(require 'subr-x)
(require 'use-package)

(defvar suderman/meow-leader-map (make-sparse-keymap)
  "Owned keymap for Suderman's Meow SPC leader bindings.")

(defun suderman/meow-reset-leader-map ()
  "Reset and install Suderman's owned Meow leader map."
  (setq suderman/meow-leader-map (make-sparse-keymap))
  (when (boundp 'meow-keymap-alist)
    (setf (alist-get 'leader meow-keymap-alist) suderman/meow-leader-map))
  suderman/meow-leader-map)

(defun suderman/meow-paste-below ()
  "Paste like Vim p: after point, or below current line for linewise text."
  (interactive)
  (let ((text (current-kill 0)))
    (when (string-empty-p text)
      (user-error "Kill ring is empty"))
    (cond
     ((use-region-p)
      (let ((beg (region-beginning)))
        (kill-region (region-beginning) (region-end))
        (insert text)
        (goto-char beg)))
     ((string-suffix-p "\n" text)
      (let ((content (substring text 0 -1))
            target)
        (end-of-line)
        (insert "\n")
        (setq target (point))
        (insert content)
        (goto-char target)
        (back-to-indentation)))
     (t
      (unless (or (eobp) (eolp))
        (forward-char 1))
      (insert text)
      (backward-char 1)))))

(defun suderman/meow-paste-above ()
  "Paste like Vim P: before point, or above current line for linewise text."
  (interactive)
  (let ((text (current-kill 0)))
    (when (string-empty-p text)
      (user-error "Kill ring is empty"))
    (cond
     ((use-region-p)
      (let ((beg (region-beginning)))
        (kill-region (region-beginning) (region-end))
        (insert text)
        (goto-char beg)))
     ((string-suffix-p "\n" text)
      (let ((content (substring text 0 -1))
            target)
        (beginning-of-line)
        (setq target (point))
        (insert content "\n")
        (goto-char target)
        (back-to-indentation)))
     (t
      (insert text)
      (backward-char 1)))))

(defun suderman/meow-setup-qwerty ()
  "Install Meow's upstream QWERTY layout with local paste/redo tweaks."
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . suderman/meow-paste-below)
   '("P" . suderman/meow-paste-above)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("C-r" . undo-redo)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :demand t
  :init
  (setq meow-use-clipboard t
        meow-mode-state-list
        '((conf-mode . normal)
          (fundamental-mode . normal)
          (prog-mode . normal)
          (text-mode . normal)
          (dired-mode . motion)
          (dirvish-mode . motion)
          (help-mode . motion)
          (Info-mode . motion)
          (special-mode . motion)
          (compilation-mode . motion)
          (grep-mode . motion)
          (occur-mode . motion)
          (messages-buffer-mode . motion)
          (eshell-mode . insert)
          (shell-mode . insert)
          (term-mode . insert)
          (vterm-mode . insert)))
  :config
  (suderman/meow-reset-leader-map)
  (suderman/meow-setup-qwerty)
  (meow-global-mode 1))

(provide 'suderman-meow)
;;; suderman-meow.el ends here
